### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Clubeddie** [pippyn/Home-Assistant-Sensor-Afvalbeheer#10]
I have an issue with HA version 0.93.2. Afvalbheer won't show any data anymore.

In the log file i see:

`2019-05-25 12:07:40 ERROR (SyncWorker_12) [custom_components.afvalbeheer.sensor] Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='inzamelkalender.hvcgroep.nl', port=443): Max retries exceeded with url: /rest/adressen/[mypostalcode] (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x6cdbbf10>: Failed to establish a new connection: [Errno -3] Try again'))"))`

Any clue?

**Comment by pippyn** [comment]
Are you still having these issues? what is the config you are using?

**Comment by pippyn** [comment]
I'll close this issue due to inactivity
