### ISSUE TITLE
Kan jij almere toevoegen aub? 

### ISSUE THREAD

**Issue by zhinees** [pippyn/Home-Assistant-Sensor-Afvalbeheer#100]
https://afvalportaal.2go-mobile.com/modules/53d8db94-7945-42fd-9742-9bbc71dbe4c1/kalender/

test data: 1336AK  nr 40.

**Comment by pippyn** [comment]
Sure! Support for Almere added in version 4.3.1

**Comment by zhinees** [comment]
Wow, wat geweldig!!! Zo snel ook nog. Dank je wel!! Ik ga wat koffie voor je regelen.
