### ISSUE TITLE
RD4 doesn't work?

### ISSUE THREAD

**Issue by cschillings** [pippyn/Home-Assistant-Sensor-Afvalbeheer#101]
The RD4 integration doesn't work for me, it only says unknown.
Can you check the API connection please?

![Screenshot_20200528-233818__01](https://user-images.githubusercontent.com/60855190/83196565-6c947600-a13c-11ea-908b-af6a157d7b8e.jpg)

I saw this:
JSON: https://app.rd4.nl/nsi/api/v1/wastecalendars. This is what the official RD4 'Milieu App' connects to, and returns categories where 0 is restafval, 1 is GFT, 2 is Oud Papier, 3 is Snoeiafval, 4 is Kerstbomen, 5 is PMD and 6 is BEST. This requires an API_KEY and Basic Authorization header (see below).

HTML: https://www.rd4info.nl/NSI/Burger/Aspx/afvalkalender_public_text.aspx?pc=POSTALCODE&nr=NUMBER&t=ADDITION, e.g.: https://www.rd4info.nl/NSI/Burger/Aspx/afvalkalender_public_text.aspx?pc=6411XZ&nr=41&t=. This is not my address, just grabbed one from Funda.

JSON: https://rd4.syzygy.eu/POSTALCODE/NUMBER/, e.g.: https://rd4.syzygy.eu/6411XZ/41. I'm not entirely sure where this URL comes from and if it's future proof.

Only the HTML one seems to work???

**Comment by pippyn** [comment]
Hey @cschillings, thanks for the bug report.

When I use the address you provided with this config:
```
  - platform: afvalbeheer
    wastecollector: RD4
    resources:
        - gft
        - pmd
        - papier
    postcode: 6411XZ
    streetnumber: 41
```
The sensor works fine for me:
![image](https://user-images.githubusercontent.com/7591990/83229471-590efc80-a188-11ea-9d66-e30f035ffeb9.png)

Can you check your logs for errors?

FYI: the sensor uses the syzygy.eu API

> JSON: https://rd4.syzygy.eu/POSTALCODE/NUMBER/, e.g.: https://rd4.syzygy.eu/6411XZ/41. I'm not entirely sure where this URL comes from and if it's future proof.

**Comment by cschillings** [comment]
I give it a try for that postcode

**Comment by cschillings** [comment]
This is my config in sensor.yaml. same issue for that postcode...

  - platform: afvalbeheer
    wastecollector: RD4
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 6411XZ
    streetnumber: 41

**Comment by pippyn** [comment]
and the error log?

**Comment by cschillings** [comment]
Where can i check that? Cant find anything in logbookm

**Comment by cschillings** [comment]
I think this?

Logboekdetails (ERROR)
Logger: homeassistant.core
Source: custom_components/afvalbeheer/sensor.py:970
First occurred: 9:25:23 (1 occurrences)
Last logged: 9:25:23

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 337, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 970, in update
    response = r.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by cschillings** [comment]
Logboekdetails (ERROR)
Logger: homeassistant.core
Source: custom_components/afvalbeheer/sensor.py:970
First occurred: 9:44:57 (1 occurrences)
Last logged: 9:44:57

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 337, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 970, in update
    response = r.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by pippyn** [comment]
Looks like you are blocked or something. I need some more time to investigate.

**Comment by cschillings** [comment]
Thank you, let me know if you want.

**Comment by pippyn** [comment]
In my testing i found that syzygy.eu only allows IPv4 addresses and blocks IPv6 addresses. So I'm guessing you have an IPv6 address, correct?

**Comment by cschillings** [comment]
Both but main protocal is IPv4.
My HA ip is IPV4 so that must be working normaly.

**Comment by pippyn** [comment]
Is your HA on the ziggo network (which has an IPv6)? then your HA also has a IPv6.
Contact Ziggo for help to change back to IPv4. Maybe a modem/router setting?

**Comment by cschillings** [comment]
There is not such a option, already checked that.
Can i disable it in HA/HASSIO???

**Comment by cschillings** [comment]
Found a workaround for this problem. Change IPv6 settings in Ziggo ConnectBox from Stateless (SLAAC) to Stateful (DHCPv6)
![IPv6](https://user-images.githubusercontent.com/60855190/83275514-87fc9100-a1cf-11ea-8b02-0ba945f33911.PNG)
