### ISSUE TITLE
Meerlanden seems to not working

### ISSUE THREAD

**Issue by HoekieN** [pippyn/Home-Assistant-Sensor-Afvalbeheer#104]
It looks like Meerlanden is nog working, or at least for me:
![image](https://user-images.githubusercontent.com/28273279/83522125-80dfc680-a4e0-11ea-8f1c-f936e46b2a14.png)
![image](https://user-images.githubusercontent.com/28273279/83522170-96ed8700-a4e0-11ea-8916-697870e50aa0.png)

My config:
  - platform: afvalbeheer
    wastecollector: meerlanden
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: xxxxxx
    streetnumber: xx
    upcomingsensor: 1

**Comment by pippyn** [comment]
any errors in the log?

**Comment by HoekieN** [comment]
The supervisor and core log have no errors

**Comment by HoekieN** [comment]
example postcode: 1433ac 3

**Comment by pippyn** [comment]
hmm for me it's working fine:
![image](https://user-images.githubusercontent.com/7591990/83525355-27c66180-a4e5-11ea-9bb8-8141deab4431.png)

Does the kalender give the correct info?
https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/

**Comment by pippyn** [comment]
With your example address the logs say: "Address not found".
I'll look into this issue. Did the sensor used to work for you?

**Comment by HoekieN** [comment]
Thanks for checking, it is first time i am using this sensor.

**Comment by temmink** [comment]
it's also not working for me. (no error in the log).
I do get my information when I manually enter my zipcode and house number in the link provided by pippyn.

**Comment by pippyn** [comment]
I'm unable to find a fix. But I did find a work around (added in v4.5.0).

1. Go to https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/ 
2. Enter your postcode and streetnumber
3. Click "Volgende"
4. Look at the url, for 1433ac 3 it looks like this: https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/calendar.html?1000088827&Schweitzerstraat---3%20%20%20---1433AC---Kudelstaart---Aalsmeer
5. Copy the code after `calendar.html?` and before `&`. In this example it's `1000088827`
6. Add the option `addressid` to you config (postcode and streetnumber are required to!):

```
- platform: afvalbeheer
  wastecollector: Meerlanden
  resources:
      - gft
      - restafval
      - takken
  postcode: 1433ac
  streetnumber: 3
  addressid: 1000088827
```

Let me know if it works!

**Comment by HoekieN** [comment]
Awesome, it works now.
