### ISSUE TITLE
Build in icons barely visible in ios-dark-mode theme 

### ISSUE THREAD

**Issue by ericvb** [pippyn/Home-Assistant-Sensor-Afvalbeheer#109]
Apparently my waste collector Ophaalkalender doesn't send icons with his api, so I wanted to use the building icons.
But in the ios-dark-mode theme these are barely visible :-(
On my desktop pc they are not visible, on my tablet they are barely visible...

**Comment by pippyn** [comment]
You can use what ever icons you want. You don't need to use the builtin icons.

**Comment by ericvb** [comment]
Okay, I searched in the home assistant forum how to do that and of course it is simple, use the default possibility of HA to customize sensors.

You should mention that in your Readme.md to avoid repeating yourself the answer ;-)
