### ISSUE TITLE
after update to 4.3.2 Circulus Berkel no longer visible

### ISSUE THREAD

**Issue by InvertedMinor** [pippyn/Home-Assistant-Sensor-Afvalbeheer#110]
Sensors give status Unknown

**Comment by pippyn** [comment]
For me Circulus Berkel sensor is working.

Does https://mijn.circulus-berkel.nl/afvalkalender/ give you the correct information?
Any errors in your log?

**Comment by InvertedMinor** [comment]
1) yes
2) no errors

But an extra restart solved it...

**Comment by pippyn** [comment]
oke glad it's working now
