### ISSUE TITLE
[Feature request] List available resources per collector

### ISSUE THREAD

**Issue by DrBlokmeister** [pippyn/Home-Assistant-Sensor-Afvalbeheer#112]
Right now it can be difficult to determine which resource are available for which collector. For example: Waalre switched from PBD to PMT, and my notifications for PBD stopped working. I think it would be nice to either have a list of available resources per collector (in readme or documents) or to let the component automatically select all available resources.

**Comment by pippyn** [comment]
Great idea! Will look into it

**Comment by pippyn** [comment]
Added this option in version 4.4.0. Are you willing to test?

Update and set [this option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions)

**Comment by DrBlokmeister** [comment]
Hey Pippyn!

I updated, set the option and checked the logs:
![image](https://user-images.githubusercontent.com/57352628/86899144-e6d7f300-c109-11ea-8ce0-b0ed23fc1f68.png)

The sensors are working just fine. Great update! :)

If I may make another suggestion, maybe it's a good idea to simply display these values during the first startup of the plugin, or if the option has been set to true.

**Comment by pippyn** [comment]
> If I may make another suggestion, maybe it's a good idea to simply display these values during the first startup of the plugin, or if the option has been set to true.
I have no easy way of knowing if the sensor was just installed and that it is the first start up. But I will look into it.

BTW in a next version the list will be displayed in the notification panel instead of the error log.  Which would be nicer I think.

**Comment by DrBlokmeister** [comment]
Sounds good!

**Comment by pippyn** [comment]
The latest version now displays the information in the notification panel

**Comment by DrBlokmeister** [comment]
Thanks Pippyn! Off topic, but you helped me to not forget my garbage and hence make my life a tiny bit better. Kudos to you!
