### ISSUE TITLE
Omrin integration - Sortibak icon [request]

### ISSUE THREAD

**Issue by JayOne73** [pippyn/Home-Assistant-Sensor-Afvalbeheer#115]
First of all thanks for the Omrin integration (finally I can use this sensor).

I'm using the built in icons, only for the Sortibak resource there is no icon available. Because the Sortibak is some sort of Restafval, could you map the Restafval-icon to the Sortibak resource?

**Comment by pippyn** [comment]
First of all; sorry for replying so late.

I can map the icon to sortibak also, but as I've seen in a few cases some waste collectors have both restafval and sortibak for some reason. That would make it unclear. When I have some time I'll add a new icon for sortibak (I also want to add new icons that are not only in black, but change color with your theme), but it's not high on my list as I'm quite swamped with work right now. If you (or someone else) can design some cool icons I'm willing to implement them. The have to be svg though.

> First of all thanks for the Omrin integration (finally I can use this sensor).

Sorry it took me so long ;)
