### ISSUE TITLE
Can't find Afvalbeheer in HACS

### ISSUE THREAD

**Issue by Mikomie** [pippyn/Home-Assistant-Sensor-Afvalbeheer#116]
Hi
i've removed ophaalkalender since I got the message it was depricated and now included in Afvalbeheer. However in your git readme it sais it can be added trough HACS but i can't seem to find it, what should i search for?
H

**Comment by pippyn** [comment]
You should search for "Afvalbeheer"

**Comment by Mikomie** [comment]
I did but it gave me zero results :(

**Comment by pippyn** [comment]
Just tested it and for me it works. Is your HACS up to date?
![image](https://user-images.githubusercontent.com/7591990/85535877-dfe1b880-b612-11ea-9327-e6a855e7b7d8.png)
Maybe "Afvalbeheer" is already installed?

**Comment by Mikomie** [comment]
I had the "ophaalkalender" installed trough hacs but not this one.
Your screenshot looks different so i guesst there is something wrong with mine.
![afbeelding](https://user-images.githubusercontent.com/49552571/85537008-e15fb080-b613-11ea-89be-70db7eb257fe.png)

**Comment by pippyn** [comment]
You are searching your installed integrations. Not new integrations

**Comment by Mikomie** [comment]
I don't have those installed. I'm thinking something else is wrong with hacs it does not all look like it should i think:
I do get a message not loaded in lovelace, so perhaps that's the issue, but that's foor the HA community forum if that's what's causing this problem.
![afbeelding](https://user-images.githubusercontent.com/49552571/85538061-d2c5c900-b614-11ea-9dcb-0127815c339b.png)

**Comment by Mikomie** [comment]
Oh god... I feel like a fool, that was a list of "new" repositories, in the right bottom corner was a circle with + icon ...

**Comment by pippyn** [comment]
No that error means your lovelace cards are not loaded correctly. You need to click on integrations (below the error) then on the plus icon (bottom right).
