### ISSUE TITLE
Request: Support waste collector Afval Schouwen-Duiveland

### ISSUE THREAD

**Issue by Mipilo** [pippyn/Home-Assistant-Sensor-Afvalbeheer#117]
Hello,

Is it possible to support the waste collector: Afval Schouwen-Duiveland
https://play.google.com/store/apps/details?id=nl.opzet.zcalendar.schouwenduiveland

4328AE - 1

Thanks!

**Comment by pippyn** [comment]
Added support in version 4.3.3

**Comment by Mipilo** [comment]
Wow you are fast 👍 
Thanks Pippyn. It works!
