### ISSUE TITLE
PMD data not pulled for location "wijk bij duurstede"

### ISSUE THREAD

**Issue by Lucus123** [pippyn/Home-Assistant-Sensor-Afvalbeheer#119]
postcode area 3962 has a different type mapping for PMD
it appaers its trying to pull "plastic" but in this postcode region its defined as pmd in the dictionary on the side of mijnafvalwijzer.nl
can you change it so it tries to pull type mapping "pmd"?

**Comment by pippyn** [comment]
I'm not sure what you mean by `trying to pull "plastic"`? The sensor doesn't pull any fractions on it's own. It just requests all dates for all fractions of a certain address.

But I found the issue. They named PMD `gkbp` for some reason. And it's supported in version 4.3.4
