### ISSUE TITLE
Update documentation to include fraction type PBD

### ISSUE THREAD

**Issue by kaosmagix** [pippyn/Home-Assistant-Sensor-Afvalbeheer#12]
I couldn't get PMD to work with the waste collector GAD, browsing through the closed issues I found the reason, the fraction is called PBD. This type is not mentioned in the documentation, it would be helpful to add this in the list of fraction types and add an explanation this is commonly used instead of PMD. 

Great work on this (I was looking for this functionality and thanks to HACS found it)

**Comment by pippyn** [comment]
Will do! thank you for the feedback

**Comment by rickvanassema** [comment]
The builtinicons don't seem to work for the PBD ? Is there a way to fix this? I now have one orange icon among black and whites...

**Comment by rickvanassema** [comment]
Nice functionality btw. Haven't forgotten to put the trash out since i installed it. ;)

**Comment by pippyn** [comment]
I don't have an icon for that sadly. If you can make one in svg format, i'll look into adding it.

**Comment by rickvanassema** [comment]
It is the same as PMD? Or is there no icon for PMD as well? I'll have a look and give it a try when i'm back from holiday. :)

**Comment by pippyn** [comment]
You are right. I'll add it in the next release.

**Comment by pippyn** [comment]
Added in release v2.4.1
