### ISSUE TITLE
GAD PBD/PMD unknown

### ISSUE THREAD

**Issue by PostSven** [pippyn/Home-Assistant-Sensor-Afvalbeheer#120]
GAD PBD is not returning any data

`###afvalbeheer_component
  - platform: afvalbeheer
    wastecollector: GAD
    resources:
      - restafval
      - gft
      - papier
      - pbd
    upcomingsensor: 1
    postcode: *****
    streetnumber: ****
    dutch: 1
    dateonly: 1`

**Comment by pippyn** [comment]
use pmd, not pbd

**Comment by PostSven** [comment]
Check, thanks
