### ISSUE TITLE
Can you put 'vandaag'/'morgen' in a attribute instead of in the state?

### ISSUE THREAD

**Issue by bobvmierlo** [pippyn/Home-Assistant-Sensor-Afvalbeheer#123]
Would you be able to put values like Vandaag and Morgen in a separate attribute instead of adding it in front of the state?
Or.. only put Vandaag/Morgen in the state without the date value.

This would make it much easier to create templated automations.

**Comment by pippyn** [comment]
You can use the attributes `Sort-date` and `Days-until` for automations. 
And if you want you can set the [`dateonly` option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#date-only) to disable the prefix altogether.

**Comment by pippyn** [comment]
does this suffice?

**Comment by bobvmierlo** [comment]
Yes thanks
