### ISSUE TITLE
Limburg.net Incorrect Mapping

### ISSUE THREAD

**Issue by Milithor** [pippyn/Home-Assistant-Sensor-Afvalbeheer#127]
I was coding my own Limburg.net component until I saw you provided support for it recently, many thanks for this!
When installing I found out the following:

Mapping between names of Limburg.net and collector are currently incorrect.
I had to modify some one the left side of the mapping within class "LimburgNetCollector"
Most common items that are collected on street level / known:

```
    WASTE_TYPE_MAPPING = {
        'Grofvuil': WASTE_TYPE_BULKLITTER,
        'Groenafval': WASTE_TYPE_BULKYGARDENWASTE,
        'Glas': WASTE_TYPE_GLASS,
        'Gft': WASTE_TYPE_GREEN,
        'Huisvuil': WASTE_TYPE_GREY,
        'Pmd': WASTE_TYPE_PACKAGES,
        'Papier & karton': WASTE_TYPE_PAPER,
        'Textiel': WASTE_TYPE_TEXTILE
    }
```

No clue if you want to change this, but couldn't hurt on reporting this.

**Comment by pippyn** [comment]
Added in v4.6.0
