### ISSUE TITLE
limburg.net fetch address issue

### ISSUE THREAD

**Issue by kevin-croughs** [pippyn/Home-Assistant-Sensor-Afvalbeheer#134]
Hi, just tried to configure the integration with limburg.net, but the following issue arises:
Log Details (ERROR)
Logger: homeassistant
Source: custom_components/afvalbeheer/sensor.py:711
First occurred: 2:49:07 PM (1 occurrences)
Last logged: 2:49:07 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 387, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 750, in update
    await self.hass.async_add_executor_job(self.__fetch_address)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 711, in __fetch_address
    if not response[0]['nisCode']:
IndexError: list index out of range

I did specify the streetnumber, streetname, postcode.

**Comment by pippyn** [comment]
what is your config? please use an address in your neighborhood.

**Comment by kevin-croughs** [comment]
Hi, here is my config (address was slightly changed):

sensor:  
  - platform: afvalbeheer
    wastecollector: Limburg.NET
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: '3870'
    streetnumber: 3
    streetname: Bovelingenstraat
    upcomingsensor: 0
    dateformat: '%d-%m-%Y'
    dateonly: 0
    dateobject: 0
    name: ''
    nameprefix: 1
    builtinicons: 0
    disableicons: 0
    dutch: 0

**Comment by kevin-croughs** [comment]
Hmmm, seems like the indentation is not correct here, this is it : 
`sensor:  
  - platform: afvalbeheer
    wastecollector: Limburg.NET
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: '3870'
    streetnumber: 3
    streetname: Bovelingenstraat
    upcomingsensor: 0
    dateformat: '%d-%m-%Y'
    dateonly: 0
    dateobject: 0
    name: ''
    nameprefix: 1
    builtinicons: 0
    disableicons: 0
    dutch: 0`

**Comment by kevin-croughs** [comment]
Never mind the indentation, I can't seem to get it right here in the comment box, it is correct in the actual config

**Comment by pippyn** [comment]
you are missing the [`cityname option`](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#cityname) which is required for limburg.net

**Comment by pippyn** [comment]
And Bovelingenstraat 3, 3870, Heers is not a correct address according to Limburg.net

**Comment by kevin-croughs** [comment]
You’re totally right, I overlooked the cityname option in the documentation. Sorry about this, it is working now.
