### ISSUE TITLE
[RecycleApp] IndexError: list index out of range

### ISSUE THREAD

**Issue by Twanislas** [pippyn/Home-Assistant-Sensor-Afvalbeheer#135]
Hi,

Since the `ophaalkalender` -> `recycleapp` move, my trash sensors were showing `Unknown`. I've looked at the logs but could not find anything. Browsing the repo I noticed a commit in flight mentioning RecycleApp so I waited until the next release which would include it. Today I updated with latest 4.6.2 and I got this error in my logs :
```
2020-08-11 18:02:08 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 424, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 1099, in update
    await self.hass.async_add_executor_job(self.__get_location_ids)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 1077, in __get_location_ids
    self.street_id = response.json()['items'][0]['id']
IndexError: list index out of range
```

Please let me know if I can provide further info to help debug the issue ;)

Cheers !

**Comment by pippyn** [comment]
can you also give me your config please? with an address in your neighborhood?

**Comment by Twanislas** [comment]
Sure, sorry, should have included it... ;)
```yaml
- platform: afvalbeheer
  wastecollector: RecycleApp
  resources:
    - restafval
    - papier
    - pmd
  postcode: !secret trash_postcode
  streetname: !secret trash_streetname
  streetnumber: !secret trash_streetnumber
  dateformat: "%Y-%m-%d"
  dateonly: 1
  disableicons: 1
  dateobject: 1
  upcomingsensor: 1
  name: trash
  nameprefix: 0
```
Secrets being (not the real address) :
```yaml
trash_postcode: 7110
trash_streetname: Beau Site avenue
trash_streetnumber: 8
```
Thanks for looking into it !

**Comment by pippyn** [comment]
I'm unable to find that address on [recycleapp.be](https://recycleapp.be/home)
is the address correct?

**Comment by Twanislas** [comment]
Yes, I double checked, and it's the same as before the move to RecycleApp. That being said, it works in the mobile app but not on their website. I guess their devs broke something (as usual).
I sent them an email, we'll see what comes out...

I'll go ahead and close this since I think the issue is on their side...

Thanks anyways !
