### ISSUE TITLE
Add for irado (schiedam, vlaardingen ao)

### ISSUE THREAD

**Issue by 1ntroduc3** [pippyn/Home-Assistant-Sensor-Afvalbeheer#138]
https://www.irado.nl/bewoners/afvalkalender 
THanks

**Comment by pippyn** [comment]
Could you please provide an address for me to test with?

**Comment by 1ntroduc3** [comment]
3136 JH 21


Best regards,

Mart Heijnen
Denk aan het milieu voordat u dit bericht print!


________________________________
Van: Pippyn <notifications@github.com>
Verzonden: woensdag 2 september 2020 13:52
Aan: pippyn/Home-Assistant-Sensor-Afvalbeheer <Home-Assistant-Sensor-Afvalbeheer@noreply.github.com>
CC: 1ntroduc3 <mart.heijnen@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [pippyn/Home-Assistant-Sensor-Afvalbeheer] Add for irado (schiedam, vlaardingen ao) (#138)


Could you please provide an address for me to test with?

**Comment by pippyn** [comment]
I'm sorry. I couldn't find an API. They are using CF7 in wordpress as it seems for the data. Without access to their sites REST API, I'm unable to request the data.

You could use a scraper sensor to get the data as this sensor does (https://github.com/heyajohnny/afvalinfo)
