### ISSUE TITLE
Afvalkalender voor AVRI aktief in de Betuwe

### ISSUE THREAD

**Issue by deltabert** [pippyn/Home-Assistant-Sensor-Afvalbeheer#139]
Hallo Pippyn,
Is het mogelijk om de afvalkalender van de AVRI toe te voegen aan jouw integratie/sensor?
Dit is de url van AVRI: https://www.avri.nl/inwoners/afval/afvalinzameling/afvalkalender-2020/
Een eventuele test postcode: 4105HB, elk nummer van 1 tot 60.

Heb al gekeken in jouw code maar ik ben zelf geen programmeur...
Hopelijk is dit mogelijk, bij voorbaad mijn dank.
Groet, Bert

**Comment by pippyn** [comment]
In English please :)

The postcode you give me doesn't work for me

**Comment by deltabert** [comment]
Pippyn, excuse me for using the Dutch language.

The postcode is really: 4105 HB in Culemborg.
Can you explain me what is wrong with the postcode?

**Comment by pippyn** [comment]
well the postcode is not working for me on their site:
![image](https://user-images.githubusercontent.com/7591990/92400968-0ea8fe80-f12d-11ea-8347-3b184160effa.png)

**Comment by pippyn** [comment]
This issue will be closed due to inactivity

**Comment by Flight777** [comment]
You can test with mine: 4033KA 15

Would appreciate an Avri integration 👍

**Comment by pippyn** [comment]
I'm hoping I'm not wrong, but AVRI uses DeAfvalApp right? Than you can just use that integration. Could you test for me?

**Comment by Flight777** [comment]
Nope unfortunately not, just tested but it does not support my postcode + nr

**Comment by pippyn** [comment]
Version v4.7.4 adds support for Avri
Sample config:
```
  - platform: afvalbeheer
    wastecollector: avri
    resources:
      - gft
      - papier
      - pmd
    postcode: 4033KA
    streetnumber: 15
```

**Comment by Flight777** [comment]
You are a legend, working well! 👍
