### ISSUE TITLE
Rova - Paper is not available. In the Rova app it is called 'Los Papier'

### ISSUE THREAD

**Issue by CasparTheBridge** [pippyn/Home-Assistant-Sensor-Afvalbeheer#140]
Nice to see the ROVA service is also added again.
When I check the upcomming collections in my phone app I see; Pmd, Gft-Afval, Restafval & Los papier. I've switch on the printwastetypes function in yaml and I see only PMD, GFT & restafval are available.

Is it also possible to add the paper for Rova?

**Comment by pippyn** [comment]
All fractions are enabled.

Did you check [this option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions)? If it's not listed there it will not work.

If it's listed but under a different name, let me know. Then I'll add the mapping for the correct name.

**Comment by CasparTheBridge** [comment]
Yes, I've used the option printwastetypes. This is shown:

Afvalwijzer
Available waste types: gft, pmd, restafval

When I check the website paper is there but it is called 'los papier':
https://inzamelkalender.rova.nl/nl/8141GC/8/

**Comment by pippyn** [comment]
Then their API doesn't provide the info on the paper fraction, I'm sad to say. You could contact ROVA to include this info in their API, because this sensor just reports the info available.
