### ISSUE TITLE
Suez states are not shown in HA via afvalkalender

### ISSUE THREAD

**Issue by djim1** [pippyn/Home-Assistant-Sensor-Afvalbeheer#141]
Hey @pippyn ,

at the moment my afvalbeheer sensor does not show the correct state/date of the sensors in Home Assistant. The Suez site shows the folowing:
![afbeelding](https://user-images.githubusercontent.com/24961163/92435281-37b7a680-f1a2-11ea-95f6-8ba0a0f156d3.png)

and in home assistant it's showing:
![afbeelding](https://user-images.githubusercontent.com/24961163/92435297-456d2c00-f1a2-11ea-9dbd-81d68e18da58.png)

my config worked fine, and I did not change anything, but for a day or 1-2 it does not show the states, from 6 sept at 12:35:15 it stoped:
![afbeelding](https://user-images.githubusercontent.com/24961163/92436229-849c7c80-f1a4-11ea-83b5-7fcded46519d.png)

the question is, what is going on/wrong here?

here is my config:
`````
sensor:
   - platform: afvalbeheer
     wastecollector: Suez
     resources:                       
       - restafval
       - textiel
       - gft
       - papier
       - pmd
     postcode: 6835AG                 
     streetnumber: 1 
     printwastetypes: 1
     upcomingsensor: 1                #(optional)
     dateformat: '%d %b'           #(optional)
     dateonly: 1                      #(optional)
     nameprefix: 1                    #(optional)
     builtinicons: 0                  #(optional)
     dutch: 1                         #(optional)

**Comment by pippyn** [comment]
This config is working fine for me. (except the fractions restafval and textiel, which should be removed from your config). Can you restart your HA and look at the logs for any errors?

**Comment by djim1** [comment]
after a restart of HA everything works again, strangely.
Thanks for taking a look and sorry for bothering you

**Comment by pippyn** [comment]
That's oke, I'm glad it's working again!
