### ISSUE TITLE
Add trash calendar Venlo

### ISSUE THREAD

**Issue by NielsPeulen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#142]
Hi Pippyn,

Is it possible to add the trash calendar of Venlo?
the address is in the url below. Also a .ics file could be generated there.
https://www.venlo.nl/trash-removal-calendar/5912SG/46 

Thanks in advance!

**Comment by joepstar** [comment]
Would be nice to have Venlo added!

**Comment by pippyn** [comment]
I'm sorry. I couldn't find an API for venlo. But you could use a scraper if you like:
[Afvalinfo](https://github.com/heyajohnny/afvalinfo)

**Comment by NielsPeulen** [comment]
Thanks! of course that is also working just fine.
