### ISSUE TITLE
Many reports off issues...

### ISSUE THREAD

**Issue by sanderlv** [pippyn/Home-Assistant-Sensor-Afvalbeheer#144]
Hi, just to make you aware... I also have these messages though it seems still working:

![image](https://user-images.githubusercontent.com/16528916/92871015-c4fa3580-f404-11ea-9956-121354f6d795.png)

See this:
https://community.home-assistant.io/t/i-made-no-changes-but-ha-is-unreachable/225900/2?u=sender

**Comment by pippyn** [comment]
You are not using this sensor. Your are using the one made by xirixiz

**Comment by sanderlv** [comment]
hm... only using this:

  - platform: afvalbeheer
    wastecollector: Avalex
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 1111xx
    streetnumber: 11
    upcomingsensor: 1
    dateformat: '%d-%m-%Y'
    dateonly: 0
    name: "xxxx"
    nameprefix: 0
    builtinicons: 1
    dutch: 1

**Comment by pippyn** [comment]
In the last line of the image you posted it says: [**xirixiz**/Home-Assistant-Sensor-Afvalwijzer](https://github.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer), so i would say you have that one also installed trough HACS

**Comment by sanderlv** [comment]
nope...
![image](https://user-images.githubusercontent.com/16528916/92877453-7734fb80-f40b-11ea-85c4-ce219642120c.png)

**Comment by pippyn** [comment]
Then I don't know what to say, I'm 100% sure it's not caused by this sensor though..
If the message doesn't disappear after a restart I would recommend you open a tread on the HA community forum.
