### ISSUE TITLE
Wrong info when exceptional no waste collection (recycleapp)

### ISSUE THREAD

**Issue by wimpie007** [pippyn/Home-Assistant-Sensor-Afvalbeheer#146]
Hi,
the 'exceptional' no waste collection is not used in the app, instead, it still shows that there is waste collected...
config:
  - platform: afvalbeheer
    wastecollector: ophaalkalender
    wastecollector: RecycleApp
    resources:
      - restafval
      - tuinafval
      - papier
      - pmd
      - grofafval
      - glas
    postcode: 9340
    streetname: xxxxx
    streetnumber: xxxx
    builtinicons: 1
    upcomingsensor: 1

recycleapp:
![image](https://user-images.githubusercontent.com/33153228/93565701-13bb4880-f98c-11ea-8454-1bb5ce1d00f3.png)

Sensors in HA:
![image](https://user-images.githubusercontent.com/33153228/93565781-34839e00-f98c-11ea-9aed-c95f0cb79334.png)

regards!

**Comment by pippyn** [comment]
can you give me an address to test with?

BTW: you should remove the line `wastecollector: ophaalkalender` from your config

**Comment by wimpie007** [comment]
sure! try:
Hoging 18, 9340 Oordegem, Belgium
(removing wastecollector: `wastecollector: ophaalkalender` didnt' help)

**Comment by pippyn** [comment]
Sorry for the late reaction.

I didn't find any mention of the exception in the API. As the sensor just passes along the data from the API, it had no way of knowing paper was not collected on the 18th. Maybe an one-time error in the API?
Please notify me when this happens again (and mention this issue number please)!

For now I'll close this issue.
