### ISSUE TITLE
New Option

### ISSUE THREAD

**Issue by williamgeurts** [pippyn/Home-Assistant-Sensor-Afvalbeheer#148]
Hi,
I am a happy user of the afvalbeheer plugin. Cranendonck uses a new sensor called: restafvalzakken. They use a different schedule than the restafval container. Can you add the restafvalzakken sensor as well?

William
![IMG_A5E3D94E84CD-1](https://user-images.githubusercontent.com/34502921/93873487-11315980-fcd2-11ea-93dd-099f61df1200.jpeg)

**Comment by pippyn** [comment]
No need. All fractions are supported by default.
If you need to know what value to put under `resources`, use the[ print fractions option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions)

**Comment by williamgeurts** [comment]
Dank voor het snelle antwoord.

-- 
Met vriendelijke groet,

William Geurts

**Comment by williamgeurts** [comment]
This new option (restafvalzakken)  is not available.

![Schermafbeelding 2020-09-22 om 13 55 30](https://user-images.githubusercontent.com/34502921/93879051-5ad27200-fcdb-11ea-9930-7d331be90284.png)

**Comment by pippyn** [comment]
I found the problem, will be fixed in the next release

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by williamgeurts** [comment]
Off course:

Bruine Akkers 91,
6026 DS Maarheeze

Thanks for helping.

Met vriendelijke groet,

William Geurts

**Comment by pippyn** [comment]
Fixed in v4.6.6

**Comment by williamgeurts** [comment]
Updated and tested, perfect, thanks.

-- 
Met vriendelijke groet,

William Geurts
