### ISSUE TITLE
FR: support for Area Reiniging

### ISSUE THREAD

**Issue by JanLankhorst** [pippyn/Home-Assistant-Sensor-Afvalbeheer#15]
Hi,

Would it be possible for you to include the Digitale Afvalwijzer from Area?
https://www.area-afval.nl/voor-bewoners/afvalkalender/digitale-afvalkalender

kind regards,
jan

**Comment by pippyn** [comment]
Sadly not the same API. This sensor will not work for Area.

**Comment by JanLankhorst** [comment]
Ah ok, thanks for the respons.

**Comment by Aham330** [comment]
Does this meanwhile work cause area reiniging is in the list?
