### ISSUE TITLE
change attribute please

### ISSUE THREAD

**Issue by 1000HrZ** [pippyn/Home-Assistant-Sensor-Afvalbeheer#154]
Hello,

ATTR_DAYS_UNTIL = 'days-until'  contains a - which gives a problem when you use it in lovelace.
Please change it to:

ATTR_DAYS_UNTIL = 'days_until'
same goes for ATTR_SORT_DATE

**Comment by pippyn** [comment]
What is the problem in LoveLace? is this a recent change?

**Comment by 1000HrZ** [comment]
i dont know havent used it before. but if you call a entity with a - in it you cannot call it somehow.

**Comment by pippyn** [comment]
I'm not sure what you mean... I use this in my HA (latest version) without any problem.

What card are you trying to use? what is the config you are using?

**Comment by 1000HrZ** [comment]
![afbeelding](https://user-images.githubusercontent.com/9479263/95907569-0717ed80-0d9c-11eb-91e7-bd824b12db58.png)

Invalid entity ID at position 0: states.sensor.omrin_sortibak.attributes.days-until

**Comment by pippyn** [comment]
Ahh so the problem isn't with LoveLace, but with Jinja.

Change states.sensor.omrin_sortibak.attributes.days-until to states.sensor.omrin_sortibak.attributes['days-until'] and it should work

**Comment by 1000HrZ** [comment]
i am ashamed ;-) sorry for wasting your time....

**Comment by pippyn** [comment]
No problem, I'm glad I could help
