### ISSUE TITLE
RD4.nl data is not fetched

### ISSUE THREAD

**Issue by Noto123** [pippyn/Home-Assistant-Sensor-Afvalbeheer#155]
On all my sensors this happens: Days-until: null

I'm running the latest versions of both HA and Afvalbeheer. Also tried to reinstall Afvalbeheer but without any luck.
Hope you can help to resolve this. Let me know if there are any logs or stuff you need for this.

**Comment by pippyn** [comment]
1. Does the afvalkalender on the website of your municipality work?

2. Do you have any errors in your log?

3. Could you please share your config, with an address in your neighbourhood?

**Comment by Noto123** [comment]
1. yes that seems to be working https://www.rd4info.nl/NSI/Burger/Aspx/afvalkalender_public.aspx?pc=6431xl&nr=3&t=
2. Only one from this morning, not sure if this is related

Logger: homeassistant
Source: custom_components/afvalbeheer/sensor.py:1005
First occurred: 7:49:39 AM (1 occurrences)
Last logged: 7:49:39 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 432, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 1005, in update
    response = r.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 


3. my config:
sensor:
  - platform: afvalbeheer
    wastecollector: RD4
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 6431XL
    streetnumber: 3
    upcomingsensor: 0
    dateformat: ''
    dateonly: 0
    name: ""
    nameprefix: 0
    builtinicons: 1
    dutch: 1

The date is empty on purpose, it only needs to displays today or tomorrow, I use it in combination with an Auto Entities card:

card:
  type: entities
filter:
  include:
    - attributes:
        Days-until: <= 1
sort:
  attribute: Days-until
  method: attribute
  numeric: true
type: 'custom:auto-entities'


Let me know if you need any more info.

**Comment by pippyn** [comment]
The non-official API this sensor uses seems down, or we got locked out. I'll do some more research and look for an alternative API.

**Comment by Noto123** [comment]
dank je 👍

**Comment by Oldacres** [comment]
I have seen the API go down at the beginning of the month as well: September 1st and Also on October first.
Also this link does not work anymore: https://rd4.syzygy.eu/1234AA/56. It gives a 500 error (server error)
Their app is still working... 

By the way pippyn: very nice add-on for HA. Thanks.

**Comment by Oldacres** [comment]
Today it suddenly worked again. Also the https://rd4.syzygy.eu/1234AA/56 works again.

**Comment by pippyn** [comment]
Nice! 

Well if  https://rd4.syzygy.eu/ isn't up, the sensor will not work as it uses this API.

**Comment by Noto123** [comment]
Donno what happened but the sensors are beeing updated again. Guess RD4 was
having issues with their API.

Thanks for checking Pippyn 😁
