### ISSUE TITLE
Omrin, Reuse of public key

### ISSUE THREAD

**Issue by Speedydown** [pippyn/Home-Assistant-Sensor-Afvalbeheer#156]
Hello,

I'm a dev that maintains the Omrin Api and unfortunately I had to disable your request to our Api

Could you make it so that if you already have requested a public Key, this key is reused so no new keys are created constantly? the way you are talking to our api is not as it was intended to be used by the app

And could you also identify yourself in the keyrequest with "platform = "HomeAssistant"?

Thanks in advance

**Comment by pippyn** [comment]
Hey, 

Thank you for contacting me. I'll do some changes to the code and let you know.

gr PIppyn

**Comment by pippyn** [comment]
I did have a look at the code, but the app doesn't request a new token if it's already set. [see line 866](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/b6d255f74862ebd265a11922bbb91a7d3a6b21ab/custom_components/afvalbeheer/sensor.py#L866)
I can set the platform in the keyrequest though.

**Comment by Speedydown** [comment]
We track devices for pushnotifications for the app and some addresses in our logs have over a 1000 devices (if not more), Assigning the platform should be enough as i can bundle them as 1 device in our backend

because of this, It's important that you always use the id returned by the getToken request and not your own randomly generated id

**Comment by pippyn** [comment]
So if I understand you correctly the ID returned by keyrequest is a lifetime token? it will never change? Then I will look for a way to persits the requested ID over reboots. (now the app generates a new uuid on every reboot, and requests a new public key from the API)
It should only generate a uuid for a new user and reuse that same uuid every time, correct?

**Comment by Speedydown** [comment]
yes correct, the key returned kan be the same or a new key
