### ISSUE TITLE
no card to add ...

### ISSUE THREAD

**Issue by Tyrian81** [pippyn/Home-Assistant-Sensor-Afvalbeheer#157]
Installed through HACS , and it shows up in hacs integrations 
but no way to add it as a card in lovelace ?¿

**Comment by pippyn** [comment]
This is an custom component, not a love lace card.
Install the component, configure your details in your config and restart HA.
Then after a few moments after boot the sensors will be created.
You can use these sensors in whatever lovelace card you want

**Comment by Tyrian81** [comment]
Ah thanks, thought it was more plug and play ...

So everything in hacs needs manual editing?

**Comment by pippyn** [comment]
I don't know. I'm not the dev for HACS.
Maybe this sensor will support gui config in the future
