### ISSUE TITLE
Vianen (vijfherenlanden)

### ISSUE THREAD

**Issue by compujunk** [pippyn/Home-Assistant-Sensor-Afvalbeheer#158]
ik vind de sensor er heel goed uit zien helaas zit mijn gemeente er niet bij.
is het mogelijk dat je ook Vianen (vijfherenlanden) er bij kan  zetten?
Ik weet niet of je dan ook gegevens moet hebben van me maar dat hoor ik dan wel

**Comment by pippyn** [comment]
Please in English.

Do you have an address (postcode + house number) for me to test with?

**Comment by pippyn** [comment]
Support for Waardlanden added in v4.7.0
