### ISSUE TITLE
Support for Leudal, RD Maasland

### ISSUE THREAD

**Issue by roygeraets** [pippyn/Home-Assistant-Sensor-Afvalbeheer#159]
Hi,

I'd like to see support for "Gemeente Leudal", in this place "Reinigings Dienst Maasland" is the collector.
Are you able to put in there schedule? 

Please let me know if i can do someting to help. 

Tnx in advance!

**Comment by pippyn** [comment]
Use mijnafvalwijzer as the `wastecollector`.
