### ISSUE TITLE
tomorrow & vandaag & PMD not populate anymore

### ISSUE THREAD

**Issue by tyfoon** [pippyn/Home-Assistant-Sensor-Afvalbeheer#16]
Hi, not sure if this is related to upgrading to 96.5 or related to API changed of the data suppliers but three sensors are not updating anymore:

sensor.gad_vandaag
sensor.gad_morgen
sensor.gad_pmd

Also see here:
https://community.home-assistant.io/t/custom-component-afvalbeheer-support-for-multiple-waste-collectors/83437/144

**Comment by tuimz** [comment]
I think this is the proper repository for that issue: https://github.com/pippyn/Home-Assistant-Sensor-Ophaalkalender

**Comment by tyfoon** [comment]
Why do you think so? This is about the Dutch version (afvalbeheer) and not the Belgium version

**Comment by pippyn** [comment]
Do you have postcode and street number for me to test with? You're using GAD?

**Comment by tyfoon** [comment]
Yes, it's GAD. Try 1215CZ, 8 and you should get: [https://inzamelkalender.gad.nl/adres/1215CZ:8](url)

**Comment by pippyn** [comment]
I just checked. You should use pbd under resources, not pmd. As the fraction is called: "Plastic, blik en drinkpakken" and not "Plastic, metaal en drinkpakken". Will check the today and tomorrow sensors in a couple of days.. (as they should be empty at this moment in time)

**Comment by tyfoon** [comment]
Hi Pippyn, this sensor always worked with PMD and the component does also not expose any other sensors (like PBD). Pls see screenshot below

<img width="951" alt="Screenshot 2019-08-22 22 36 49" src="https://user-images.githubusercontent.com/22179507/63547951-878ee580-c52d-11e9-979b-d9a24de986f4.png">

**Comment by pippyn** [comment]
You will have to add it in your config under resources. I didn't change anything that could have to do with this issue. Maybe GAD renamed their fraction? See the readme for more info.

**Comment by tyfoon** [comment]
added pbd as a sensor and indeed it shows data! Now also tomorrow and today have changed from 'unknown' to 'none' so I think that is also working again. I guess GAD must have changed it.

Thanks for your help
