### ISSUE TITLE
Integration not loaded

### ISSUE THREAD

**Issue by StijnVdd** [pippyn/Home-Assistant-Sensor-Afvalbeheer#160]
When starting the "Afvalbeheer" I receive following error in the logs
![image](https://user-images.githubusercontent.com/18342617/98106427-a3b04580-1e99-11eb-8add-1883645d4559.png)

HA 0.117.2 via docker.

Het sensor is not available.

**Comment by pippyn** [comment]
Can you try and change the contents of manifest.json (in the Afvalbeheer folder) to and reboot:
```
{
  "domain": "afvalbeheer",
  "name": "Afvalbeheer",
  "documentation": "https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer",
  "dependencies": [],
  "codeowners": ["@pippyn"],
  "requirements": [
    "rsa==4.0",
    "pycryptodome"
  ]
}
```

**Comment by StijnVdd** [comment]
Hi Pippyn,

That indeed solves the issue.

Thanks for your super fast response!

Kind regards!
