### ISSUE TITLE
No Icons Mijnafvalwijzer

### ISSUE THREAD

**Issue by roygeraets** [pippyn/Home-Assistant-Sensor-Afvalbeheer#161]
When using Mijnafvalwijzer as "Collector" i don't get the preconfigured Icon's. 
After changing the collector and address to PeelenMaas for example the icon's come trough.

The only clue i have is that i don't see the icon_data being added to the AfvalwijzerCollector update function, Line #357.
And i see that on for example Line #968 from the update function for OpzetCollector.

I think you are doing awsome work with this plugin, Love it!

**Comment by pippyn** [comment]
AfvalwijzerCollector API does not contain any icons to add. You can use your own if you like.
