### ISSUE TITLE
No icons for recycleapp and no soft plastics garbage collection

### ISSUE THREAD

**Issue by XalaTheShepard** [pippyn/Home-Assistant-Sensor-Afvalbeheer#165]
Dear Pippyn, 

I was able to successfully integrate the the integration "Home-Assistant-Sensor-Afvalbeheer" using the recycleapp. 
However, I am unable to make the icons visible. Furthermore, is it possible that one of the garbage collections "soft plastics" is unavailable? 

Please find below my code and a screenshot. 

  - platform: afvalbeheer
    wastecollector: recycleapp
    resources:
    - restafval
    - gft
    - plastic
    - papier
    - pmd
    postcode: XXXX
    streetnumber: X 
    streetname: XXXXXXXX
![HA garbage collection](https://user-images.githubusercontent.com/69390987/99423023-6a97bc80-2900-11eb-9b0f-9029b31cb9ef.PNG)

    upcomingsensor: 1
    dateformat: '%d-%m-%Y'
    dateonly: 0
    name: ""
    nameprefix: 1
    builtinicons: 0
    dutch: 0

Many thanks for the support. 

Kind regards

**Comment by StarTits** [comment]
builtinicons: 0 moet builtinicons: 1 worden. Ik heb wel gemerkt dat ze in  dark mode niet zo duidelijk zijn.

Dit is mijn config:   

upcomingsensor: 0
    dateformat: '%d %b'
    dateonly: 0
    dateobject: 1
    name: afvalbeheer
    nameprefix: 1
    builtinicons: 1
    disableicons: 0
    dutch: 1

**Comment by XalaTheShepard** [comment]
Dear StarTits, 

Many thanks for the support. They were indeed already available, but barely visisble due to the dark theme. 
I have implemented a background with more contrast and now they are a bit more visible. 

Kind regards

**Comment by pippyn** [comment]
Yes for now the icons are only available in dark. But you can also provide your own icons if you like with [HA customize entities](https://www.home-assistant.io/docs/configuration/customizing-devices/)
