### ISSUE TITLE
Add translation for Today and Tomorrow

### ISSUE THREAD

**Issue by wtrbuit** [pippyn/Home-Assistant-Sensor-Afvalbeheer#17]
Hi,

I have tried it myself but I can't seem to get it to work. Is it possible to add translations for the words "Today" and "Tomorrow" so I can show "Today, 26-08-2019" in my own language?

Or can you tell me how I can implement it myself and if it works you can add it if you want.

Thanks in advance!

**Comment by pippyn** [comment]
I'll implement this. Hopefully very soon.

**Comment by pippyn** [comment]
Dutch language added in 2.5.0
