### ISSUE TITLE
Restafval AREA reiniging is not working anymore

### ISSUE THREAD

**Issue by Jolly-Roger82** [pippyn/Home-Assistant-Sensor-Afvalbeheer#174]
Since updating HassOS to 5.8 and supervisor to 2020.12.7 my Restafval sensor from AREA reiniging is not working anymore, resulting in LOG errors:

Logger: homeassistant.helpers.event
Source: helpers/condition.py:232
First occurred: 9:48:17 (1 occurrences)
Last logged: 9:48:17

Error while processing state changed for sensor.restafval
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 257, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 433, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/triggers/numeric_state.py", line 130, in state_automation_listener
    matching = check_numeric_state(entity_id, from_s, to_s)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/triggers/numeric_state.py", line 99, in check_numeric_state
    return condition.async_numeric_state(
  File "/usr/src/homeassistant/homeassistant/helpers/condition.py", line 232, in async_numeric_state
    fvalue = float(value)
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by pippyn** [comment]
What is your config? including an address that works from your area.

**Comment by Jolly-Roger82** [comment]
####       Afvalkalender       ####
  - platform: afvalbeheer
    wastecollector: AreaReiniging
    resources:
    - restafval
    - gft
    - pmd
    - restwagen
    postcode: 7901AN
    streetnumber:  !secret
    upcomingsensor: 1
    dateformat: '%d %b'
    dateonly: 0
    dateobject: 1
    name: ''
    nameprefix: 0
    builtinicons: 1
    disableicons: 1
    dutch: 1

**Comment by Jolly-Roger82** [comment]
it worked flawlessly but for a couple of days my Restafval sensor does give me the error stated above

**Comment by pippyn** [comment]
Your streetnumber is non existent. Either add the name of the variable in secrets.yaml or hardcode the streetnumber

**Comment by pippyn** [comment]
example: if in secrets.yaml you have `streetnumber: 123`
then your config should include:
`streetnumber:  !secret streetnumber`

**Comment by Jolly-Roger82** [comment]
i copied my config directly from my sensors.yaml and edited the number into !secret because I do not use the secrets.yaml So be aware the real config contains a number instead of !SECRET

**Comment by pippyn** [comment]
oke. and is it a number only? not `123B` or `123-1` or something?
if you need to specify a suffix, use the suffix option

**Comment by Jolly-Roger82** [comment]
Yes, no additions what soever

**Comment by pippyn** [comment]
I checked the website https://www.area-afval.nl/voor-bewoners/afvalkalender/digitale-afvalkalender
And there is simply no data yet for 2021. And there are no collections for this fraction left in 2020. So there is no data to display

**Comment by Jolly-Roger82** [comment]
could it be that simple? so I guess, ill have to wait until there are new dates and see if the problem solves itself. 

Thanks for your support, ïll come back when needed/

**Comment by Jolly-Roger82** [comment]
Ok, so I was wondering. I can see upcoming dates in the Area Reiniging app on my android device. Even for newly added paper/cardboard and Christmas trees, I can see dates when they will be collected. 
I added the 2 new sensors (papier & Kerstbomen) but both show up as unknown. Is it just the issue of the transition into 2021 or is there something else wrong? Does the API go/show dates beyond 31 dec.?

**Comment by pippyn** [comment]
This sensor uses the same data as the https://www.area-afval.nl/voor-bewoners/afvalkalender/digitale-afvalkalender website. If the data is available there it should also be available in this sensor.

To find possible fractions for your address use the [Print all available waste fractions option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions)

**Comment by Jolly-Roger82** [comment]
so i see the dates in the app, and in the link you provided, even in 2021, but they don't show up in my HassOs

**Comment by pippyn** [comment]
You were right. I found the issue and it is fixed in v4.7.6

**Comment by Jolly-Roger82** [comment]
like, will see if it updates in HACS already

**Comment by pippyn** [comment]
You can force an HACS update by going to hacs>integrations and clicking on the name "Afvalbeheer"

**Comment by Jolly-Roger82** [comment]
YES, the print gives me all available waste types now. and I see them in my Lovelace. The issue is definetly resolved.

Good work! Thank you!
