### ISSUE TITLE
MijnAfvalwijzer not showing sensors any more

### ISSUE THREAD

**Issue by sneekerzzz** [pippyn/Home-Assistant-Sensor-Afvalbeheer#176]
Since 2 updates ago MijnAfvalwijzer doesn't show sensor information anymore. 

Papier, restafval are shown unavailable while the rest still provides dates

**Comment by pippyn** [comment]
Could you please provide some more info? What's your config? (Including an address in your neighbourhood) Does the website give you the correct info? Any errors?

**Comment by sneekerzzz** [comment]
Sure, MijnAfvalwijzer is working and let me see the pickup dates 

You can check yourself with 4707RE 1

`- platform: afvalbeheer
  wastecollector: MijnAfvalwijzer
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 4707RE
  streetnumber: 24
  upcomingsensor: 1
  dateformat: "%d %b"
  dateonly: 0
  name: ""
  nameprefix: 1
  builtinicons: 1
  dutch: 1
  printwastetypes: 1 `

**Comment by pippyn** [comment]
The config works fine, there are simply no dates yet for 2021 on the site for your area, so the sensor is also unable to show dates in 2021.
