### ISSUE TITLE
Sensor attribitues created with a - instead of _

### ISSUE THREAD

**Issue by sylviepipi** [pippyn/Home-Assistant-Sensor-Afvalbeheer#177]
most attributes in home assistance uses a _ in the attribute name to represent a space

the sensors created by Wastecollector uses a - symbol (Sort-date: &  Days-until: )
it gives some issue to use them in custom:button and from lovelace

any change you'll fix this (causing a breaking change)

**Comment by pippyn** [comment]
I agree this would be better, but I haven't found any issues yet with the current setup.
Can you explain your issue a bit more?

**Comment by sylviepipi** [comment]
- type: "custom:button-card"
                entity: sensor.recycleapp_gft   
                template: card_sensor_big
                name:  GFT in
                show_state: false
                show_label: true
                label: >
                      [[[                           
                          if (entity === undefined) return "?"  ;                
                          if (entity.attributes.days-until !=  undefined) return entity.attributes["Days-until"]  + "days" ;                
                          else  return "?"
                      ]]]

**Comment by pippyn** [comment]
Yes that is true.
In an upcomming major release, I'll include this breaking change.
