### ISSUE TITLE
 Integration 'Afvalbeheer' not found.

### ISSUE THREAD

**Issue by SonnyBBQ** [pippyn/Home-Assistant-Sensor-Afvalbeheer#179]
Hi,

I'm trying to get this sensor set-up, but keep getting the following error when checking the configuration:
Platform error sensor.Afvalbeheer - Integration 'Afvalbeheer' not found.

Have tried installing manually and via HACS.  No difference.

Thanks

**Comment by pippyn** [comment]
Steps:
- Remove your config of the sensor.
- Make sure the custom component is installed
- Restart HA
- Add sensor config
- Restart HA

**Comment by SonnyBBQ** [comment]
Thanks for the quick response, tried the above, but it doesn't work.

When you state, Make sure the custom component is installed.  I can see it in custom_components, I can also see it as an installed repository in HACS.
I cannot add this as a HA integration.

**Comment by pippyn** [comment]
Did you do a reboot? before adding the config?
What is your config?

**Comment by SonnyBBQ** [comment]
I did reboot before adding the config.
Below you will find my config. (address details changed).  As soon as I add this, I get the config error and can't reboot normally, only via supervisor.

`sensor:
  - platform: Afvalbeheer
    wastecollector: Limburg.NET
    resources:                  
     - restafval
     - gft
     - papier
     - pmd
    postcode: 1111
    cityname: mycity
    streetname: mystreet
    streetnumber: 1
    upcomingsensor: 0
    dateformat: '%d-%m-%Y'
    dateonly: 0
    dateobject: 0
    dayofweek: 1
    alwaysshowday: 1
    name: ''
    nameprefix: 1
    builtinicons: 0
    disableicons: 0
    dutch: 0 
`

**Comment by SonnyBBQ** [comment]
sorry, in the above post indentation seems screwed up, it looks like this:

![image](https://user-images.githubusercontent.com/76279232/103224743-98711780-4928-11eb-8e0d-29b09c08436e.png)

**Comment by pippyn** [comment]
change `Afvalbeheer` to lowercase.

**Comment by SonnyBBQ** [comment]
That did the trick :)  thanks
