### ISSUE TITLE
Add support for RD4

### ISSUE THREAD

**Issue by redahb** [pippyn/Home-Assistant-Sensor-Afvalbeheer#18]
The Garbage collector RD4 operates in the southern part of Limburg. I've found several official ways to retrieve the data:

**JSON:** _https://app.rd4.nl/nsi/api/v1/wastecalendars_. This is what the official RD4 'Milieu App' connects to, and returns categories where 0 is _restafval_, 1 is _GFT_, 2 is _Oud Papier_, 3 is _Snoeiafval_, 4 is _Kerstbomen_, 5 is _PMD_ and 6 is _BEST_. This requires an API_KEY and Basic Authorization header (see below).

**HTML:** _https://www.rd4info.nl/NSI/Burger/Aspx/afvalkalender_public_text.aspx?pc=POSTALCODE&nr=NUMBER&t=ADDITION_, e.g.: _https://www.rd4info.nl/NSI/Burger/Aspx/afvalkalender_public_text.aspx?pc=6411XZ&nr=41&t=_. This is not my address, just grabbed one from Funda.

**JSON:** _https://rd4.syzygy.eu/POSTALCODE/NUMBER/_, e.g.: _https://rd4.syzygy.eu/6411XZ/41_. I'm not entirely sure where this URL comes from and if it's future proof.

The downside with the first JSON approach is that it requires an API_KEY and Authorization. The API_KEY seems common but the (basic) Authorization seems to be different depending solely on the address. The same address on different devices yields the same Authorization key, so I'm guessing they assigned a different Authorization key to each collection route. API and Authorization can be sniffed when using the official app, but that's far from user friendly.

The downside with the HTML approach is it obviously needs extracting data from the HTML, but there's a nice LUA script that might 'inspire' you at _https://github.com/jvanderzande/mijnafvalwijzer/blob/master/script_time_huisvuil-zuidlimburg.lua_.

The downside with the second/last JSON approach is there's a category _Overig_ where they combined things like _Kerstbomen_, _BEST_ and _Snoeiafval_ so those are not specified.

Still, any update to the sensors would be nice!

**Comment by pippyn** [comment]
I'm not sure if this is the same api. I'm quite sure it's not. I'll have a look if you can give me a postcode and street number.
Second of all html is not an option. I'm not a fan of web scrapers as they are fragile and inefficient.

**Comment by rudolin** [comment]
Is there any progress on this? Did you receive a PC and number combination yet?

**Comment by redahb** [comment]
Sorry, was under the impression @pippyn would figure it out, because in the first post in this issue I had already provided PC and number.

**Comment by pippyn** [comment]
I missed the pc and number in your first post. 

But as I said on the HA forum; 
This is a different API and I'm only adding waste collectors with the same API. Sorry.

You could use my code in this repo as a start off point for making your own integration.

**Comment by Pr0gr4mm3r** [comment]
> Sorry, was under the impression @pippyn would figure it out, because in the first post in this issue I had already provided PC and number.

https://github.com/Pr0gr4mm3r/Home-Assistant-RD4

**Comment by Raarrrinator** [comment]
Hi all!

Al though this is an old post, I would like to comment..

I've noticed that resource https://rd4.syzygy.eu/POSTALCODE/NUMBER/ is down often lately, but https://www.rd4info.nl/NSI/Burger/Aspx/afvalkalender_public_text.aspx?pc=POSTALCODE&nr=NUMBER&t=ADDITION does work.

Does anyone have an integration that uses the HTML resource instead of the syzygy JSON?

**Comment by henkjohan** [comment]
It seems that after playing around with the URL a bit, you can get a JSON out of the official website.

https://data.rd4.nl/api/v1/waste-calendar/?year=2025&postal_code=6269%20AP&house_number=4

**Comment by pippyn** [comment]
RD4 is already supported
