### ISSUE TITLE
Replace text "pmd" with "Plastic" (MagicMirrorO

### ISSUE THREAD

**Issue by HaViGit** [pippyn/Home-Assistant-Sensor-Afvalbeheer#180]
First of all, thank you for sharing this beautiful plugin! I am using MagicMirror running a module that takes info from Home Assistant (see image). That works fine but I want to change the text of the afvalbeheer component so that "avri" is changed to "Avri" and "pmd" to "plastic". Is this possible and if so how should I do that?

![Avri](https://user-images.githubusercontent.com/46343309/103456689-e0ad8280-4cf8-11eb-813b-9c8181898f75.png)

**Comment by pippyn** [comment]
You can change that with the HA option [`Customizing Entities`](https://www.home-assistant.io/docs/configuration/customizing-devices/#manual-customization)

**Comment by HaViGit** [comment]
Hi Pippyn. Thanks for your fast reply. Just tried to edit customize.yaml:

`sensor.avri_pmd:
  friendly_name: Plastic
sensor.avri_gft:
  friendly_name: GFT
sensor.avri_papier:
  friendly_name: Papier
sensor.disk_free_home:`

But this is not accepted by HA which reports  _[friendly_name] is an invalid option for [sensor.afvalbeheer]._  Any suggestions?
