### ISSUE TITLE
Terneuzen

### ISSUE THREAD

**Issue by cjriemens** [pippyn/Home-Assistant-Sensor-Afvalbeheer#181]
Is this also possible with the municipality of Terneuzen?

**Comment by pippyn** [comment]
Do you have some more info?
What website does terneuzen use for the calendar?
Do you have an address for me to test with?

**Comment by pippyn** [comment]
@cjriemens Do you have this info for me?

**Comment by rodin-ia** [comment]
Hi, here is the link, this is the official link and yes there is a problem with the certificate :) 
https://terneuzen.deafvalapp.nl/calendar/kalender_start.jsp

**Comment by pippyn** [comment]
DeAfvalApp is already supported
