### ISSUE TITLE
date is not next but the one after

### ISSUE THREAD

**Issue by netsooj** [pippyn/Home-Assistant-Sensor-Afvalbeheer#182]
iám using afvalbeheer for the township PeelenMaas

#Afvalbeheer
- platform: afvalbeheer
  wastecollector: peelenmaas
  resources:
    - 'restafval'
    - 'gft'
    - 'papier'
    - 'pmd'
    - 'textiel'
  postcode: 5984NR
  streetnumber: 9
  upcomingsensor: 1
  dateformat: '%d-%b'
  dateonly: 1
  dateobject: 0
  printwastetypes: 1
  name: ''
  nameprefix: 1
  builtinicons: 0
  disableicons: 0
  dutch: 1
  alwaysshowday: 0

but the date showing isn't the next one, the showing date is the date after the next one?
Ican't find where to correct this. Please advice or help me
gr, Twan

**Comment by pippyn** [comment]
Yes the API is reporting the wrong dates for your address. As you can see here:
https://afvalkalender.peelenmaas.nl/rest/adressen/1894200000312031/afvalstromen

I'm not sure why...

**Comment by netsooj** [comment]
this is not alone for my adres, this is wrong for the hole township, i can pick the adres of my son and that's also wrong, could you please look at it, or is our township the only wrong one?

**Comment by pippyn** [comment]
is this still an issue with the latest version of the sensor?

**Comment by BVGorp** [comment]
Dates are getting more wonky.
Probably nothing you can do but are these APIs publicly available? Can we get support on them?
If these are not working just contact the municipality or directly to OpZet?
I checked Purmerend which is also OpZet, but that one is working fine. Its just Peel en Maas failing.

**Comment by Ascathon** [comment]
Same issue, same location. ;) Is there any contact information for this afvalkalender club to contact? The website shows it just fine, when you open the rest URL it's wrong. Also today when collection day is tomorrow.

**Comment by BVGorp** [comment]
Tried contacting OpZet via Facebook but didn’t get a response.

**Comment by BVGorp** [comment]
Seems the new year fixed this issue.
If others confirm then close it.

**Comment by Ascathon** [comment]
Doesn't sound hopeful when "the new year" has to fix it. But yes. It shows the collection date this friday.
Regardless if fixed or not, it's not a implementation issue of this addon, so still could be closed.

**Comment by netsooj** [comment]
thanks
