### ISSUE TITLE
RD4 doesn't show information

### ISSUE THREAD

**Issue by cschillings** [pippyn/Home-Assistant-Sensor-Afvalbeheer#183]
Forget this, read below. :)

**Comment by cschillings** [comment]
Already fixed it, you need to change the sensor.py coding
Old one was:
`for item_date in response[item]:
                    collection = WasteCollection.create(
                        date=datetime.strptime(item_date, "%d-%m-%Y"),
                        waste_type=waste_type
                    )
                    self.collections.add(collection)`

But the changed the order of date and now must be:

`for item_date in response[item]:
                    collection = WasteCollection.create(
                        date=datetime.strptime(item_date, "%Y-%m-%d"),
                        waste_type=waste_type
                    )
                    self.collections.add(collection)`

I changed it for myself for now and its working, can you changed it for a next update??

Thanks!

**Comment by dheuts90** [comment]
Thanks a lot!! Same problem, changed it in the file and hope its working after next sync

**Comment by cschillings** [comment]
> Thanks a lot!! Same problem, changed it in the file and hope its working after next sync

Restart your HA and it will be there directly!

**Comment by pippyn** [comment]
Thank you for your report.
Fixed in v4.7.8
