### ISSUE TITLE
Suez collection data not working

### ISSUE THREAD

**Issue by Dricey** [pippyn/Home-Assistant-Sensor-Afvalbeheer#184]
Sinds een aantal dagen geeft Suez geen ophaal datum meer terug, aan het begin van het jaar (paar dagen geleden) werkte het nog wel.

~~Als ik kijk naar de code en naar https://inzamelwijzer.suez.nl/rest/adressen/0317200000176648/afvalstromen
dan lijkt het alsof de mapping tussen menu_title is gewijzigd. Bijv. "menu_title": "Groente-, fruit en tuinafval"~~

**Comment by Dricey** [comment]
Uiteindelijk opgelost door een ander adres te selecteren. Het lijkt erop dat de verkeerde bagid wordt gekozen als er meerdere adressen zijn met hetzelfde huisnummer

**Comment by pippyn** [comment]
Did you specify a suffix in your config? Can you share your config with your address with me? Maybe [DM me on HA community forum](https://community.home-assistant.io/u/pippyn/) to keep your address private.

Could be that commit 9d720ec caused some new errors. I'll look into it

**Comment by Dricey** [comment]
I do not have a suffix configured. I will share the setup via DM.
I changed the code into `        elif (len(response) > 1):
            self.bag_id = response[0]['bagId']`
and now it seems to work

**Comment by pippyn** [comment]
Fixed in v4.7.9
