### ISSUE TITLE
Translate weekdays

### ISSUE THREAD

**Issue by HaViGit** [pippyn/Home-Assistant-Sensor-Afvalbeheer#187]
The module works fine, thank you for sharing! I wonder if I can translate the weekdays (see image) into Dutch. Although I have set "dutch: 1", the text remains in English. Can you help me with this?

![AVRI](https://user-images.githubusercontent.com/46343309/105162497-fb626280-5b12-11eb-8648-b8fa413f9db4.png)

**Comment by pippyn** [comment]
I assume you have set `dateformat` in your config? Remove that line and restart HA

**Comment by HaViGit** [comment]
Thanks for helping! Below the code in configuration.yaml and the image shows what I see in Home Assistant. As you can see I  use ``dateformat: '%a `%d-%m'`, do I need to remove this line?

``
sensor:
    - platform: afvalbeheer
      wastecollector: Avri
      resources:
        - gft
        - papier
        - pmd
      postcode: 1234XX
      streetnumber: 1
      upcomingsensor: 0
      dateformat: '%a %d-%m'
      dateonly: 1
      dutch: 1
``

![HA](https://user-images.githubusercontent.com/46343309/105168754-d8d44780-5b1a-11eb-8960-f0ecbcc4e7ad.png)

**Comment by pippyn** [comment]
Yes, or change it to the `a` to capital `A`:
`dateformat: '%A %d-%m' `

**Comment by HaViGit** [comment]
The line `dateformat: '%A %d-%m'` did the job. Thanks for helping!
