### ISSUE TITLE
New sensor first upcoming 

### ISSUE THREAD

**Issue by Dutchy-79** [pippyn/Home-Assistant-Sensor-Afvalbeheer#189]
Hi,

I see there is a today and tomorrow option, though I'd like to see a next item like the afvalwijzer app uses. 

Is this possible?

**Comment by pippyn** [comment]
Sure you can use a custom lovelace card like `auto-entities` and use the attribute Sort-date.

Look at [issue 33](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/33)

**Comment by Dutchy-79** [comment]
Just noticed this is closed, I'd like to suggest a 3th sensor that shows first upcoming item(s)

> Upcoming sensor
upcomingsensor: 1
If you activate this option you'll get 2 extra sensors (today and tomorrow) which are handy for automations. The today sensor will display the fractions collected today. The tomorrow sensor will display the fractions collected tomorrow. Default is 0.

Like afvalwijzer uses see this image https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/afvalwijzer-lovelace.png
