### ISSUE TITLE
Meerlanden seems to be broken

### ISSUE THREAD

**Issue by leonkielstra** [pippyn/Home-Assistant-Sensor-Afvalbeheer#193]
Hi, first of all: thanks for this plugin, it has been really useful.

Recently the plugin stopped working for me for Meerlanden. 

My config:
```
sensor:
  - platform: afvalbeheer
    wastecollector: Meerlanden
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: XXXXYY
    streetnumber: XX
    printwastetypes: 1
    alwaysshowday: 1
```

In my logs I get the following two errors:
```
Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1349
Integration: afvalbeheer (documentation)
First occurred: February 2, 2021, 7:38:42 PM (47 occurrences)
Last logged: 5:38:58 PM

No Waste data found!
```

```
Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1315
Integration: afvalbeheer (documentation)
First occurred: February 2, 2021, 7:38:41 PM (47 occurrences)
Last logged: 5:38:58 PM

Address not found!
```

So I looked into the code whenever this error occurs and tried to reproduce the API request you do [here](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/master/custom_components/afvalbeheer/sensor.py#L1304).

```py
data = {
  "postCode": "XXXXYY",
  "houseNumber": "XX",
  "companyCode": "800bf8d7-6dd1-4490-ba9d-b419d6dc8a45"
}
response = requests.post("https://wasteapi.ximmio.com/api/FetchAdress", data=data).json()
```

The reponse I get is:
 ```js
{
  "userMessage": {
    "type": null,
    "messageCode": 0,
    "description": null
  },
  "ExtraOption": {
    "$type": "System.Dynamic.ExpandoObject, System.Core"
  },
  "dataList": null,
  "intDataList": null,
  "data": null,
  "status": false,
  "messageCode": 164,
  "pdfResponse": null,
  "token": null,
  "ID": null,
  "invalidParameters": null,
  "total": 0,
  "messageToString": null
}
```

I know for sure that the given address is correct. It also used to work before. I can't seem to find the API docs for Ximmio anywhere, so I can't figure out what `messageCode: 164` is, nor whether their API implementation has been changed. 

Can you help me find out whether this is a problem I have or whether the plugin is broken? I am also happy to try and fix it if it's broken, yet I would probably need to know where to find the API docs for that.

**Comment by pippyn** [comment]
This error means that the API can't find your address. Could you try maybe a different house number? or a street close to you?

Does the website work for your address?
https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/

**Comment by leonkielstra** [comment]
I have tried different house numbers and also addresses on streets nearby, it all results in the same response. All those addresses work perfectly fine on https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/.

**Comment by pippyn** [comment]
Could you [DM](https://community.home-assistant.io/u/Pippyn/) me your address on HA forum? Then I'll have a look.

**Comment by leonkielstra** [comment]
I am sorry, but I just created an account there and can't send you a message.
> Sorry, you cannot send a personal message to that user.

I can't really find why not.

**Comment by jk38448** [comment]
Hi all,

I runned into exact same problem. When i enter my details in the URL it seems to work fine.
https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/

But the plugin give me the same errors as leonkielstra mentioned:
No Waste data found!
Address not found!

**Comment by leonkielstra** [comment]
At https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/ it calls `https://wasteprod2api.ximmio.com`. Replacing the API with this url, gives me a correct response.

```py
response = requests.post("https://wasteprod2api.ximmio.com/api/FetchAdress", data=data).json()
```

Reponse:
```py
{
  "userMessage": {
    "type": null,
    "messageCode": 0,
    "description": null
  },
  "ExtraOption": {
    "$type": "System.Dynamic.ExpandoObject, System.Core"
  },
  "dataList": [
    {
      "UniqueId": "XXXXXXXXXX",
      "Street": "YYYYYYYY",
      "HouseNumber": "XX",
      "HouseLetter": "",
      "HouseNumberIndication": "",
      "HouseNumberAddition": "",
      "ZipCode": "XXXXYY",
      "City": "YYYYYY",
      "Community": "YYYYYY",
      "AddressType": "",
      "Floor": null,
      "AddressUniqueId": 0,
      "AddressUnique": null
    }
  ],
  "intDataList": null,
  "data": null,
  "status": true,
  "messageCode": 107,
  "pdfResponse": null,
  "token": null,
  "ID": null,
  "invalidParameters": null,
  "total": 0,
  "messageToString": null
}
```
