### ISSUE TITLE
Feature request: dayofweek without date behind them

### ISSUE THREAD

**Issue by LethalRabbit** [pippyn/Home-Assistant-Sensor-Afvalbeheer#196]
First of all, thank you so much for all the time and effort that you have put into this! Truely amazing!

I have a feature request. In my setup I am using the 'dayofweek: 1' option. I have also adjusted the date format to only show day and month. I would love to be able to not show the date, when the day of week is being shown. I would like this because if it shows both the day of the week and the date, the data gets cut off because it is too long.

So in the image below, I would like the first entry to only say 'Dinsdag' and not 'Dinsdag, 09...'. Would this be possible?

![Screenshot](https://user-images.githubusercontent.com/8746812/107132810-792fb780-68e2-11eb-9d04-2da131e15ece.png)

**Comment by pippyn** [comment]
There is currently no option to accomplish this. I'll think about including this feature in a next release if there is enough demand from the user base. You could also create an LoveLace card to display the data in every way you want ofcourse.

**Comment by FredericMa** [comment]
I'm also interested in this feature! :-)

**Comment by pippyn** [comment]
Added in v4.7.27

**Comment by pippyn** [comment]
To use this new option follow these steps:
- Update the custom component
- Reboot HA
- Edit your config and add the [new option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#day-of-week-only) 'dayofweekonly: 1'
- Reboot HA again

**Comment by FredericMa** [comment]
Thanks for adding! The only issue I see is that the name of the day is not translated to Dutch.
Adding `self.date_format = '%A'` here fixes it: https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/a6b9dc7599132ba395aec90ac8435494319f926d/custom_components/afvalbeheer/sensor.py#L1388-L1389

**Comment by pippyn** [comment]
Did you set the [translation option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#translation) to on?
i.e. `dutch: 1`

**Comment by pippyn** [comment]
Should be fixed in v4.7.28

**Comment by FredericMa** [comment]
Works like a charm! Thanks a lot.

**Comment by LethalRabbit** [comment]
Works like a charm, thank you so much for this update!!
