### ISSUE TITLE
Wrong upcoming day indication

### ISSUE THREAD

**Issue by blackneonreaper** [pippyn/Home-Assistant-Sensor-Afvalbeheer#197]
Hello super dope component!
i setup my light to change color depending on what is getting collected te next day and when I switch on the light in the morning it also show's the color.
Really cool thanks again.

Just one small issue.
I setup the wastecollection to limburg.net.
The dates are correct and the day aswel but the "Tomorrow / Today" indication is a day behind.
Today is never show

![Screenshot 2021-02-12 at 08 51 43](https://user-images.githubusercontent.com/3583565/107742573-9368fb80-6d0f-11eb-8e91-6ffd18c35c3d.png)

The upcoming sensors are correct (_vandaag and _morgen)

Is that field calculated? Or is it also received from the waste provider?
I checked my date settings in home assistant config and they are correct 

- platform: afvalbeheer
    wastecollector: Limburg.NET
    resources:
    - restafval
    - papier
    - pmd
    - glas
    postcode: xxx
    streetnumber: xx
    streetname: 'xx'
    cityname: 'xx'
    name: 'Garbage Collection'
    upcomingsensor: 1

Is my setup wrong? Or is this a bug?

**Comment by pippyn** [comment]
Strange..
Do you have an address for me to test with?

**Comment by blackneonreaper** [comment]
I solved it the timezone setting was off with one hour. Set it correct restart and works now. Thnx
