### ISSUE TITLE
Omrin Restafval

### ISSUE THREAD

**Issue by bernd37** [pippyn/Home-Assistant-Sensor-Afvalbeheer#198]
Intergratie geinstalleerd via HACS, werkt uitstekend behalve "Restafval" deze staat op "onbekend" zonder dat ik begrijp waarom dit het geval is, nabij mijn weten staat alles goed ingesteld. Iemand suggesties hoe dit op te lossen is?

![Schermafbeelding 2021-02-12 om 14 53 13](https://user-images.githubusercontent.com/58814279/107776577-0b501980-6d42-11eb-9453-ed68e7822610.png)

sensor:
  - platform: afvalbeheer
    wastecollector: Omrin
    resources:           
      - restafval
      - gft
      - papier
    postcode: 1234AB
    streetnumber: 1
    upcomingsensor: 1
    dateformat: '%d-%m-%Y'
    dateonly: 0           
    name: ''
    nameprefix: 1
    builtinicons: 0
    dutch: 1

**Comment by jdevnl** [comment]
Voor mezelf moest ik ook even zoeken, maar voor omrin moet je de sortibak gebruiken:
    resources:                       
      - sortibak

**Comment by bernd37** [comment]
Bedankt voor je snelle reactie, dit bied inderdaad de oplossing. Sensor restafval -> sortibak werkt nu naar behoren. Groeten!
