### ISSUE TITLE
[README] Wastecollector configuration

### ISSUE THREAD

**Issue by Devqon** [pippyn/Home-Assistant-Sensor-Afvalbeheer#2]
Your README states that you can choose a `wastecollector` of a given list. They only work in lowercase though, so either the README should be updated, or the code should do a `toLowerCase`.

**Comment by pippyn** [comment]
I can not repoduce your error. A wastecollector as title, lower case or all upper case works just fine for me, because the code does convert to lower case. What collector are you using?

**Comment by Devqon** [comment]
It seems you are right. The first time it didn't work, and when I changed it to lowercase it did work, so I assumed that was the issue.
Now I have changed it back to 'Circulus-Berkel', which just works. So you can close this one :)
