### ISSUE TITLE
HVC PMD sensor is not working

### ISSUE THREAD

**Issue by matthijssn** [pippyn/Home-Assistant-Sensor-Afvalbeheer#20]
Hi,

The PMD sensor of HVC doesnt seem to work. When I request the "Afvalstromen" by hand from the HVC api, I get the following title:  "title": "Plastic, blik & drinkpakken",
Somehow this is not recognized by the PMD sensor.  My guess it's related tothe RENAME_TITLES array. Hope you can have a look at it. Thanks!

Regards, Matthijs

**Comment by pippyn** [comment]
Use PBD, not PMD. As it's "plastic, BLIK & drinkpakken"

**Comment by matthijssn** [comment]
Thanks, I'll try it immediatly

**Comment by matthijssn** [comment]
Works like a charm! thanks
