### ISSUE TITLE
 sensor.recycleapp_restafval

### ISSUE THREAD

**Issue by JefNewTech** [pippyn/Home-Assistant-Sensor-Afvalbeheer#203]
My 
sensor.recycleapp_restafval gives me an unknown information 

While on recycleapp.be I have the collection of household waste

**Comment by pippyn** [comment]
Some more information would be helpful:

- Did it work before?
- Any errors in your log?
- What's your config?
- Please provide an address in your neighborhood

**Comment by JefNewTech** [comment]
Additional information would be useful:

Did it work before?
No since the installation it does not work. 

Errors in your log?
No errors are indicated in the log

What is your configuration?

platform: afvalbeheer
wastecollector: RecycleApp            
resources:                       
  - restafval
  - paper
  - pmd
postcode: 7540  
streetname: Rue du Mont d'Or              
streetnumber: 1             
cityname: Kain
upcomingsensor: 1
dateformat: '%d-%m-%Y'.           
dateonly: 0                     
dateobject: 0                   
# name: ''                        
nameprefix: 1                    
builtinicons: 0                  
disableicons: 0
printwastetypes: 1

Data for pmc and papers are well uploaded

**Comment by pippyn** [comment]
Fixed in v4.7.15

**Comment by JefNewTech** [comment]
Thank you it works 😊
