### ISSUE TITLE
Afvalbeheer causes configuration error since last update

### ISSUE THREAD

**Issue by YvoTuk** [pippyn/Home-Assistant-Sensor-Afvalbeheer#207]
Since I installed the latest update of Afvalbeheer, something seems to cause this error:

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:420 
Integration: Home Assistant Supervisor (documentation, issues) 
First occurred: 21:56:15 (1 occurrences) 
Last logged: 21:56:15

Component error: Sensor - Integration 'Sensor' not found.

I've tried editing the data in configuration in configuration.yaml, but as soon as I enable the module the above error is thrown.

This is my config:
Sensor:
    - platform: afvalbeheer
      wastecollector: Cyclus
      resources:
        - restafval
        - gft
        - papier
        - pmd
      postcode: <mypostcode in 1234AB format)
      streetnumber: 3

**Comment by milanmeu** [comment]
Sensor should start with a lowercase letter.

Change `Sensor:` to `sensor:`.

---
Put your configuration between triple [backticks](https://superuser.com/a/254077), we cannot see your indentation. For more information see the [GitHub docs](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code).
