### ISSUE TITLE
afval kalender Vlaardingen

### ISSUE THREAD

**Issue by csfolmer** [pippyn/Home-Assistant-Sensor-Afvalbeheer#210]
Hi kan en wil je gemeente Vlaardingen toevoegen?
test postcode 3132 SP, huisnummer 53a.

Alvast bedankt

**Comment by jobvk** [comment]
De afhaalcollector van Vlaardingen is Irado

@pippyn heeft in een eerdere issue al aangegeven dat het niet ging #26 
En ook in #138, hier in adviseert hij wel dat je een scraper sensor kan gebruiken voor [afvalinfo.nl](https://www.afvalinfo.nl/)

**Comment by csfolmer** [comment]
> De afhaalcollector van Vlaardingen is Irado
> 
> @pippyn heeft in een eerdere issue al aangegeven dat het niet ging #26
> En ook in #138, hier in adviseert hij wel dat je een scraper sensor kan gebruiken voor [afvalinfo.nl](https://www.afvalinfo.nl/)

aha thanks!
dan moet ik me ff gaan verdiepen in een scraper sensor.
haha eerst eens kijken wat het is ;-)

maar komt goed
