### ISSUE TITLE
Error loading /config/configuration.yam

### ISSUE THREAD

**Issue by MrMickeyMike** [pippyn/Home-Assistant-Sensor-Afvalbeheer#213]
Hi,

I used the same config, but I get the following errors:

Error loading /config/configuration.yaml: while parsing a block mapping
in "/config/configuration.yaml", line 2, column 7
expected <block end>, but found '<scalar>'
in "/config/configuration.yaml", line 13, column 40

This is my config:

sensor:
      platform: afvalbeheer
      wastecollector: RecycleApp            (required)
      resources:                       (at least 1 required)
        - restafval
        - gft
        - papier
        - pmd
      postcode: 8550                 (required)
      streetnumber: 5                  (required)
      streetname: Paardenbloemstraat    (required)
      upcomingsensor: 1                (optional)
      dateformat: '%d-%m-%Y'           (optional)
      dateonly: 0                      (optional)
      dateobject: 0                    (optional)
      name: 'Afval Buiten'                         (optional)
      nameprefix: 1                    (optional)
      builtinicons: 0                  (optional)
      disableicons: 0                  (optional)
      dutch: 1                         (optional)

**Comment by pippyn** [comment]
Remove all the `(optional)` and `(required)`, and the `(at least 1 required)` from your config and reboot HA

**Comment by MrMickeyMike** [comment]
thx pippyn, but still not working.

Next error is: Platform error sensor.Afvalbeheer - Integration 'Afvalbeheer' not found.

If i run the sensor.py file  I get:

Traceback (most recent call last):
  File "/tmp/Home-Assistant-Sensor-Afvalbeheer-master/custom_components/afvalbeheer/sensor.py", line 48, in <module>
    import voluptuous as vol
ModuleNotFoundError: No module named 'voluptuous'

**Comment by pippyn** [comment]
It looks like you capitalized the word `afvalbeheer` in your config (after `platform:`)?

What do you `mean run the file`? You can't just run an addon, it needs to be called by HA.
