### ISSUE TITLE
No sensor update (new install)

### ISSUE THREAD

**Issue by otterlo** [pippyn/Home-Assistant-Sensor-Afvalbeheer#214]
Hello

i created the config section and my config points to Circlus-Berkel, restarted HA and i see the sensors all available in entities for Paper, GFT etc.

However, i dont seem to get an update. Days until is showing a “-”" see also the image

how do i know the API is working, or how can i test the connectivty?

thanks in advance for your support

i included the sensor status in the dashboard and the configuration section. for privacy i just marked my postal code with xx but this is not in the real live version

i checked the logfiles but i dont see any error related to this plugin

![config](https://user-images.githubusercontent.com/80626061/112620623-1316d980-8e29-11eb-961d-c5ce1306b234.JPG)

![gft](https://user-images.githubusercontent.com/80626061/112620431-d0550180-8e28-11eb-97a7-bdfe229b028c.JPG)

**Comment by pippyn** [comment]
Did you change your postcode for privacy or is this your actual config?

**Comment by pippyn** [comment]
Well there would definitely be errors in the logs, or your HA is broken. Did you look at these logs in `/config/logs`?

**Comment by otterlo** [comment]
> Did you change your postcode for privacy or is this your actual config?

this was just for privacy reasons, actual config is showing my actual postcode

**Comment by otterlo** [comment]
> Well there would definitely be errors in the logs, or your HA is broken. Did you look at these logs in `/config/logs`?

in /config/logs i did a search and i am getting as shown in the picture
![afval_error1](https://user-images.githubusercontent.com/80626061/112623702-f67ca080-8e2c-11eb-818d-239a6088e7d2.JPG)

**Comment by pippyn** [comment]
The origin of this error is most likely that your address wasn't found.
Does your address work on the Circlus-Berkel website?

**Comment by otterlo** [comment]
it does work on the website, i attached screendump. (again removed postal code partly for privacy)

it also works in the afvalvrij app

![tempsnip](https://user-images.githubusercontent.com/80626061/112624376-dd282400-8e2d-11eb-9ea9-ce75841babce.jpg)

**Comment by pippyn** [comment]
can you DM me your address details on the HA forum? I'll need to do some more tests.

**Comment by pippyn** [comment]
I've seen you can't DM me. Can you test some other addresses in your neighborhood?

**Comment by otterlo** [comment]
i believe i may have a pointer to this problem. when i go to circulus site and enter my postalcode and number, it comes back to me with another selection. possible issue is that my house number is 70 and my neighbour is 70A. so it is asking me for a confirmation whether i want to see 70 or 70a.

when i look at this URL behind the selections on the page i see also difference in the URL's. may this be causing the error? i will also try a number somewhere else in this street

**Comment by otterlo** [comment]
that must have been the issue, i tried another number in this street and it works!
sorry that i did not try that myself.

would there been any resolution to fixing the 70 vs 70A problem? i guess not so important as i can use the other house numbers as well

many thanks for your very kind support!

**Comment by pippyn** [comment]
Ahh yes, my integration of CirculusBerkel does not yet support a suffix. I'll look into adding it in the near future
