### ISSUE TITLE
Restafval, GFT, Glas onbekend

### ISSUE THREAD

**Issue by wolfhond** [pippyn/Home-Assistant-Sensor-Afvalbeheer#215]
Sinds een week of zo (is me dan pas opgevallen) Kan ik restafval, gft en glas niet meer zien.
Staat op Onbekend. Enkel Afvalophaling Papier en PMD werken nog.

Heb de laatste update gedaan maar blijft gelijk. 
Enig idee. Het is over de RecycleApp 
Dit is eventueel mijn code die dus vroeger wel volledig ging, maar gewoon ter verduidelijking.

    - platform: afvalbeheer
      wastecollector: RecycleApp
      resources:
        - restafval
        - gft
        - papier
        - pmd
        - glas
      postcode: 9300
      streetnumber: 58
      streetname: achterweg
       #If you activate this option you'll get 2 extra sensors (today and tomorrow) which are handy for automations.
       #The today sensor will display the fractions collected today.
       #The tomorrow sensor will display the fractions collected tomorrow.
      upcomingsensor: 1
      dateformat: '%d %b %Y'
      alwaysshowday: 1
      dateonly: 0
      dateobject: 0
      name: 'Afvalophaling'
      nameprefix: 0
      builtinicons: 1
      disableicons: 0
      dutch: 1

**Comment by pippyn** [comment]
This address is not giving me any data on https://recycleapp.be/

**Comment by pippyn** [comment]
I have had a look. There is no `restafval` collection for your address according to https://recycleapp.be/calendar

The API is only reporting back `Papier` and `PMD`.

**Comment by wolfhond** [comment]
Ik zal even hun contacteren. 
Waar vind ik de API ?

**Comment by pippyn** [comment]
[line 1075](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/71ecdeec6c71cfade224b4c16e700da0b8c21225/custom_components/afvalbeheer/sensor.py#L1075) in sensor.py

**Comment by quinten94b** [comment]
I have the same problem with the recycle app. 
Since a couple of days my recycle app is showing everything as unknown. Where it previously worked fine. The recycle app itself still gives me the dates for pmd, restafval, groen, ....

I will try to do a rollback tomorrow and test some older versions.

**Comment by wolfhond** [comment]
It works again

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

________________________________

**Comment by pippyn** [comment]
@quinten94b It's not the sensor, but the API that's acting strange. Installing older versions will not work.

@wolfhond nice!
