### ISSUE TITLE
Syntax warning in current code

### ISSUE THREAD

**Issue by mleenaerts** [pippyn/Home-Assistant-Sensor-Afvalbeheer#216]
When starting the latest version (v4.7.18) I receive the following error.

/config/custom_components/afvalbeheer/sensor.py:436: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.update_interval is not 0:

**Comment by pippyn** [comment]
Thank you for reporting this issue!
It's not an error though, but a warning. I'll fix this is the next release.
