### ISSUE TITLE
Waste Collector (Cure) defined a waste type twice

### ISSUE THREAD

**Issue by wtrbuit** [pippyn/Home-Assistant-Sensor-Afvalbeheer#22]
So today it is the day Papier en karton is picked up. According to the sensor it is not due till the 7th of November. In the app of Cure the 7th of November is marked as pickup date for Papier en karton but also today as expected.

By inspecting the API I found that both dates are available but with a different ID in the result.

**Today**
`
{
id: 131,
parent_id: 0,
title: "Papier en karton",
slug: "",
tags: null,
page_title: "Papier en karton",
content: "<p><strong>Wat</strong></p> <p>Papier en karton m....",
menu_title: "Papier en karton",
icon: "doos-karton-papier",
icon_data: "data:image/svg+xml;base64,PD94bWwgdm...",
ophaaldatum: "2019-10-10"
}
`

**The 7th of November**
`{
id: 124,
parent_id: 0,
title: "Papier en karton",
slug: "",
tags: null,
page_title: "Papier en karton",
content: "<p><strong>Wat</strong><br /> .....",
menu_title: "Papier en karton",
icon: "doos-karton-papier",
icon_data: "data:image/svg+xml;base64,PD94bWw.....",
ophaaldatum: "2019-11-07"
}`

It seems like a bug on the waste collectors end but maybe it is an idea to do an extra check if there are two of the same kind and just give back the one with the earliest pickup date.

**Comment by pippyn** [comment]
That is strange indeed. I'll have a look

**Comment by pippyn** [comment]
Is this still an issue with the current version?

**Comment by wtrbuit** [comment]
Just updated in a while. I will keep an eye on it. I did have the issue again but with paper this time but with an older version of your integration.

**Comment by pippyn** [comment]
hey Wouter,

I fixed this issue in v2.5.10, please update
