### ISSUE TITLE
Afvalbeheer lijkt niet te werken bij mij

### ISSUE THREAD

**Issue by frankverheyen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#221]
Hallo Pippyn. Bedankt voor de prachtige sensor, maar ik heb problemen met de implementatie.

Mijn sensor configuratie:
`sensor:
  - platform: afvalbeheer
    wastecollector: recycleApp
    resources:
     - restafval
     - gft
     - papier
     - pmd
    streetname: Steynstraat
    postcode: 2660             
    streetnumber: 168
    upcomingsensor: 1
      `
Mijn lokatie is dus Steynstraat 168 te 2660 Antwerpen (Hoboken)

Ik krijg de volgende foutmelding in de log:

_**Logger: homeassistant.helpers.entity
Source: custom_components/afvalbeheer/sensor.py:282
First occurred: 2:54:55 AM (12456 occurrences)
Last logged: 8:12:28 PM

Update for sensor.recycleapp_gft fails
Update for sensor.recycleapp_papier fails
Update for sensor.recycleapp_pmd fails
Update for sensor.recycleapp_vandaag fails
Update for sensor.recycleapp_morgen fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 292, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 490, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 669, in update
    collection = self.data.collections.get_first_upcoming_by_type(self.waste_type)
  File "/config/custom_components/afvalbeheer/sensor.py", line 282, in collections
    return self.collector.collections
AttributeError: 'NoneType' object has no attribute 'collections'**_

Ik weet niet of deze fout ook hoort bij de sensor

Logger: homeassistant.components.command_line.sensor
Source: components/command_line/sensor.py:122
Integration: command_line (documentation, issues)
First occurred: 3:06:42 AM (10 occurrences)
Last logged: 8:06:44 PM

Empty reply found when expecting JSON data

Ik heb de installatie reeds 2x uitgevoerd, zonder resultaat. Ik heb ook geprobeerd met een ander adres, maar ik krijg dezelfde fout (kapelstraat nr 4, ook in Hoboken)
Als ik naar de recycleapp website ga, met dezelfde gegevens, krijg ik mijn gegevens volledig door.

Ik draai HA op een RP4 met de allerlaatste updates.

Please advise :-)

Bedankt, Frank

**Comment by frankverheyen** [comment]
Edit:
Nu krijg ik ook de volgende fout:
Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:270
Integration: afvalbeheer (documentation)
First occurred: 8:29:40 PM (1 occurrences)
Last logged: 8:29:40 PM

Waste collector not found!

**Comment by kurtdb** [comment]
Dat komt omdat de afvalbeheer-token die gebruikt wordt (lijn 1077 in de sensor.py) outdated is. Elke maand wordt die token aan gepast om misbruik te voorkomen.

**Comment by pippyn** [comment]
I'll look into it asap and change the token if needed.

**Comment by frankverheyen** [comment]
For the moment I can not complain after a reinstallation. It could be that next month it is a different situation if the token indeed changes. I will come back with more feedback.
Thanks for the help and for offering the sensor to us pippyn!

**Comment by pippyn** [comment]
I'm glad it's working now.
In the year the RecycleApp integration has been active, the token has changed twice. So it is definitely not every month. I'll keep an eye on it. I'll close this issue for now.

**Comment by frankverheyen** [comment]
Thanks for your reply. I will keep you informed.
Again many thanks. Good luck and good health.

Kind greetings

Frank.
