### ISSUE TITLE
Feature request - Toevoegen van DHM als afvalsoort voor Gemeente Tilburg

### ISSUE THREAD

**Issue by Janderatelslang** [pippyn/Home-Assistant-Sensor-Afvalbeheer#222]
Beste @pippyn,

Zou het misschien mogelijk zijn om de afvalsoort DHM toe te voegen? Gemeente Tilburg gebruikt dit voor de Droge Herbruikbare Materialen oftewel de duobak plastic en papier. Ik kan nu alleen maar een automatisering voor de normale duobak van rest en gft en het zou fijn zijn voor mij en mijn gezien als ik die ook kan maken voor dhm. 

Mocht dit lukken dan staat daar natuurlijk een pilsje tegenover.

**Comment by pippyn** [comment]
English please.

All fractions are supported by default.
use the option [`Print all available waste fractions `](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions) to get a list of all fractions

**Comment by Janderatelslang** [comment]
Oh please excuse me. 

Thank you for the information. That is a really handy feature I hadn't noticed before. As it turns out I was looking for papier-pmd. Thanks a again and thanks as well as for this great intergration  and I will keep my promise.
