### ISSUE TITLE
Are there detailed install instructions for a beginner?

### ISSUE THREAD

**Issue by notflip** [pippyn/Home-Assistant-Sensor-Afvalbeheer#226]
For example where do I add the example config,
where do I find the custom component once the folder is copied?

I would be grateful! Thanks

**Comment by pippyn** [comment]
I would recommend using HACS to install the sensor. And the config should go under the `sensor:` section in the configuration.yaml file

**Comment by notflip** [comment]
Thank you, I did not know about the existence of HACS.
