### ISSUE TITLE
Belgium Limburg.net Adaption

### ISSUE THREAD

**Issue by Milithor** [pippyn/Home-Assistant-Sensor-Afvalbeheer#228]
Hi!

I noticed my 'Groenafval' marker being broken for a while.
Seems limburg.net changed it to 'Tuin- en Snoeiafval'.
After changing `'Groenafval': WASTE_TYPE_BULKYGARDENWASTE` to `'Tuin- En Snoeiafval': WASTE_TYPE_BULKYGARDENWASTE `resolved the problem.

I do not know if this is for the whole province.

```
WASTE_TYPE_MAPPING = {
        # 'tak-snoeiafval': WASTE_TYPE_BRANCHES,
        # 'gemengde plastics': WASTE_TYPE_PLASTIC,
        'Grofvuil': WASTE_TYPE_BULKLITTER,
        # 'Groenafval': WASTE_TYPE_BULKYGARDENWASTE,
        'Tuin- En Snoeiafval': WASTE_TYPE_BULKYGARDENWASTE,
        # 'grof huisvuil afroep': WASTE_TYPE_BULKLITTER,
        # 'tak-snoeiafval': WASTE_TYPE_BULKYGARDENWASTE,
        'Glas': WASTE_TYPE_GLASS,
        'GFT': WASTE_TYPE_GREEN,
        # 'batterij': WASTE_TYPE_KCA,
        'Huisvuil': WASTE_TYPE_GREY,
        'PMD': WASTE_TYPE_PACKAGES,
        'Papier': WASTE_TYPE_PAPER,
        'Textiel': WASTE_TYPE_TEXTILE,
        # 'kerstboom': WASTE_TYPE_TREE,
    }
```

**Comment by pippyn** [comment]
You can just add `Tuin- en Snoeiafval` as a fraction and it should work again

**Comment by pippyn** [comment]
There is no need to change the mapping

**Comment by Milithor** [comment]
As a fraction?

**Comment by pippyn** [comment]
under `resources` in your config

**Comment by Milithor** [comment]
It does not work though

**Comment by pippyn** [comment]
can you share your config please?

**Comment by pippyn** [comment]
Never mind I added the mapping in v4.7.21

**Comment by Milithor** [comment]
Cheers! Thanks for the quick work!
