### ISSUE TITLE
Sort by date ?

### ISSUE THREAD

**Issue by marcello9** [pippyn/Home-Assistant-Sensor-Afvalbeheer#23]
Great integration, very useful !

Is there anyway to sort by date ?

**Comment by denman1991** [comment]
I have the same question. works perfectly but would be complete when you can sort by date in your card.

**Comment by pippyn** [comment]
I don't understand the question. Where would you like to sort?
In lovelace?

**Comment by marcello9** [comment]
Yes, in my case I would like to have the upcoming "event" :) first and then the rest...
I am sure it would be possible, either to sort the output in lovelace or (maybe even beter..) to have a parameter in the config.

**Comment by pippyn** [comment]
I certainly think it's possible. But for that, you'll have to find a lovelace card. This is only the sensor that loads the data into HA.
