### ISSUE TITLE
Invalid timestamp in Mobile app

### ISSUE THREAD

**Issue by binoke** [pippyn/Home-Assistant-Sensor-Afvalbeheer#230]
I noticed that a “invalid timestamp” shows in Lovelace when using the mobile app.  
![EB18127F-58CD-40BB-84ED-12E5B4924613](https://user-images.githubusercontent.com/30434109/117858538-4523b400-b28e-11eb-9caf-ba73f97e79a2.jpeg)
I do not see the problem in my browser.

**Comment by pippyn** [comment]
What is the config you're using?

**Comment by pippyn** [comment]
yes i think so. Please try it without `datobject: 1`

**Comment by binoke** [comment]
That did make a difference but it shows the date inconsistent now.  
![F0658EE9-875D-4559-AD67-C181D7CE0C47](https://user-images.githubusercontent.com/30434109/117939894-cae44580-b308-11eb-8e5f-07faf53140e8.jpeg)
But at least it shows a date now.  Just testing the automations now

**Comment by pippyn** [comment]
No thats correct according to your config.
`dateformat: '%Y-%m-%d'`

**Comment by binoke** [comment]
what I mean is that the view Restafval shows "Maandag, 2021-05-17" but the others don't have the day name in front, just date "2021-05-20" for example.

**Comment by pippyn** [comment]
if you want to disable the dayname in the status, use this option:
`dateonly: 1`

**Comment by pippyn** [comment]
Is this issue resolved now?

**Comment by binoke** [comment]
yes, it seems to be fixe.
p.s. I was on vacation, sorry for the late reply.
