### ISSUE TITLE
RWM addition

### ISSUE THREAD

**Issue by schwickster** [pippyn/Home-Assistant-Sensor-Afvalbeheer#233]
Hey,

Is it possible to add RWM to this integration?
Data can be collected by using https://www.rwm.nl/api.php using form data
zipcode:
houseNumber:
addition: (optional where you can add your district)

For example https://www.rwm.nl/inwoners/afvalwijzer?zipcode=6191%20GR&houseNumber=38

Thanks

**Comment by pippyn** [comment]
The website doesn't seem to work with this address?

But RWM should be supported by mijnafvalwijzer, which is already integrated in this sensor.
Could you check if this works for you?
