### ISSUE TITLE
Can you Add gemeente Uden

### ISSUE THREAD

**Issue by de-krabburger** [pippyn/Home-Assistant-Sensor-Afvalbeheer#236]
I tried several of the waste collectors but none give info about gemeente Uden. I went directly to their website to check.

Website https://www.afvalinfo.nl/ will redirect to the page of waste collection page of Uden https://www.uden.nl/inwoners/afval/ophaaldagen-afval/

The integration Afvalinfo works but it doesn't work with the nice icons.

**Comment by jobvk** [comment]
The Problem with Afvalinfo.nl is it doesn't have an API. The same problem is with Issue #58.
The custom component "Afvalinfo" by heyajohnny. Uses a scraper for collecting data from the website.
Using a scraper is not an option for this  custom component.

A solution is using the custom component "Afvalinfo" by heyajohnny.
And adding an entity picture to an entity is using the home assistant customizations page.

1. Just upload a picture to home assistant.
2. Then select the entity.
3. Put by Entity picture the path of the picture.

Example Customizations:
![image](https://user-images.githubusercontent.com/32730202/121180454-2b5f9780-c861-11eb-9516-b8ab3efa7e63.png)

After adding all custom pictures, it should look like this:
![image](https://user-images.githubusercontent.com/32730202/121181036-dc663200-c861-11eb-94d6-d30fcff80d94.png)

I hope to help you further if there is anything else let me know.

**Comment by de-krabburger** [comment]
Oké thanks for the advice got it working.
