### ISSUE TITLE
Miwa support?

### ISSUE THREAD

**Issue by johanvh83** [pippyn/Home-Assistant-Sensor-Afvalbeheer#237]
Hi Pippyn,

Would it be possible to integrate support for MIWA afvalbeheer? This is a Belgian company in East-Flanders.
https://www.miwa.be/nl/inzameling-aan-huis/afvalkalender/

The website provides downloading of a .csv file based on village and street. 
I don't know if you have possibility to make full support for all villages and streets. If not, I live in Sint-Gillis-Waas, Zandstraat.
If it's not possible at all, does your integration supports import of a calendar/sheduling? Alternatively a manually change of an existing sheduling could help.
Thanks in advance,

Johan.

**Comment by pippyn** [comment]
MIWA should be supported by Ophaalkalender.be. Could you try and config the sensor with the waste collector Ophaalkalender?
