### ISSUE TITLE
Feature request: MijnAfvalWijzer additional information

### ISSUE THREAD

**Issue by yfands** [pippyn/Home-Assistant-Sensor-Afvalbeheer#238]
Hai,

With 'Mijnafvalwijzer' there is a possibility to get additional information, if you go to the website's 'mijn afval' menu.
There you have to provide a code (which you can request (also on this page)) and after entering the code you can see how much 
Kilograms there was in your Bin and the price.

Would be a nice feature to have.. ;)

Regards, Frank

**Comment by pippyn** [comment]
I would like to add this this feature, but as I don't have this option with my Waste Collector, it will be hard for me to code.
