### ISSUE TITLE
Error in config

### ISSUE THREAD

**Issue by MichNLGithub** [pippyn/Home-Assistant-Sensor-Afvalbeheer#240]
When i paste the code:

  sensor:
    - platform: afvalbeheer
      wastecollector: Blink            (required)
      resources:                       (at least 1 required)
        - restafval
        - gft
        - papier
        - pmd
      postcode: 1111AA                 (required)
      streetnumber: 1                  (required)
      upcomingsensor: 0                (optional)
      dateformat: '%d-%m-%Y'           (optional)
      dateonly: 0                      (optional)
      dateobject: 0                    (optional)
      name: ''                         (optional)
      nameprefix: 1                    (optional)
      builtinicons: 0                  (optional)
      disableicons: 0                  (optional)
      dutch: 0                         (optional)

in receive the error:

can not read a block mapping entry; a multiline key may not be an implicit key at line 57, column 15:
          dateonly: 1                      (optional)
                  ^

**Comment by pippyn** [comment]
You will have to leave out all the comments (all the text within brackets and the brackets also). Like "(optional)" and "(required)"

**Comment by MichNLGithub** [comment]
Hi Pippyn,

Thanks for your support maybe change the code to the # symbol to prevent form error:

sensor:
    - platform: afvalbeheer
      wastecollector: Mijnafvalwijzer     # (required)
      resources:                                    # (at least 1 required)
        - restafval
        - gft
        - papier
        - pmd
      postcode: 1234AB                       # (required)
      streetnumber: 1                           # (required)
      upcomingsensor: 1                     # (optional)
      dateformat: '%d %b'                   # (optional)
      dateonly: 0                              # (optional)
      dayofweek: 1                         # (optional)
      alwaysshowday: 1                # (optional)
      dateobject: 0                         # (optional)
      name: ''                                # (optional)
      nameprefix: 0                       # (optional)
      builtinicons: 1                      # (optional)
      disableicons: 0                    # (optional)
      dutch: 1                              # (optional)

**Comment by pippyn** [comment]
Yes indeed. I'll change this soon. I'm sorry for the inconvenience!
