### ISSUE TITLE
Can’t hide nameprefix

### ISSUE THREAD

**Issue by Robbi-Ho** [pippyn/Home-Assistant-Sensor-Afvalbeheer#241]
Hi,

I’ve been playing with your great add-on but when I can’t get rid of the prefix ‘hvc’. When I use ‘nameprefix: 0’ I don’t get any dates.
With this configuration it work, but with the prefix ‘hvc’ before the wasteresource:

  - platform: afvalbeheer
    wastecollector: HVC              #(required)
    resources:                       #(at least 1 required)
      - restafval
      - gft
      - pmd
    postcode: XXXXXX                 #(required)
    streetnumber: XXX                #(required)
    upcomingsensor: 1                #(optional)
    dateformat: '%d-%m-%Y'           #(optional)
    dateonly: 0                      #(optional)
    dateobject: 0                    #(optional)
    name: ''                         #(optional)
    nameprefix: 1                    #(optional)
    builtinicons: 1                  #(optional)
    disableicons: 0                  #(optional)
    dutch: 1                         #(optional)

**Comment by pippyn** [comment]
If you change the nameprefix to 0 new sensors are created (new entity ids). The old ones are not going to work anymore

**Comment by Robbi-Ho** [comment]
With the new sensors it works again. Thanks for your quick reply.
