### ISSUE TITLE
Errors and no data since update to HA OS 6.2

### ISSUE THREAD

**Issue by coolnr** [pippyn/Home-Assistant-Sensor-Afvalbeheer#243]
After update to Home Assistant OS6.2 the integration is not working anymore. No dates are displayed. Nothing has changed in my configuration.yaml. Before update everything worked fine.

In logbook i get following errors:

No Waste data found!
9:00:24 – (FOUT) afvalbeheer (aangepaste integratie)
Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1260
Integration: afvalbeheer (documentation)
First occurred: 9:00:24 (1 occurrences)
Last logged: 9:00:24

No Waste data found!

Address not found!
9:00:22 – (FOUT) afvalbeheer (aangepaste integratie)
Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1226
Integration: afvalbeheer (documentation)
First occurred: 9:00:22 (1 occurrences)
Last logged: 9:00:22

Address not found!

Here are the details from my configuration.yaml
(postcode and streetnumber deleted)

- platform: afvalbeheer
    wastecollector: Meppel
    resources:
      - gft
      - papier
      - pmd
    postcode: ----
    streetnumber: -
    upcomingsensor: 0
    dateformat: '%d-%m-%Y'
    dateonly: 0
    name: ""
    nameprefix: 1
    builtinicons: 1
    dutch: 1

**Comment by coolnr** [comment]
After several restarts and new updates it started working again.

**Comment by pippyn** [comment]
Most likely the API was down.
