### ISSUE TITLE
Translation to Dutch fails for September

### ISSUE THREAD

**Issue by Doomic** [pippyn/Home-Assistant-Sensor-Afvalbeheer#248]
First of all, thanks for this plugin. I use it daily; because google assistant alerts me in the evening before and in the morning if i need to place my bin.
but this month; if i ask when paper will be collected; google will response that this will ben xxth sepember. First i thought that this was some issue of google speach. but i found out that it is indeed listed without a "t" in homeassistant.

my configuration is dateformat: "%d %B"
I guess this line I marked below is the issue. Because of the loop it will have twice a replace on %B.. "September" will be replaced with "September" (same in dutch).. But later it will match the part "Sept" and that will be replaced with the dutch abbreviation "Sep".

Not sure what the solution may be for this issue.. what i can think of that you first replace the "%" in the dateformat with something like "$%". Then the output will become "$x $September".. then you replace "$"+EN_da, with NL_day. And if you sort the items from large to small (like they currently are); it will replace $September with September; so it will not later replace Sept to Sep because it is missing the $ sign. Of course you should only do this if translation to dutch is requested by configuration. Or you should do a replace of $ with empty string at the end to remove this signs.
Not the most beautiful solution, because the dateformat can now never use the $-sign. So maybe you can think of a better solution.

https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/b3310a8475a975b6ff7f21667653b9634db0b6a6/custom_components/afvalbeheer/sensor.py#L1379

**Comment by pippyn** [comment]
Thank you for reporting this bug.
This is fixed in v4.7.25

**Comment by Doomic** [comment]
Thank you, I saw your fix.. if I am correct; this will still break if you use both %b and %B in the format string. That been said; I don't think anyone will ever use this combination. Therefore I will close this issue.
