### ISSUE TITLE
no AVRI data

### ISSUE THREAD

**Issue by ssewalt** [pippyn/Home-Assistant-Sensor-Afvalbeheer#249]
first, thnx for the plugin.
But i didnt get data at this moment. Log errors are:

No waste data found: 
Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1276
Integration: afvalbeheer (documentation)
First occurred: 19 september 2021 20:58:46 (26 occurrences)
Last logged: 9:06:35

No Waste data found!

And
adress not found
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1242
Integration: afvalbeheer
First occurred: 19 september 2021 20:58:46 (26 occurrences)
Last logged: 9:06:35

Address not found!

how to fix?

**Comment by pippyn** [comment]
Did it work before?

As the error states your address can't be found by the API. Does your address work on the website of the wastecollector?

If so; what is your config?

**Comment by ssewalt** [comment]
the web address is working. but i saw there message....
WEGENS EEN STORING IS DE AFVALKALENDER OP DIT MOMENT ALLEEN TE RAADPLEGEN VIA DE AVRI-APP. WE WERKEN AAN EEN OPLOSSING.
That is the reason...
