### ISSUE TITLE
Avri (or use AfvalApp as source?)

### ISSUE THREAD

**Issue by Flight777** [pippyn/Home-Assistant-Sensor-Afvalbeheer#25]
Hi,

Thanks for this nice component! I'm not a developer myself sadly so not able to fully assess or do this, but is there any possibility the Avri that takes care of all the Gemeenten in Regio Rivierenland can be added?

www.avri.nl

They do also feature on the website: http://www.deafvalapp.nl (which I used for Homey previously), so that might be another source to get information from?

Again not sure if anything is possible, but if you could have a look that would be much appreciated!

PC: 4033KA, Numb: 15

Thanks.

**Comment by pippyn** [comment]
I did have a look, but it's a different API. So this component will not support Avri I'm sorry to say.
