### ISSUE TITLE
Gemeente Westland is now using XIMMIO

### ISSUE THREAD

**Issue by AlbertDijksma** [pippyn/Home-Assistant-Sensor-Afvalbeheer#250]
Gemeente Westland is now using XIMMIO

Please add:

 'westland': '6fc75608-126a-4a50-9241-a002ce8c8a6c',

 'westland': "https://wasteprod2api.ximmio.com"

To your code.

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by pippyn** [comment]
Added in v4.7.26

**Comment by AlbertDijksma** [comment]
Not working
Jou also need to update the XIMMIO_URLS
With 'westland': "https://wasteprod2api.ximmio.com"

**Comment by pippyn** [comment]
you are right, fixed in v4.7.27

**Comment by AlbertDijksma** [comment]
![Screenshot_20210927-101822_Home Assistant](https://user-images.githubusercontent.com/25565832/134880932-ec74bda7-f9ae-4cf9-9d6c-041cefc13351.jpg)
![Screenshot_20210927-101901_Home Assistant](https://user-images.githubusercontent.com/25565832/134880986-d60c621e-eb4a-45f2-b91a-d3b24d9abb1a.jpg)
![Screenshot_20210927-094414_Samsung Internet](https://user-images.githubusercontent.com/25565832/134881019-39561541-6118-42b8-97d4-194e429cc5ea.jpg)

**Comment by pippyn** [comment]
I'm glad it's working now!
