### ISSUE TITLE
Translation issue?

### ISSUE THREAD

**Issue by AlbertDijksma** [pippyn/Home-Assistant-Sensor-Afvalbeheer#251]
![Screenshot_20210926-095037_Home Assistant](https://user-images.githubusercontent.com/25565832/134800894-8fb27938-7949-4b9e-8804-763cb26f7ba7.jpg)

**Comment by pippyn** [comment]
What's the problem? you renamed your PMD sensor to PDB?
What's your config? what is wrong?

**Comment by AlbertDijksma** [comment]
Sorry, forgot that I had translated the labels myself. this case can be closed.
