### ISSUE TITLE
Avalex switched to XIMMIO

### ISSUE THREAD

**Issue by StevenBoelhouwer** [pippyn/Home-Assistant-Sensor-Afvalbeheer#253]
avalex: "f7a74ad1-fdbf-4a43-9f91-44644f4d4222"
avalex: https://wasteprod2api.ximmio.com/

**Comment by pippyn** [comment]
Thank you!
Changed in v4.7.30

**Comment by StevenBoelhouwer** [comment]
Confirmed working here
