### ISSUE TITLE
Ilva Belgian government Waste collector

### ISSUE THREAD

**Issue by koenvo27** [pippyn/Home-Assistant-Sensor-Afvalbeheer#263]
Hey there,

It would be really sweet if it would work for me aswell. But "Ilva" Isn't supported yet I see.

https://afvalkalender.ilva.be/nl/

You can use Eichemstraat 140 9406 Outer (Ninove)

Thanks alot in advance!

Kind regards

Koen

**Comment by PorkyFrost** [comment]
Hello Koen

It would surprise me if it would be different, but here Ilva uses the "Recycle"-app.
I pasted the configuration I use in combination with Recycle, edited to your location.

# Afvalbeheer
sensor:
    - platform: afvalbeheer
      wastecollector: RecycleApp
      resources:
        - restafval
        - gft
        - papier
        - pmd
        - glas
      postcode: 9406
      streetnumber: 140
      streetname: Eichemstraat
      upcomingsensor: 1
      dateformat: '%A, %d %B'
      dateonly: 0
      dateobject: 0
      name: 'Afvalophaling'
      nameprefix: 1
      builtinicons: 1
      disableicons: 0
      dutch: 1

Kind regards!

**Comment by pippyn** [comment]
@koenvo27 can this issue be closed?

**Comment by jeroenvdd** [comment]
Tested this as an ilva user and works perfectly!

**Comment by DeWaHa** [comment]
Hello,
Does the Recycle! App used in 9300 Aalst work?
I tried RecycleApp, but HA says can´t find it.

**Comment by DeWaHa** [comment]
Sorry,
Tried again, and now it seems to be working.
Many thanks
