### ISSUE TITLE
429 Too Many Request "RD4"

### ISSUE THREAD

**Issue by Toetje585** [pippyn/Home-Assistant-Sensor-Afvalbeheer#265]
For some strange reason my "ip4/6" adres is getting blocked from RD4, I never used this module before and created a simple:

```
sensor:
    - platform: afvalbeheer
      wastecollector: RD4
      resources:
        - restafval
      postcode: 6222xx
      streetnumber: xx
      updateinterval: 24
```
      
However it seems that RD4 has an aggressive rate limit setup and also block request depending on GEO, If i use a proxy like "hideproxy.me" I can use "https://rd4.syzygy.eu/6222xx/xx" just fine, however with my Ziggo IPV4 address I get rate limited... It seems they might be rate-limiting Ziggo's ipv4 range? 
 
 I waited 48 hours with the above settings.
 
```
 Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 461, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 1067, in update
    response = r.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I know this is not a issue itself of Afvalbeheer but perhaps more people came across this issue, also an alternative website I found is https://www.rd4info.nl/NSI/Burger/Aspx/afvalkalender_general.aspx and this one works just fine.
 
 Any idea's?

**Comment by pippyn** [comment]
You can set the update interval with [this option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#update-interval). That should fix the issue

**Comment by Toetje585** [comment]
I already have this ootion

> You can set the update interval with [this option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#update-interval). That should fix the issue

I already used that option from the beginning, see above config.

**Comment by pippyn** [comment]
Ahh sorry, I missed that.

I'm aware of the rd4info site, but that API is not accessible sadly.

**Comment by Toetje585** [comment]
Alright well then I will need to skip this for now, but awesome work!

Thanks allot.
