### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ImanRibbens** [pippyn/Home-Assistant-Sensor-Afvalbeheer#268]
Error:

Deze entiteit ("sensor.zrd_required_at_least_1_required_restafval_gft") heeft geen unieke ID, daarom kunnen de instellingen ervan niet worden beheerd vanuit de gebruikersinterface.

yaml:

- platform: afvalbeheer
    wastecollector: zrd              (required)
    resources:                       (at least 1 required)
      - restafval
      - gft
    postcode: 4485AT                 (required)
    streetnumber: 6                  (required)

**Comment by pippyn** [comment]
This is resolved in the latest update.
