### ISSUE TITLE
meerdere locaties uitlezen

### ISSUE THREAD

**Issue by ssewalt** [pippyn/Home-Assistant-Sensor-Afvalbeheer#272]
Bij een oudere versie kon ik 2 postcodes uitlezen. Nu krijg ik daar een error op. Is het mogelijk om nog steeds het afval ophaal schema van 2 postcodes uit te lezen?

**Comment by pippyn** [comment]
Sure, just add another config for the sensor

**Comment by ssewalt** [comment]
thnx.

my config:
sensor afvalbeheer:
  - platform: afvalbeheer
    wastecollector: Avri
    resources:
        - gft
        - papier
        - pmd
    postcode: 4007WD
    streetnumber: 15
    dutch: 1

sensor afvalbeheer_corso:
  - platform: afvalbeheer
    wastecollector: Avri
    resources:
        - gft
        - papier
    postcode: 4006EV
    streetnumber: 37
    dutch: 1
    
    
error message:
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:592
Integration: Sensor (documentation, issues)
First occurred: 12:54:09 (2 occurrences)
Last logged: 12:54:09

Platform afvalbeheer does not generate unique IDs. ID avri gft already exists - ignoring sensor.avri_gft
Platform afvalbeheer does not generate unique IDs. ID avri papier already exists - ignoring sensor.avri_papier


Wat doe ik niet helemaal goed???

**Comment by pippyn** [comment]
Please keep all conversions in English.

You should give the different sensors a name. You can achieve this with the [name option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#name)

**Comment by ssewalt** [comment]
thanx this will help
