### ISSUE TITLE
Request to add INCOVO waste collector

### ISSUE THREAD

**Issue by McDr** [pippyn/Home-Assistant-Sensor-Afvalbeheer#274]
Hello, I was excited to find this integration for home assistant. Unfortunately my waste collector is not on the list (INCOVO). I was wondering if you would be able to add them to the supported list?

**Comment by pippyn** [comment]
They use a totally different API as it seems.
Do you have an address for me to test with?
I'll see what I can do

**Comment by McDr** [comment]
I realized a couple days ago that their schedule is available through RecycleApp. 

If you want an address to try directly: Keizer Karellaan, 1982 Elewijt

**Comment by pippyn** [comment]
RecycleApp is already supported
