### ISSUE TITLE
Request: Avri bedrijven

### ISSUE THREAD

**Issue by davey400** [pippyn/Home-Assistant-Sensor-Afvalbeheer#275]
Hi Pippyn,
great work; finally een afvalwijzer that works with Avri.

But there is alway a bigger mountain, as we say in Denglish. ;)

Avri has two different pages, one for the regular kliko's, and one for the bigger ones.
These bigger ones can be found under the 'bedrijven' tab, because they are not being hauled on the regular rounds.

These can be found at:
https://www.avri.nl/bedrijven/afval/bedrijvenafvalkalender-2021/

Would it be possible to add these dates as well?

Best regards,
Dave

**Comment by pippyn** [comment]
Sure will try!
Do you have an address for me to test with?

**Comment by davey400** [comment]
4012DD
1

**Comment by pippyn** [comment]
A `Klantnummer` is also required for this API. Could you send me a DM on the HA forum with your actual address and customer number?

**Comment by davey400** [comment]
Hm, that’s new.
I will look for it and send a DM.

Might take a few hours, sorry fort hat.

Dave

**Comment by davey400** [comment]
As far as I can find there seems to be no way to send a private messege in Github?

**Comment by pippyn** [comment]
you can do that on the HA forum

**Comment by pippyn** [comment]
Support for commercial address is added in v4.9.0.
Update the sensor > restart HA > add [`customerid`](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#customer-id-for-ximmio-commercial-address) to your config with your customer ID as a value > restart HA

**Comment by davey400** [comment]
Hi Pippyn, thank you for this update.
Unfortunately this introduced a new issue.
When I add the customerid it is only showing the 'commercial' collection.
The logging says:  _Available waste types: papier_
The other collections (which were papier, pmd, gft) are no longer visible. 

In my case we have 2 paper collections; one for the regular paper Kliko, and one (on the same address) for a big paper container, which is considered as a commercial address.

You might want to distinguish the results for the commercial type from the private type?
(And if the answer is: this is to much work, than this is fine as well, ofcourse!)

**Comment by pippyn** [comment]
just add 2 sensors to your config

**Comment by pippyn** [comment]
Remember to give each sensor a useful name with the `name` option

**Comment by davey400** [comment]
That's smart. Will try.

**Comment by davey400** [comment]
That works. Thanks!
