### ISSUE TITLE
RD4 Wastecollector broken

### ISSUE THREAD

**Issue by razor109** [pippyn/Home-Assistant-Sensor-Afvalbeheer#276]
I've installed the Afvalbeheer app but the status returns Unknown. Probably the website scraper for RD4 is broken?

This is in the home assistant log:

2021-12-24 15:19:40 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/afvalbeheer/sensor.py", line 464, in async_update
await self.collector.update()
File "/config/custom_components/afvalbeheer/sensor.py", line 1070, in update
response = r.json()
File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mdresen** [comment]
Here also wastetype results in unknown. Other wastecollector gives results as expected, so I assume configuration setup and entities are correct.

Also the manual API call via rd4.syzygy.eu gives results, so postalcode and number are correct too.

**Comment by pippyn** [comment]
Did it work before? 
Is it always unknown? 
Does your address work on the RD4 website?

**Comment by razor109** [comment]
I installed the addon and noticed it didn't work. Yes it is always unknown

On the RD4 website my address works and gives a kalender return.

This is the return for the api url:

https://rd4.syzygy.eu/POSTALCODE/NUMBER 

I use the format for postalcode: 0000AA 

`{"PMD":["2022-01-06","2022-01-20","2022-02-03","2022-02-17","2022-03-03","2022-03-17","2022-03-31","2022-04-14","2022-04-28","2022-05-12","2022-05-28","2022-06-09","2022-06-23","2022-07-07","2022-07-21","2022-08-04","2022-08-18","2022-09-01","2022-09-15","2022-09-29","2022-10-13","2022-10-27","2022-11-10","2022-11-24","2022-12-08","2022-12-22"],"REST":["2022-01-07","2022-01-21","2022-02-04","2022-02-18","2022-03-04","2022-03-18","2022-04-01","2022-04-15","2022-04-29","2022-05-13","2022-05-27","2022-06-10","2022-06-24","2022-07-08","2022-07-22","2022-08-05","2022-08-19","2022-09-02","2022-09-16","2022-09-30","2022-10-14","2022-10-28","2022-11-11","2022-11-25","2022-12-09","2022-12-23"],"GFT":["2022-01-14","2022-01-28","2022-02-11","2022-02-25","2022-03-11","2022-03-25","2022-04-08","2022-04-22","2022-05-06","2022-05-20","2022-06-03","2022-06-17","2022-07-01","2022-07-15","2022-07-29","2022-08-12","2022-08-26","2022-09-09","2022-09-23","2022-10-07","2022-10-21","2022-11-04","2022-11-18","2022-12-02","2022-12-16","2022-12-30"],"KERSTBOOM":["2022-01-17"],"OVERIG":["2022-01-17","2022-04-21","2022-05-13","2022-06-07","2022-10-12","2022-11-09","2022-11-30"],"PAPIER":["2022-01-28","2022-02-25","2022-03-25","2022-04-29","2022-05-27","2022-06-24","2022-07-29","2022-08-26","2022-09-30","2022-10-28","2022-11-25","2022-12-30"],"SNOEIAFVAL_OP_AFSPRAAK":["2022-04-21","2022-05-13","2022-06-07","2022-10-12","2022-11-09","2022-11-30"]}`

**Comment by pippyn** [comment]
Yes, that's correct. This sensor is using the same API.
Is your config correct?

**Comment by mv33rs** [comment]
Is it possible you tried to refresh your calender several times in a short amount?

rd4 has their API protected, after 4 responses within a short time, you get blocked for several minutes returning the message "Too many requests".

**Comment by JelleKoster** [comment]
I can confirm Afvalbeheer was properly working with RD4 before. The last date for which I had data was Dec 30th. I'm unsure when it retrieved that data, so it might have broken earlier than that.

**Comment by Scriptman** [comment]
Same issue for me. Was working before, but now I get the exact same error. Navigating to the URL which @razor109 mentioned, is giving me a 403 response.

**Comment by JelleKoster** [comment]
As a temporary workaround I have downloaded the "milieu app" and activated
the notifications from there.

Op di 11 jan. 2022 14:57 schreef M. Lamers ***@***.***>:

**Comment by pippyn** [comment]
I would recommend you set the [update interval](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#update-interval) of the sensor to 12 or even 24. This will decrease the requests to the api. After setting the option, reboot HA and wait a couple of days to see the results.

**Comment by Untiring** [comment]
I just spent all evening trying to get this to work, but for me too it shows "Unknown" for all sensors. RD4 does show a calendar for me when I fill in my address on their site.

this is my configuration.yaml just to verify i didnt do anything else wrong
(i changed the postal code for this post for obvious reasons)
`
sensor:
  - platform: afvalbeheer
    wastecollector: RD4
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 1111AA
    streetnumber: 61
    upcomingsensor: 7
    dayofweek: 1
    updateinterval: 12
`

**Comment by Scriptman** [comment]
It's still not working, I'm switching to a different integration

**Comment by pippyn** [comment]
Closing stale issue
