### ISSUE TITLE
WasteDateSensor state has duplicate value

### ISSUE THREAD

**Issue by stefanroelofs** [pippyn/Home-Assistant-Sensor-Afvalbeheer#277]
Recently I noticed that the WasteDateSensor state has the same waste type listed twice: `pmd, pmd`

![image](https://user-images.githubusercontent.com/37924749/148024701-006fd222-678d-4215-a87c-5821f9a7ca13.png)

Not a big issue, only now the google home appears to be stuttering when it reads out the notification 😄 

Can we filter out duplicate elements in the collection?
Or is there a better solution?

Thanks 👍🏻

**Comment by pippyn** [comment]
This is strange, are there 2 different kinds of PMD collections for today? Can you check on the ACV website for me?

**Comment by stefanroelofs** [comment]
Good idea!
I downloaded a calendar ics file from the website and there are indeed duplicates!

![image](https://user-images.githubusercontent.com/37924749/148065044-1450efe2-8a82-42c0-914c-81d3cb8c9972.png)

I guess there's nothing to do about this but contact ACV?
Thanks!

**Comment by pippyn** [comment]
I think so. I'll close this issue as I do not have any influence in the source data
