### ISSUE TITLE
Sensor has invalid timestamp

### ISSUE THREAD

**Issue by stefanroelofs** [pippyn/Home-Assistant-Sensor-Afvalbeheer#279]
My `sensor.acv_restafval` has an invalid timestamp:

![image](https://user-images.githubusercontent.com/37924749/148066766-509e552a-6685-489d-adcf-a7f7d3518116.png)

Is there something I can do about that? The value of the sensor (20-01-2022) is accurate.

The rest of the sensors all function fine:

![image](https://user-images.githubusercontent.com/37924749/148066857-2dcee522-0563-4dd8-bb92-2186fb9ece91.png)

**Comment by stefanroelofs** [comment]
Update: My PMD container got emptied yesterday, and the PMD sensor got a new date.
Now this sensor also has an invalid timestamp:

![image](https://user-images.githubusercontent.com/37924749/148176151-5f1de046-5734-4dab-9205-f48cff305c0d.png)

So I guess the state is not a valid ISO 8601 timestamp?
I think it needs to be formatted like: YYYY-MM-DD ?

I filtered my entity list by `device_class: timestamp`, so I got all timestamp sensors. All other sensors had a state in this format: 
`2022-01-11T13:55:01+00:00`

**Comment by pippyn** [comment]
You would want the state for the sensor as a date object. You can do that with this option:
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#date-object

**Comment by stefanroelofs** [comment]
I found the issue, thanks for pointing me in the right direction!
Here's what happened:
As you can see in the screenshots above, my sensors had device_class: timestamp.
Even though the `dateobject` option was not used (so it had the default value false).

See this code:
![image](https://user-images.githubusercontent.com/37924749/148949336-2dd0eb17-22d1-411a-afe6-6a65d049a256.png)
The sensor should only be a timestamp when the option is true.

I've had this sensor active for a long time (more than a year). I think somewhere along the way the device class was set to timestamp by default, and then afterwards never changed again.

To test I've deleted the sensors and then recreated them. Everything looks fine now.

Maybe you can create an `else` statement here like this?
```python
    @property
    def device_class(self):
        return DEVICE_CLASS_TIMESTAMP if self.date_object else ""
```
Now when you set the `dateobject` option to false, the device_class is removed (maybe?). I did not test this.

**Comment by stefanroelofs** [comment]
And maybe it is nice to change this line to return a timestamp instead of a date object?

https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/873809dfd274c51be5697bbb3c1fca3ac473f93d/custom_components/afvalbeheer/sensor.py#L1422

`self._state = collection.date.timestamp()`

But I don't really know, it might be a breaking change for some people?

**Comment by pippyn** [comment]
No I don't think so. This option exists so people can do whatever with the object they like. (like making it a timestamp)
And it would most definitely be a breaking change.
