### ISSUE TITLE
Limburg.NET switched to' Optimo'

### ISSUE THREAD

**Issue by gijbelsy** [pippyn/Home-Assistant-Sensor-Afvalbeheer#281]
At the start of 2022 Limburg.NET changed the way it's collecting waste. The program is called 'Optimo'.
All waste is collected at once, every 2 weeks in colored bags for separation.

This means that the previous integration of Limburg.NET is broken.
A new JSON file is attached to this post
[2022-1.txt](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/files/7813172/2022-1.txt)
.

**Comment by bollekes01** [comment]
> At the start of 2022 Limburg.NET changed the way it's collecting waste. The program is called 'Optimo'. All waste is collected at once, every 2 weeks in colored bags for separation.
> 
> This means that the previous integration of Limburg.NET is broken. A new JSON file is attached to this post [2022-1.txt](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/files/7813172/2022-1.txt) .

confirming by using attached json file functionality has resumed. thank you

**Comment by riversideneyon** [comment]
Thanks, can someone create Pull requests?

I don't know what to do exactly with that JSON? I don't see related file on Github compoment.

**Comment by mhemeryck** [comment]
I also don't really get what this is supposed to fix.

Had a look myself at the API endpoints from limburg.net and comparing it with the paper version calendar, I actually have the idea it reports the correct dates. Even more, the current limburg.net website itself is using the *very same API endpoints*.

I just came here since I had noticed that after the first new waste collection, the dates weren't updating in my home assistant installation, but that might have just been some temporary issue with the availability of the limburg.net API (perhaps there was a switchover with some downtime around this point).

Another issue I've seen is that the dates reported themselves look OK, but they are always reported as one day ahead of today. Not sure if it's related, probably for another issue.

**Comment by pippyn** [comment]
> Another issue I've seen is that the dates reported themselves look OK, but they are always reported as one day ahead of today. Not sure if it's related, probably for another issue.

Can you please elaborate? Maybe make a new issue?

**Comment by gijbelsy** [comment]
I noticed that the integration wasn't showing any data after 01/01/2022, the date that Limburg.NET switched to Optimo.
Therefore my conclusion was that they've changed the format of the json.

For convenience, I've fetched a new JSON (attached to the original post), to be compared with the old integration.
I thought some of the fraction names, or json format have been changed.

**Comment by mhemeryck** [comment]
> > Another issue I've seen is that the dates reported themselves look OK, but they are always reported as one day ahead of today. Not sure if it's related, probably for another issue.
> 
> Can you please elaborate? Maybe make a new issue?

Sure! This is from a sensor output from today:

![image](https://user-images.githubusercontent.com/5445250/149743266-b92ec981-d889-42cf-9639-1723d2df04c9.png)

So, it says the collection is due tomorrow, whereas it's actually today.

Related API call:

```
curl https://www.limburg.net/api-proxy/public/kalender/73083/2022-01\?straatNummer\=79117\&huisNummer\=30\&toevoeging\=%22%22 | jq
{
  "activiteitenLegende": {
    "5": {
      "nummer": "5",
      "omschrijving": "Gft ",
      "detail_url": "https://limburg.net/fractie/gft"
    },
    "10": {
      "nummer": "10",
      "omschrijving": "kerstboom",
      "detail_url": null
    },
    "14": {
      "nummer": "14",
      "omschrijving": "Papier & karton",
      "detail_url": "https://limburg.net/fractie/papier-karton"
    },
    "22": {
      "nummer": "22",
      "omschrijving": "Pmd",
      "detail_url": "https://limburg.net/fractie/pmd"
    },
    "23": {
      "nummer": "23",
      "omschrijving": "Textiel",
      "detail_url": "https://limburg.net/fractie/textiel"
    },
    "27": {
      "nummer": "27",
      "omschrijving": "Huisvuil",
      "detail_url": "https://limburg.net/fractie/huisvuil"
    }
  },
  "gemeenteKalender": {
    "kalenderNaam": "Tongeren1",
    "feestDagen": [
      {
        "datum": "01/01/2022",
        "feestDagType": "Nieuwjaar"
      },
      {
        "datum": "17/04/2022",
        "feestDagType": "Pasen"
      },
      {
        "datum": "18/04/2022",
        "feestDagType": "Paasmaandag"
      },
      {
        "datum": "01/05/2022",
        "feestDagType": "Feest van de Arbeid"
      },
      {
        "datum": "26/05/2022",
        "feestDagType": "O.L.H. Hemelvaart"
      },
      {
        "datum": "05/06/2022",
        "feestDagType": "Pinksteren"
      },
      {
        "datum": "06/06/2022",
        "feestDagType": "Pinkstermaandag"
      },
      {
        "datum": "21/07/2022",
        "feestDagType": "Nationale feestdag"
      },
      {
        "datum": "15/08/2022",
        "feestDagType": "O.L.V Hemelvaart"
      },
      {
        "datum": "01/11/2022",
        "feestDagType": "Allerheiligen"
      },
      {
        "datum": "11/11/2022",
        "feestDagType": "Wapenstilstand"
      },
      {
        "datum": "25/12/2022",
        "feestDagType": "Kerstmis"
      }
    ],
    "gemeenteActiviteiten": [
      {
        "datum": "12/03/2022",
        "mededeling": "Vergeet geen gft-sticker 2022 te kopen"
      },
      {
        "datum": "28/03/2022",
        "mededeling": "Kleef uw gft-sticker 2022 op uw bak"
      },
      {
        "datum": "29/03/2022",
        "mededeling": "Zomeruur op recyclagepark - p. 36"
      },
      {
        "datum": "02/11/2022",
        "mededeling": "Winteruur op recyclagepark - p. 36"
      },
      {
        "datum": "24/12/2022",
        "mededeling": "Recyclagepark namiddag gesloten"
      },
      {
        "datum": "31/12/2022",
        "mededeling": "Recyclagepark namiddag gesloten"
      }
    ],
    "legende": [],
    "legendeExtra": []
  },
  "ophalingen": {
    "kalenderNummer": "1643",
    "lijstVanOphaalDagen": [
      {
        "datum": "2022-01-06T10:29:02+01:00",
        "activiteitCode": "5",
        "subZoneCode": "",
        "displayCode": 1,
        "displayReden": null
      },
      {
        "datum": "2022-01-13T10:29:02+01:00",
        "activiteitCode": "10",
        "subZoneCode": "",
        "displayCode": 1,
        "displayReden": null
      },
      {
        "datum": "2022-01-13T10:29:02+01:00",
        "activiteitCode": "27",
        "subZoneCode": "",
        "displayCode": 1,
        "displayReden": null
      },
      {
        "datum": "2022-01-13T10:29:02+01:00",
        "activiteitCode": "22",
        "subZoneCode": "",
        "displayCode": 1,
        "displayReden": null
      },
      {
        "datum": "2022-01-13T10:29:02+01:00",
        "activiteitCode": "23",
        "subZoneCode": "",
        "displayCode": 1,
        "displayReden": null
      },
      {
        "datum": "2022-01-17T10:29:02+01:00",
        "activiteitCode": "14",
        "subZoneCode": "",
        "displayCode": 1,
        "displayReden": null
      },
      {
        "datum": "2022-01-20T10:29:02+01:00",
        "activiteitCode": "5",
        "subZoneCode": "",
        "displayCode": 1,
        "displayReden": null
      },
      {
        "datum": "2022-01-27T10:29:02+01:00",
        "activiteitCode": "27",
        "subZoneCode": "",
        "displayCode": 1,
        "displayReden": null
      },
      {
        "datum": "2022-01-27T10:29:02+01:00",
        "activiteitCode": "22",
        "subZoneCode": "",
        "displayCode": 1,
        "displayReden": null
      },
      {
        "datum": "2022-01-27T10:29:02+01:00",
        "activiteitCode": "23",
        "subZoneCode": "",
        "displayCode": 1,
        "displayReden": null
      }
    ]
  },
  "events": [
    {
      "type": "Huis-aan-huis-ophaling",
      "category": "Gft ",
      "date": "2022-01-06T10:29:02+01:00",
      "title": "Gft ",
      "description": null,
      "time": null,
      "location": null,
      "detailUrl": "https://limburg.net/fractie/gft",
      "display": {
        "code": 1,
        "reden": null
      }
    },
    {
      "type": "Huis-aan-huis-ophaling",
      "category": "kerstboom",
      "date": "2022-01-13T10:29:02+01:00",
      "title": "kerstboom",
      "description": null,
      "time": null,
      "location": null,
      "detailUrl": null,
      "display": {
        "code": 1,
        "reden": null
      }
    },
    {
      "type": "Huis-aan-huis-ophaling",
      "category": "Huisvuil",
      "date": "2022-01-13T10:29:02+01:00",
      "title": "Huisvuil",
      "description": null,
      "time": null,
      "location": null,
      "detailUrl": "https://limburg.net/fractie/huisvuil",
      "display": {
        "code": 1,
        "reden": null
      }
    },
    {
      "type": "Huis-aan-huis-ophaling",
      "category": "Pmd",
      "date": "2022-01-13T10:29:02+01:00",
      "title": "Pmd",
      "description": null,
      "time": null,
      "location": null,
      "detailUrl": "https://limburg.net/fractie/pmd",
      "display": {
        "code": 1,
        "reden": null
      }
    },
    {
      "type": "Huis-aan-huis-ophaling",
      "category": "Textiel",
      "date": "2022-01-13T10:29:02+01:00",
      "title": "Textiel",
      "description": null,
      "time": null,
      "location": null,
      "detailUrl": "https://limburg.net/fractie/textiel",
      "display": {
        "code": 1,
        "reden": null
      }
    },
    {
      "type": "Huis-aan-huis-ophaling",
      "category": "Papier & karton",
      "date": "2022-01-17T10:29:02+01:00",
      "title": "Papier & karton",
      "description": null,
      "time": null,
      "location": null,
      "detailUrl": "https://limburg.net/fractie/papier-karton",
      "display": {
        "code": 1,
        "reden": null
      }
    },
    {
      "type": "Huis-aan-huis-ophaling",
      "category": "Gft ",
      "date": "2022-01-20T10:29:02+01:00",
      "title": "Gft ",
      "description": null,
      "time": null,
      "location": null,
      "detailUrl": "https://limburg.net/fractie/gft",
      "display": {
        "code": 1,
        "reden": null
      }
    },
    {
      "type": "Huis-aan-huis-ophaling",
      "category": "Huisvuil",
      "date": "2022-01-27T10:29:02+01:00",
      "title": "Huisvuil",
      "description": null,
      "time": null,
      "location": null,
      "detailUrl": "https://limburg.net/fractie/huisvuil",
      "display": {
        "code": 1,
        "reden": null
      }
    },
    {
      "type": "Huis-aan-huis-ophaling",
      "category": "Pmd",
      "date": "2022-01-27T10:29:02+01:00",
      "title": "Pmd",
      "description": null,
      "time": null,
      "location": null,
      "detailUrl": "https://limburg.net/fractie/pmd",
      "display": {
        "code": 1,
        "reden": null
      }
    },
    {
      "type": "Huis-aan-huis-ophaling",
      "category": "Textiel",
      "date": "2022-01-27T10:29:02+01:00",
      "title": "Textiel",
      "description": null,
      "time": null,
      "location": null,
      "detailUrl": "https://limburg.net/fractie/textiel",
      "display": {
        "code": 1,
        "reden": null
      }
    }
  ]
}
```

Or, specifically for the screenshot:

```
curl https://www.limburg.net/api-proxy/public/kalender/73083/2022-01\?straatNummer\=79117\&huisNummer\=30\&toevoeging\=%22%22 | jq '.ophalingen.lijstVanOphaalDagen[5]' 
{
  "datum": "2022-01-17T10:32:53+01:00",
  "activiteitCode": "14",
  "subZoneCode": "",
  "displayCode": 1,
  "displayReden": null
}

One thing I have noticed wrt to my date issue is that the timestamps all include the *current* time of day (hours, mins, secs), doesn't even relate to the actual time of waste collection. This also seems to be parsed in the code: https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/c50ca7b016e3eb97eeccf97f1da21660d4bb40dd/custom_components/afvalbeheer/sensor.py#L878-L881. Might be related to the thing I'm seeing and I'd doubt you'd need the part beyond the date. On the other hand, could just be my install :slightly_smiling_face:

**Comment by pippyn** [comment]
> So, it says the collection is due tomorrow, whereas it's actually today.

Well the date is correct, but it should say today. Which makes me suspect your HA server date is off by one day or in the incorrect time zone?
So the data is imported correctly. The sensor then compares the collection date with the current date to determine how many days from now the collection is. To do this it uses the system time. Please check your server settings. On my end the sensor state is correct with your settings.

> One thing I have noticed wrt to my date issue is that the timestamps all include the current time of day (hours, mins, secs), doesn't even relate to the actual time of waste collection. This also seems to be parsed in the code:

That's just how the Limburg.net API reports the data (I'm not sure why), my code just parses the string into a date object.

**Comment by pippyn** [comment]
@gijbelsy I have 5 addresses to test the Limburg.net integration. They are all working normally. Could you please check if it's working for your address now too? Maybe reboot HA and wait a few minutes.

If not; please DM me your address and sensor config on the HA forum please and I'll do some tests

**Comment by mhemeryck** [comment]
> > So, it says the collection is due tomorrow, whereas it's actually today.
> 
> Well the date is correct, but it should say today. Which makes me suspect your HA server date is off by one day or in the incorrect time zone? So the data is imported correctly. The sensor then compares the collection date with the current date to determine how many days from now the collection is. To do this it uses the system datetime. Please check your server settings. On my end the sensor state is correct with your settings.

I thought had checked this before, but after checking again I did notice:
* the host system was actually in the wrong timezone (off by one hour; CET vs GMT)
* the container seems to be running in UTC / the config I have does not have any time zone explicitly set.

I'm guessing indeed it has something to do with my time / timezone setup. nvm my comment!

Thx btw for the very fast and thorough response!

**Comment by 20bart** [comment]
There is one thing missing. It's called 'tuinbak' which is new in the optimo plan. I can't seem to find it in the code.

**Comment by pippyn** [comment]
All fractions are supported by default. Use the option [`Print all available waste fractions`](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions) to view the available fractions.

**Comment by riversideneyon** [comment]
> Thanks, can someone create a Pull requests?
> 
> I don't know what to do exactly with that JSON? I don't see related file on Github compoment.

It works now fine, probably updating the version of the integration.

**Comment by pippyn** [comment]
Closing stale issue
