### ISSUE TITLE
Add Lingewaard afval

### ISSUE THREAD

**Issue by TimBoz** [pippyn/Home-Assistant-Sensor-Afvalbeheer#286]
Hello,

Is it possible to add de Lingewaard afvalwijzer tot de list of collectors? It uses the same tooling as 'alkmaar' i have added the link manually in the sensor.py and in seems to work.

de following line can be added tot the "OPZET_COLLECTOR_URLS" section,
    'lingewaard': 'https://afvalwijzer.lingewaard.nl',

**Comment by Dutcherik** [comment]
Yes, that would be very nice.
I used MijnAfvalwijzer successfully until January 1.
Now there is this new afvalwijzer.lingewaard app.

**Comment by TimBoz** [comment]
Lingewaard afvalwijzer has been added in the latest reo.
