### ISSUE TITLE
Circulus Berkel to Circulus

### ISSUE THREAD

**Issue by otterlo** [pippyn/Home-Assistant-Sensor-Afvalbeheer#287]
Hi

i keep getting the warning that i am still using Circulus-Berkel as waste collector but i changed all to Circulus. i looked at the code where this message is coming from (depreciated). can it be that the code still triggers this warning but incorrectly? 

i check all automations and lovelace but still getting the warning

**Comment by roynijkamp** [comment]
You have to chance the wastecollector in configuration.yaml

**Comment by otterlo** [comment]
thanks! i am emberrased. i changed it also in configuration.yaml but i must have forgotten to save the file.
it is working now, sorry for causing the trouble
