### ISSUE TITLE
PMD for meerlanden

### ISSUE THREAD

**Issue by Plork** [pippyn/Home-Assistant-Sensor-Afvalbeheer#29]
Deze werkt op het moment niet en ik krijg een unkown.

```    {
        "id": 14,
        "parent_id": 0,
        "title": "Plastic, Blik en Drinkpakken",
        "slug": "plastic",
        "tags": null,
        "page_title": "Plastic, Blik en Drinkpakken",
        "content": "...",
        "menu_title": "Plastic, Blik en Drinkpakken",
        "icon": "petfles-blik-drankpak_pmd",
        "icon_data": "",
        "ophaaldatum": "2020-01-16"
    },
```

zo ziet de json eruit van meerlanden. geen title "pmd" iig.

Ik probeer door de code te graven om te kijken waar het mis gaat maar ben er nog niet goed achter hoe ik dit debug in HA.

**Comment by Plork** [comment]
als ik het goed begrijp zoek je de "sensor_type", pmd in dit geval, op in je json die je terugkrijgt van `/afvalstromen`.

Dat gaat in dit geval nooit lukkken

**Comment by Plork** [comment]
Ik dacht zelf dat dit zou moeten werken.

```
RENAME_TITLES = {
    'duobak': 'duobak',
    'gft gratis': 'gft gratis',
    'groente': 'gft',
    'gft': 'gft',
    'papier': 'papier',
    'rest': 'restafval',
    'blik': 'pbd',
    'plastic': 'pmd',
    'plastic, blik en drinkpakken': 'pmd',
    'sloop': 'sloopafval',
    'klein chemisch afval': 'kca',
    'kca': 'kca',
    'pmd': 'pmd',
    'textiel': 'textiel',
    'kerstbo': 'kerstbomen',
    'snoeiafval': 'snoeiafval',
}
```

maar ik krijg nog steeds een unknown

**Comment by Plork** [comment]
Oke na wat debuggen ben ik er achter dat het "pbd" heet en waarschijnlijk omdat er "blik" in de naam zit. 

```
for dict_title in RENAME_TITLES:
                            if dict_title in check_title:
                                title = RENAME_TITLES[dict_title]
                                break
```

dat is geen "exact" match en ik denk dat het door deze komt.

`'blik': 'pbd',`

**Comment by pippyn** [comment]
Only English is allowed. But yeah Plastic, Blik en Drinkpakken is PBD, not PMD.
