### ISSUE TITLE
wastecollector: DeAfvalApp: papier unknown status

### ISSUE THREAD

**Issue by Roger-NL1975** [pippyn/Home-Assistant-Sensor-Afvalbeheer#294]
wastecollector: DeAfvalApp

I have noticed that since about 2wk. the paper (papier) data is unknown.
is there a change made in the wastecollector: DeAfvalApp settings?

**Comment by pippyn** [comment]
And the calendar on the DeAfvalApp website does give you this information?
If so; Can you DM me your sensor config on the HA forum? (including address)

**Comment by Roger-NL1975** [comment]
Hi pippyn thnaks for the responce i should have checked this before I made the topic, so no it doesn't show the paper data, because we don't have the container our self.... ;( 
on a different adress It does show the values.

anyway thanks for the great addon---- keep up the good work
