### ISSUE TITLE
Kerstbomen unknown

### ISSUE THREAD

**Issue by remcoblom** [pippyn/Home-Assistant-Sensor-Afvalbeheer#299]
Hi,

I cant seem to get the kertbomen option to work for GAD variant. 
postalscode 1215BP,  46.

can somebody help with this?

**Comment by remcoblom** [comment]
Hi,

Thanks for the update.
Just to be clear it’s not my personal adres 😎

Cheers



Verstuurd vanaf mijn iPhone

Op 12 feb. 2022 om 16:58 heeft Job van Koeveringe ***@***.***> het volgende geschreven:

﻿

Hey @remcoblom<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fremcoblom&data=04%7C01%7C%7C084fdfb0b31d4db3395508d9ee408f2d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637802783325934329%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dra7CTLIv8rLJMCkCuHtFEzpFxOwxVvOkLUMF7r7KVk%3D&reserved=0>,

It's not smart to share your personal address😉

But if i put the zip code in the API, the result says null. So I guess GAD hasn't added a new date for picking up Christmas trees yet.

[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F32730202%2F153718226-688dadc4-0246-4b72-8d24-92fbee79a2f2.png&data=04%7C01%7C%7C084fdfb0b31d4db3395508d9ee408f2d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637802783325934329%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tYEGR21PzXi5qCl5VEdB4Y%2FLhl0dg6ggt0Um5Rhh8%2Bo%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpippyn%2FHome-Assistant-Sensor-Afvalbeheer%2Fissues%2F299%23issuecomment-1037267836&data=04%7C01%7C%7C084fdfb0b31d4db3395508d9ee408f2d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637802783325934329%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=g9MosGa8eL07CxqJdgbdaA95PwGv%2FqV%2FUD1Hnn9n%2Bzk%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAW5BPKRB7QJQVSTDQ4DMZYDU2Z7TTANCNFSM5N3HDEEQ&data=04%7C01%7C%7C084fdfb0b31d4db3395508d9ee408f2d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637802783326089706%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KS11QUqzDJdnnSqJMghCkZeZGUHVTMOP7yGxLs0ko6M%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C084fdfb0b31d4db3395508d9ee408f2d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637802783326089706%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tBDi84uioyfAe1%2BXU7twnPwsJGdASjzSN2g8mfwGUUw%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C084fdfb0b31d4db3395508d9ee408f2d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637802783326089706%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=z0zsKZ4IFgc7r7LTnQqFuNzeHsS4tOiDo1n14ac4kzk%3D&reserved=0>.

**Comment by pippyn** [comment]
Can this issue be closed?
