### ISSUE TITLE
Question to add mijnafvalwijzer.nl

### ISSUE THREAD

**Issue by IIIdefconIII** [pippyn/Home-Assistant-Sensor-Afvalbeheer#3]
https://www.mijnafvalwijzer.nl/nl/

Would you check if its easy to support this website? This is for the whole netherlands

**Comment by pippyn** [comment]
No ths sensor will work with all waste collectors using the same API. Mijnafvalwijzer works in a different way.

There's a [custom component to support mijnafvalwijzer](https://community.home-assistant.io/t/garbage-pickup-date-mijnafvalwijzer-nl-custom-component).
