### ISSUE TITLE
PMD for GAD (Hilversum, Wijdemeren etc)

### ISSUE THREAD

**Issue by clsgroen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#30]
Although there are already 2 other PMD for .. topics I'm making this a separate issue because I'm not sure it's the same one. PMD for GAD is not recognized and gives a value unknown in HA. 

A link to the output for a nearby building: https://inzamelkalender.gad.nl/rest/adressen/1696200000288611/afvalstromen

Tried adding plastic to recources in the config and RENAME_TITLES in the sensor.py but to no avail, unfortunately I'm not a python wizz so I'm not getting any firther on my own.

**Comment by pippyn** [comment]
Should be PBD, not PMD
