### ISSUE TITLE
Integration not working after update from 4.8.1 to 4.9.2 

### ISSUE THREAD

**Issue by Rosenwasser** [pippyn/Home-Assistant-Sensor-Afvalbeheer#300]
Dear Pippyn,

First of al many thanks for this beautiful integration which works for more than one year without problems.
I think it is really helpful for many people including me.

This morning true HACS, I updated the integration from version 4.8.1 to version 4.9.2 
After the update this integration has stopped working and I can’t figure out why.

I did not changed any configuration.

At the moment I copied back the old files in the folder “custom_components\afvalbeheer” and now it is working again.

Can you give me a tip what I can do to let it work with the last version 4.9.2 ?

Regards,
Benny

**Comment by pippyn** [comment]
did you reboot HA after the update? If something is wrong, there should be an error in the logs after a couple of minutes.

**Comment by pippyn** [comment]
Yes that could be the issue. Maybe you were to fast to judge ;)
