### ISSUE TITLE
Katwijk (ZH) toevoegen

### ISSUE THREAD

**Issue by theohoogervorst** [pippyn/Home-Assistant-Sensor-Afvalbeheer#301]
Is het mogelijk om Katwijk toe te voegen?

https://afval.katwijk.nl/nc/afvalkalender/

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by theohoogervorst** [comment]
Offcourse,

Kreeft 13
2221 KD Katwijk


Op do 3 mrt. 2022 08:12 schreef Pippyn ***@***.***>:

**Comment by pippyn** [comment]
I can't find an open API for Katwijk. So I'm afraid I won't be able to integrate your municipality.

You could use a [scrape sensor](https://www.home-assistant.io/integrations/scrape/) I think.
