### ISSUE TITLE
Wastetypes Venray stay blank

### ISSUE THREAD

**Issue by sjorzel** [pippyn/Home-Assistant-Sensor-Afvalbeheer#302]
Below my configuration and the notification that I get stays blank. What did I miss to get this working?

**Configuration**
```platform: afvalbeheer
    wastecollector: Venray
    resources:
      - gft
      - papier
      - pmd
    postcode: 58xxyy
    streetnumber: xx
    suffix: y
    upcomingsensor: 1
    dateformat: '%-d %b'
    dateonly: 0
    dateobject: 0
    name: ''
    nameprefix: 1
    builtinicons: 1
    disableicons: 0
    dutch: 1
    printwastetypes: 1
```

**Notification**
```
Afvalwijzer
Available waste types: 
3 minuten geleden
```

**Comment by pippyn** [comment]
Does `https://afvalkalender.venray.nl` give you the correct information for your address?
If so; please DM me your address in the HA forum and I'll do some tests.

**Comment by sjorzel** [comment]
Maybe a silly question, but how do I do that? I'm not an experienced user of Github 😅.

**Comment by pippyn** [comment]
The DM? It's not on Github, but on the HA forum. This is me: https://community.home-assistant.io/u/pippyn

**Comment by sjorzel** [comment]
Suggestion of removing the suffix worked.
