### ISSUE TITLE
(Purmerend) GFT gives Unknown

### ISSUE THREAD

**Issue by Wxam** [pippyn/Home-Assistant-Sensor-Afvalbeheer#304]
Since a couple of days my GFT sensor gives Unkown for the GFT.
I've restarted HA a couple of times and also tried to reset the sensor but it still doesn't work.
![image](https://user-images.githubusercontent.com/20145041/157427393-6411a0ec-f19c-4964-85d7-cfc86821088c.png)

When I look on the website of Purmerend itself it says Bio-afval.
So I think they changed the name.
![image](https://user-images.githubusercontent.com/20145041/157427517-084e9883-683c-48c1-ba8e-c121d16ea2b3.png)

Hope we can add Bio-afval

**Comment by pippyn** [comment]
Use the option [`Print all available waste fractions`](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions) to see which fraction are supported by your collector.

**Comment by Wxam** [comment]
Thanks this worked it indeed changed to Bio-afval 👍 
Changed my GFT to Bio-afval and now it works again.
