### ISSUE TITLE
omrin sensor doens't work

### ISSUE THREAD

**Issue by siegfried2003** [pippyn/Home-Assistant-Sensor-Afvalbeheer#307]
for omrin, the sensor restafval or grofvuil doens't work. It is strange because gft and paper does work. Do you have any sugestion what I must do to fix?

**Comment by pippyn** [comment]
Did it used to work? or is this a new installation?
Did you try the option [`Print all available waste fractions`](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions) to see which fraction are supported by your collector?

**Comment by pippyn** [comment]
And what does the Print option say?

**Comment by timovos** [comment]
Working fine here. Sortibak, gft, papier, no problems.

**Comment by siegfried2003** [comment]
Thanks, I also got it working. There finally was a mistake in my ha config file. Thanks a lot
