### ISSUE TITLE
attributes no longer available in home assisant core_2022.4.0b5

### ISSUE THREAD

**Issue by T-Luyten** [pippyn/Home-Assistant-Sensor-Afvalbeheer#309]
The sensors no longer provide attributes like days until ... in the latest beta from home assistant.

**Comment by pippyn** [comment]
Are there any errors? Are you using the latest version of this sensor?

**Comment by T-Luyten** [comment]
I thought it was the latest version but apparently it was not.  Probably something went wrong when i uploaded the files.
Everything works now.  Thank you for your fast response and pointing me to the right direction to look at.
