### ISSUE TITLE
AreaReiniging not showing dates anymore

### ISSUE THREAD

**Issue by Tyrian81** [pippyn/Home-Assistant-Sensor-Afvalbeheer#311]
`  #====================
  #=== Afvaldiensten
  #====================
  - platform: afvalbeheer
    wastecollector: AreaReiniging            
    resources:                       
      - restafval
      - gft
      - papier
      - pmd
    postcode: ****VV            
    streetnumber: **               
    upcomingsensor: 0               
    dateformat: '%d-%m-%Y'          
    dateonly: 0                     
    dateobject: 0                   
    name: ''                        
    nameprefix: 1                    
    builtinicons: 0                  
    disableicons: 0                  
    dutch: 1      `

logs says no waste data found ?
api removed ? the android app still shows waste data ?

**Comment by wilfredsmit** [comment]
Same here!

**Comment by Tyrian81** [comment]
Seems fixed, maybe API down

**Comment by pippyn** [comment]
Could be a outage, keep an eye on it to see if it continues to work.
I'll close this issue for now.
