### ISSUE TITLE
Groningen ?

### ISSUE THREAD

**Issue by pointjalta** [pippyn/Home-Assistant-Sensor-Afvalbeheer#312]
To me it seems that the "afvalwijzer-groningen" component  from 2019 isn't working. I found out about the component called "Afvalbeheer" which seems to be more recent so I tried that one instead.  Maybe it's just me but or it's because this component is unable to pull data from the city of Groningen or it's because I am overlooking something. 

Can you add Groningen to the component  or is it just not possible right now ?

**Comment by pippyn** [comment]
You'll need to use the `MijnAfvalwijzer` collector for Groningen

**Comment by pointjalta** [comment]
Thank you. I think that I’ll probably get it to work.  

tnx 
Marco.

**Comment by pippyn** [comment]
No problem!
Let me know if there are any issues. (if there are no issues, please close this issue. Thank you!)

FYI: I'm also the author of the old groningen sensor. So I deprecated that sensor as it no longer works.

**Comment by pippyn** [comment]
Can this issue be closed?

**Comment by pointjalta** [comment]
yes
sorry about it and thank you 😉
