### ISSUE TITLE
Spaarnelanden - Legen Duo-bak date is Unknown

### ISSUE THREAD

**Issue by pjannink** [pippyn/Home-Assistant-Sensor-Afvalbeheer#320]
Since a few weeks the "Legen duo-bak" date for Spaarnelanden is Unknown (sensor.spaarnelanden_duobak). 
Before it showed the correct dates.
I upgraded all to the latest versions  - HA 2022.6.7. , HACS version 1.25.5 and Integration version 4.9.4 - to no avail.

Any ideas??

**Comment by pippyn** [comment]
Did you try the option [Print all available waste fractions](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions)?

Does the Spaarnelanden website report the correct values?

**Comment by pippyn** [comment]
I'm glad all is working again.

You are right! I just changed the readme

**Comment by pjannink** [comment]
Thanks. May be also here:

 



 

Van: Pippyn ***@***.***> 
Verzonden: vrijdag 24 juni 2022 15:16
Aan: pippyn/Home-Assistant-Sensor-Afvalbeheer ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pippyn/Home-Assistant-Sensor-Afvalbeheer] Spaarnelanden - Legen Duo-bak date is Unknown (Issue #320)

 

I'm glad all is working again.

You are right! I just changed the readme
