### ISSUE TITLE
Afval beheerder changed in Alkmaar

### ISSUE THREAD

**Issue by majbah-ha** [pippyn/Home-Assistant-Sensor-Afvalbeheer#323]
Hi,
Since a few weeks is the company collecting the waste in Alkmaar and surroundings has changed.
Before it was Stadswerk072, now it is HVC. That's why the sensors are not working anymore. 
Can you please fix this.
Many thanks.
majB

**Comment by pippyn** [comment]
What do you want me to fix? HVC is already supported, is it not working for you? Did you change the config to HVC?

**Comment by pippyn** [comment]
Version v4.9.5 adds a deprecation warning for Alkmaar users

**Comment by majbah-ha** [comment]
Thanks for pointing that out, I missed it.
Changing it to HVC does make it work again,
Sorry to bother you, and many thanks for your hard work

**Comment by majbah-ha** [comment]
Solved
