### ISSUE TITLE
Image when two pickups

### ISSUE THREAD

**Issue by Obelixje** [pippyn/Home-Assistant-Sensor-Afvalbeheer#325]
When there are more than one junk pick ups on one day, there is no image showing for sensor today and tomorrow
How can I configure an image when sensor has state: papier, restafval.

**Comment by pippyn** [comment]
You would need to set a `icon_template` I believe. But I'm not sure. I would recommend asking a question on the HA forum.
I will close this issue now, because this is out of the scope of this custom component.
