### ISSUE TITLE
Max retries exceeded with url: /api/app/v1/access-token

### ISSUE THREAD

**Issue by stefanuytterhoeven** [pippyn/Home-Assistant-Sensor-Afvalbeheer#328]
Get this error already about two weeks (even more).
Changed the frequency to 12 hours , but still this error.
An update mentioned that the frequency change to 12 hours a bit later.
Still nothing.... Are we blacklisted? Is there a solution?

**Comment by pippyn** [comment]
Same as issue #321
Fixed in v4.9.6

**Comment by stefanuytterhoeven** [comment]
Updated to v4.9.5 not long ago.
Didn't get a message that there was a new update.
In hacs, only after choosing 'update information ' , in got the 'update'
option.
And...
It's fixed and working!

Thanks!

Op di 5 jul. 2022 08:51 schreef Pippyn ***@***.***>:

**Comment by pippyn** [comment]
That's because I just released the update.
