### ISSUE TITLE
does not work anymore

### ISSUE THREAD

**Issue by supermarcie** [pippyn/Home-Assistant-Sensor-Afvalbeheer#330]
Hi,

I use this for severall months but from 2 weeks ago it does not work anymore.
It does not retrieve any dates anymore.
I'm using the wastecollector: RecycleApp

can you please help me wih this?

**Comment by pippyn** [comment]
Hi,

Sure! But this not enough information. 
Do you have any errors in your logs?
What is your config?

**Comment by supermarcie** [comment]
hi just did the last update, no idea why it was not updated by HACS.
Now it is working again
