### ISSUE TITLE
Feature request: Multiple addresses/configurations

### ISSUE THREAD

**Issue by DrBlokmeister** [pippyn/Home-Assistant-Sensor-Afvalbeheer#333]
I live in a place where I have easy access to two trash collecting zones with different dates for each. I'd like to add not only my own address, but also an address that corresponds to the other zone. To distinguish between the two, I'd like to add a name/ID to either address/entry/configuration.

**Comment by pippyn** [comment]
That what the [name prefix](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#name-prefix) is for

**Comment by DrBlokmeister** [comment]
I feel like an idiot now. Thanks for the reply. I saw a comment that multi-config was not yet supported and found no issues that mention multiple configurations.
