### ISSUE TITLE
Fraction renamed for wastecollector Spaarnelanden

### ISSUE THREAD

**Issue by Peklaa** [pippyn/Home-Assistant-Sensor-Afvalbeheer#334]
My wastecollector is Spaarnelanden. The fraction "duobak" has worked well for me for over two years, but now they seem to have renamed to "papier-pmd"
The printwastetypes notification says: Available waste types: gft, papier-pmd
Would it be possible to update the component to recognize this fraction for this wastecollector?

**Comment by pippyn** [comment]
All fractions are supported by default. Just change your config; remove duobak and add papier-pmd

**Comment by Peklaa** [comment]
Yes, it does, thanks for pointing this out. I had already changed the config, but didn't notice that there was a new entity. It's simple enough, I should've been able to figure this one out by myself...
