### ISSUE TITLE
Vandaag and Morgen not getting translated into Today and Tomorrow

### ISSUE THREAD

**Issue by robvangeloven** [pippyn/Home-Assistant-Sensor-Afvalbeheer#338]
Checking the code it seems when checking delta.days the parameter dutch_days should also be checked. At the moment it doesn't so setting dutch:0 doesn't result in vandaag and morgen being translated into today and tomorrow

**Comment by pippyn** [comment]
Thank you for pointing this out. This will be fixed in the next release.

**Comment by pippyn** [comment]
Changed in v5.0.2
