### ISSUE TITLE
Error when running afvalbeheer

### ISSUE THREAD

**Issue by CrisRijsdijk** [pippyn/Home-Assistant-Sensor-Afvalbeheer#340]
Hi,
I getting this error when running your code.
Traceback (most recent call last):
File "/config/custom_components/afvalbeheer/API.py", line 132, in async_update
await self.collector.update()
File "/config/custom_components/afvalbeheer/API.py", line 271, in update
data = (response['ophaaldagen']['data'] + response['ophaaldagenNext']['data'])
KeyError: 'ophaaldagen'

Am i doing something wrong, just installed it so i assume i have the latest version.
my configuration.yaml
Offcourse adress is entered.
afvalbeheer:
  wastecollector: MijnAfvalwijzer
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 
  streetnumber: 
  suffix: a                        # (optional)
  upcomingsensor: 1                # (optional)
  dateformat: '%d-%m-%Y'           # (optional)
  dateonly: 0                      # (optional)
  name: ""                         # (optional)
  nameprefix: 1                    # (optional)
  builtinicons: 0                  # (optional)
  dutch: 0                         # (optional)

**Comment by pippyn** [comment]
Does it work if you remove the suffix option?

**Comment by CrisRijsdijk** [comment]
Ok, sometimes things are to easy.
Sorry for taking up your time.

**Comment by pippyn** [comment]
no worries!
