### ISSUE TITLE
Add collector: Intradura

### ISSUE THREAD

**Issue by Sipozove** [pippyn/Home-Assistant-Sensor-Afvalbeheer#343]
Hi,
Do you think you could add Intradura to the waste collectors?
https://www.intradura.be/index.php/nl/inzameling-asse

It covers 19 gemeenten (mine is 1730 Asse)
https://www.intradura.be/index.php/nl/kies-jouw-gemeente-of-stad

Thanks!

**Comment by pippyn** [comment]
RecycleApp is already supported
