### ISSUE TITLE
Cranendonck PMD not working

### ISSUE THREAD

**Issue by posixx** [pippyn/Home-Assistant-Sensor-Afvalbeheer#35]
I cannot get the PMD data working for Cranendonck. Somehow it's not recognised. It;'s in the rest data: id:1 and title "Plastic en blik/drankkarton'

Can you take a look to fix?

**Comment by pippyn** [comment]
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/27

try PBD (not PMD)
