### ISSUE TITLE
Upcoming sensor entity name should not depend on language config

### ISSUE THREAD

**Issue by kaosmagix** [pippyn/Home-Assistant-Sensor-Afvalbeheer#350]
The name of the 2 upcoming sensors created by config option upcomingsensor: 1 are now depending on the dutch: 0/1 config setting. The 2 entities should have a fixed name as changing the dutch: 0/1 config setting now breaks dashboards, scripts and automations.

This is what happens now:

upcomingsensor: 1
dutch: 0

creates 2 sensors:
sensor.gad_today
sensor.gad_tomorrow

Changing the config settings to 

upcomingsensor: 1
dutch: 1

creates 2 new sensors (and the existing 2 are no longer updated, status unavailable):
sensor.gad_vandaag
sensor.gad_morgen

**Comment by awolkers** [comment]
Agree, names of entities and there values should not intertwine

**Comment by pippyn** [comment]
I totally agree. However changing this will be a breaking change for so many users.
So this will have to wait until (if ever) we have a large code rewrite with multiple breaking changes.
I'm not willing to annoy users with this change now. I hope you understand.
