### ISSUE TITLE
Invalid response from server for accessToken

### ISSUE THREAD

**Issue by stefdewilde** [pippyn/Home-Assistant-Sensor-Afvalbeheer#351]
This error originated from a custom integration.

Logger: custom_components.afvalbeheer.API
Source: custom_components/afvalbeheer/API.py:824
Integration: Afvalbeheer (documentation)
First occurred: 17:29:16 (1 occurrences)
Last logged: 17:29:16

Invalid response from server for accessToken

I'm getting this error after updating to the latest version.

**Comment by pippyn** [comment]
Could you elaborate? What is your sensor config? Does the website of the waste collector work for your address?

**Comment by clayhill** [comment]
I got the same error for RecycleApp.

**Comment by FredericMa** [comment]
I'm seeing the same error. I'm also using RecycleApp.

**Comment by pippyn** [comment]
Are you using the latest version of the sensor?

**Comment by stefdewilde** [comment]
> Are you using the latest version of the sensor?

yes, i'm on the latest release.

**Comment by pippyn** [comment]
I just released a fix in v5.0.8

**Comment by stefdewilde** [comment]
> I just released a fix in v5.0.8

Yes, now it's fixed!

**Comment by clayhill** [comment]
@pippyn thanks a lot for the swift response! Just in time to put my garbage out tomorrow :slightly_smiling_face:

**Comment by pippyn** [comment]
Can this issue be closed?

**Comment by stefdewilde** [comment]
> Can this issue be closed?

Done!
