### ISSUE TITLE
Add glas to RecycleApp

### ISSUE THREAD

**Issue by goessensj** [pippyn/Home-Assistant-Sensor-Afvalbeheer#352]
Currently RecycleApp is not supporting glas collection.
The native app reports when glas collection is scheduled.

**Comment by pippyn** [comment]
What does the option [`printwastetypes`](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions) say?
What is your config of the sensor?

**Comment by goessensj** [comment]
When i added glas as an option, the integration became unavailable. I restarted because i added printwastetypes to check and the afvalbeheer now works and show glas.
It seems i was too fast to open an issue.
