### ISSUE TITLE
RecycleApp accesstoken

### ISSUE THREAD

**Issue by krisdep** [pippyn/Home-Assistant-Sensor-Afvalbeheer#354]
Today I restarted home assistant. The afvalbeheer sensors have value "unknown". Here is the error log:

```
This error originated from a custom integration.

Logger: custom_components.afvalbeheer.API
Source: custom_components/afvalbeheer/API.py:824
Integration: Afvalbeheer (documentation)
First occurred: 15:57:29 (1 occurrences)
Last logged: 15:57:29

Invalid response from server for accessToken

```

It might be related with the latest release? -> [FIX: Update RecycleApp token](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/releases/tag/v5.0.8)

**Comment by pippyn** [comment]
What version of the sensor are you using? v5.0.8?

**Comment by krisdep** [comment]
My bad. I thought v5.0.8 was already installed. But it wasn't the case. Sorry for the false positive.
Thanks for this integration btw!
