### ISSUE TITLE
Dates "Unknown" after installing 2022.11

### ISSUE THREAD

**Issue by pjannink** [pippyn/Home-Assistant-Sensor-Afvalbeheer#355]
After installing to HA 2022.11, I noticed that the next dates for garbage-collection by Spaarnelanden are now Unknown.

**Comment by pippyn** [comment]
Did it work before updating to 2022.11?
What is your config of the sensor?
Does the website of Spaarnelanden give the correct info?
Do you have an address for me to test with?

**Comment by pjannink** [comment]
Hi 

 

 

Yes, it did work with 2022.10.5

Config:



 

The website op Spaarnelanden shows the correct information: 



 

Address can be seen in the config: 2012KJ64

 

Regards and thx for looking into this!

 

 

Paul 

 

 

Van: Pippyn ***@***.***> 
Verzonden: donderdag 3 november 2022 09:23
Aan: pippyn/Home-Assistant-Sensor-Afvalbeheer ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pippyn/Home-Assistant-Sensor-Afvalbeheer] Dates "Unknown" after installing 2022.11 (Issue #355)

 

Did it work before updating to 2022.11?
What is your config of the sensor?
Does the website of Spaarnelanden give the correct info?
Do you have an address for me to test with?

**Comment by pippyn** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/7591990/199677954-9132aac8-cef8-42cd-b9c5-1e50ba273836.png)
Do you have any errors in the log?

**Comment by pjannink** [comment]
Hi 

 

It must have been caused by the initial restart of HA after the 2022.11 upgrade, as another restart did the trick. Issue resolved.

Thanks for the quick replies!

 

Paul

 

Van: Pippyn ***@***.***> 
Verzonden: donderdag 3 november 2022 09:41
Aan: pippyn/Home-Assistant-Sensor-Afvalbeheer ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pippyn/Home-Assistant-Sensor-Afvalbeheer] Dates "Unknown" after installing 2022.11 (Issue #355)

 

Works for me:
 <https://user-images.githubusercontent.com/7591990/199677954-9132aac8-cef8-42cd-b9c5-1e50ba273836.png> 
Do you have any errors in the log?
