### ISSUE TITLE
no week day on paper sensor

### ISSUE THREAD

**Issue by luckyzor** [pippyn/Home-Assistant-Sensor-Afvalbeheer#359]
Hello, in the paper sensor there are no week day like the other sensors:

![image](https://user-images.githubusercontent.com/31155573/203058347-8b9c71ec-f42a-4423-b0d7-3fadae297160.png)

**Comment by pippyn** [comment]
Use the option [Always show day](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#always-show-day) if you want that:

**Comment by luckyzor** [comment]
perfect, thank you :)
