### ISSUE TITLE
Documentation: Add "kerstbomen" as possible fraction type

### ISSUE THREAD

**Issue by kaosmagix** [pippyn/Home-Assistant-Sensor-Afvalbeheer#36]
A little bit late, but I found you can actually retrieve the date for the fraction "kerstbomen" (with GAD at least). So you might add that to the possible list of fraction types. (it currently actually retrieves 5-jan-2021 for me).

```
resources:
  - kerstbomen

```

**Comment by pippyn** [comment]
I didn't work for you? Or just a question to add this to the docs?

**Comment by kaosmagix** [comment]
> I didn't work for you? Or just a question to add this to the docs?

It works perfectly. Just a request to update the docs to include the fraction type for other users

**Comment by pippyn** [comment]
There are a lot of special waste types. Because every waste collector can name their fractions the way they want. I don't think it would be wise to list them all. Maybe I will add a line in the readme to explain that all fractions (i.e. recourses) are supported even though they are not all listed.
