### ISSUE TITLE
add IOK to the list of wastecollecters pls.

### ISSUE THREAD

**Issue by TimmieVL** [pippyn/Home-Assistant-Sensor-Afvalbeheer#360]
ad IOK to the list of wastecollectors pls.
https://www.iok.be/afvalkalender

**Comment by TimmieVL** [comment]
Meerhout 2450Kanaalstraat 7Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Pippyn ***@***.***> Datum: 2/12/2022  16:14  (GMT+01:00) Aan: pippyn/Home-Assistant-Sensor-Afvalbeheer ***@***.***> Cc: TimmieVL ***@***.***>, Author ***@***.***> Onderwerp: Re: [pippyn/Home-Assistant-Sensor-Afvalbeheer] add IOK to the list of wastecollecters pls. (Issue #360) 
Do you have an address for me to test with?

**Comment by pippyn** [comment]
You can use `RecycleApp` as a wastecollector and that should work.

**Comment by TimmieVL** [comment]
Cool will test it laterVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Pippyn ***@***.***> Datum: 2/12/2022  16:36  (GMT+01:00) Aan: pippyn/Home-Assistant-Sensor-Afvalbeheer ***@***.***> Cc: TimmieVL ***@***.***>, Author ***@***.***> Onderwerp: Re: [pippyn/Home-Assistant-Sensor-Afvalbeheer] add IOK to the list of wastecollecters pls. (Issue #360) 
You can use RecycleApp as a wastecollector and that should work.
