### ISSUE TITLE
DAR - Sensors not working

### ISSUE THREAD

**Issue by stijnhub** [pippyn/Home-Assistant-Sensor-Afvalbeheer#361]
Updated every thing and currently running v5.0.10 trough HACS.
But my sensors voor "vandaag" en "morgen" stays unavailable.

Is there something wrong with my config?

![DAR 1](https://user-images.githubusercontent.com/64000075/204255440-e57ce5f5-666c-460f-88e7-74e6dacf5fb5.png)
![Dar 2](https://user-images.githubusercontent.com/64000075/204255441-a2104505-3f9e-4154-8ea6-37d604f1cb0f.png)

**Comment by pippyn** [comment]
They were renamed to be more consistent with the other sensors.
Use the english translation. `Today` and `Tomorrow`

**Comment by stijnhub** [comment]
> They were renamed to be more consistent with the other sensors. Use the english translation. `Today` and `Tomorrow`

Missed that i am so sorry!
