### ISSUE TITLE
Adding deafvalapp.nl

### ISSUE THREAD

**Issue by supergroover** [pippyn/Home-Assistant-Sensor-Afvalbeheer#37]
Is it possible to add deafvalapp.nl?
they don't really have an api, data can be retrieved from:
http://dataservice.deafvalapp.nl/dataservice/DataServiceServlet?service=OPHAALSCHEMA&land=NL&postcode=6658GT&straatId=0&huisnr=65

**Comment by pippyn** [comment]
No sorry this component uses just one api. You are free to adjust my code for your needs though.
