### ISSUE TITLE
feature requiest: include sensor to track cleaning

### ISSUE THREAD

**Issue by DvdEnde** [pippyn/Home-Assistant-Sensor-Afvalbeheer#370]
The integration works just great and I would like to add a sensor that would enable notification of the carbage can cleaning week. The cleaning company provides a list of weeknumbers of each kind of trash can. From this array of weeknumbers is would be nice when a sensor receives a value 'on' to allow highlighting this in the dashboard.

**Comment by pippyn** [comment]
What waste collector are you using?
Do you have an address for me to test with?

**Comment by pippyn** [comment]
The API response does not include the cleaning days, so I won't be able to include that info in a sensor.
