### ISSUE TITLE
GAD not working?

### ISSUE THREAD

**Issue by inijman** [pippyn/Home-Assistant-Sensor-Afvalbeheer#372]
HI, I'm struggling to get this to work with GAD service (for 1276HS 4). From the log I cannot see any action (or I'm looking in the wrong place), but I get a single entity (showing 'notifying') and no sensors for this...

As I had never any waste plugin working with GAD, it seems an issue on their side (no rest response anymore?), but then it should be removed from the options. And I would love to hear an alternative approach on getting this to work...

**Comment by inijman** [comment]
apparently takes a long time to populate.. and is case sensitive for 'RESTAFVAL' which stops the sensors.

But now it works!

**Comment by pippyn** [comment]
I'm glad it's working!
