### ISSUE TITLE
ACV doesn’t show pickups since today

### ISSUE THREAD

**Issue by Jorikay** [pippyn/Home-Assistant-Sensor-Afvalbeheer#373]
Starting today, I do not get updates for ACV anymore. It looks like the sensor doesn’t receive updates anymore.

today PMD is picked up, but HA does show “unknown” for the sensor, although it seems to have been populated earlier.

**Comment by pippyn** [comment]
Does the kalendar work on the ACV website?

**Comment by Jorikay** [comment]
https://acv-afvalkalender.nl/ does work, as well does the app.

**Comment by pippyn** [comment]
Can you DM me an address in your neighborhood on the HA forum? Then I can do some tests

**Comment by Hartger87** [comment]
First of all, I'm very pleased to use your addon!

I encounter the same problem, I noticed that my wastecollector RMD uses an other calender.
Can this be the cause?

**Comment by pippyn** [comment]
@Hartger87 Do you mean RMN? Because I don't know what RMD is?
If so, please open a new issue as that is not the same as ACV.
Don't forget to mention your config, any errors in your log and a address in your area.

**Comment by Jorikay** [comment]
Just to update on ACV, this is still not working, even after a full reinstall. I have no clue at this point.

**Comment by pippyn** [comment]
Because your config is working on other systems. It has to be either an issue with your HA install or a rate limiting issue.
You could try and set the [update interval](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#update-interval) to 24 and wait a couple of days.
