### ISSUE TITLE
Adding Assen

### ISSUE THREAD

**Issue by wyyagh** [pippyn/Home-Assistant-Sensor-Afvalbeheer#375]
Hi,
Graag Assen toevoegen
Is dat mogelijk?

**Comment by pippyn** [comment]
Assen uses Mijnafvalwijzer, which is already supported.

**Comment by wyyagh** [comment]
OK
I have used the singel instance code in de configuration.yaml but stil getting no results.
Wat I am doing wrong?
afvalbeheer:
    wastecollector: Blink
    resources:
    - restafval
    - gft
    - papier
    - pmd
    postcode: 9408LJ
    streetnumber: 24
    
    
![afvalbeheer](https://user-images.githubusercontent.com/118002301/214055786-208edacc-3679-4bba-93cc-3a9b28cda926.jpg)

**Comment by Brandweerman** [comment]
Hallo wyyagh, 

Probeer het eens met: **wastecollector: MijnAfvalwijzer**

afvalbeheer:
  wastecollector: MijnAfvalwijzer
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 9408LJ
  streetnumber: 24
  upcomingsensor: 1
  dateformat: '%A %-d %B'
  dateonly: 0
  name: ""
  nameprefix: 0
  builtiniconsnew: 1
  dutch: 1

**Comment by wyyagh** [comment]
Dag Brandweerman
Nu krijg ik in de Yammer configuration check het onderstaande melding

Integration error: nameprefix - Integration 'nameprefix' not found.
Integration error: resources - Integration 'resources' not found.
Integration error: builtiniconsnew - Integration 'builtiniconsnew' not found.
Integration error: name - Integration 'name' not found.
Integration error: wastecollector - Integration 'wastecollector' not found.
Integration error: streetnumber - Integration 'streetnumber' not found.
Integration error: dutch - Integration 'dutch' not found.
Integration error: postcode - Integration 'postcode' not found.
Integration error: dateonly - Integration 'dateonly' not found.
Integration error: upcomingsensor - Integration 'upcomingsensor' not found.
Integration error: dateformat - Integration 'dateformat' not found.

**Comment by wyyagh** [comment]
dom van mij.
Kopiëren en plakken in de studio code server ging ergens niet goed.
De code handmatig intikken dan ging het goed.
Ophaal datums zie ik nu in beeld
Bedankt

**Comment by MWolthuis** [comment]
Good evening,
Is it possible to review Assen again? It start using the platform from 21 South next year. 
It is now listed here: [https://21burgerportaal.mendixcloud.com/](url) 
So maybe it is using the same API as RMN and BAR?
