### ISSUE TITLE
Feature Request: sort entries on date

### ISSUE THREAD

**Issue by menloperk** [pippyn/Home-Assistant-Sensor-Afvalbeheer#377]
Can we have the entries sorted by their upcoming dates? So the first upcoming 'event' is at the top?

**Comment by s-edel** [comment]
> Can we have the entries sorted by their upcoming dates? So the first upcoming 'event' is at the top?

I installed this sensor, and after the first date passed, I also noticed that the list does not sort by next date. So this feature request would be a more than welcome addition.

**Comment by pippyn** [comment]
This is not so much a integration issue, but more a dashboard issue.
But yes there are multiple ways to do that.
You could sort by the attribute `Sort date` of the sensor. (look at issue [#33](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/33) to get you started)

**Comment by menloperk** [comment]
Thanks for the tip!
Switching to 'Auto Entities' with the Sort option fixed it (also not aware there was the 'Sort-date' attribute)!

**Comment by pippyn** [comment]
No problem! Can I close this issue?

**Comment by menloperk** [comment]
For me you can!

**Comment by kooijman599** [comment]
Really don't get it. In my dashboard the option to sort by attribute doesn't work. Can you please help me out?

Configuration:
`afvalbeheer:
  wastecollector: MijnAfvalwijzer
  resources:
    - gft
    - papier
    - pmd
  postcode: 8256JL
  streetnumber: 6
  upcomingsensor: 1                # (optional)
  dateformat: '%d-%m-%Y'              # (optional)
  dateonly: 1                      # (optional)
  name: ""                         # (optional)
  nameprefix: 1                    # (optional)
  builtinicons: 1
  builtiniconsnew: 1               # (optional)
  dutch: 1                         # (optional)`

Lovelace:
`type: custom:auto-entities
card:
  type: glance
filter:
  include:
    - entity_id: sensor.mijnafvalwijzer_gft
    - entity_id: sensor.mijnafvalwijzer_pmd
    - entity_id: sensor.mijnafvalwijzer_papier
sort:
  method: attribute
  attribute: Sort-date
  numeric: true`
