### ISSUE TITLE
Namen van maanden onterecht met hoofdletter

### ISSUE THREAD

**Issue by FqfxLSNiKo** [pippyn/Home-Assistant-Sensor-Afvalbeheer#385]
`dateformat: '%d %B'` ("month as locale’s full name") doet niet wat ik zou verwachten omdat namen van maanden (en dagen van de week) in het Nederlands niet met een hoofdletter horen (behalve aan het begin van een zin).

**Comment by Ascathon** [comment]
Dat ligt dan denk ik aan de implementatie van Home Assistant en/of Python.
In de template editor ook met hoofdletter.
![2023-04-14-19_32_28](https://user-images.githubusercontent.com/21990236/232116883-14e1921e-6a4f-4569-9c84-e3a6fa5a878f.png)

**Comment by pippyn** [comment]
No it's definitely my code that causes this issue.
This will be addressed in a upcoming version.

**Comment by Ascathon** [comment]
Haha okay nice one. Then I didn't say a word.

**Comment by pippyn** [comment]
The Dutch month names are changed to lowercase in v5.2.3
