### ISSUE TITLE
Missing GFT information

### ISSUE THREAD

**Issue by larsvdmanden** [pippyn/Home-Assistant-Sensor-Afvalbeheer#386]
Hi!

I try to get the information from the GTF sensor for Purmerend, but it says the information is 'unknown'. The afvalkalender from the city council shows the information, so I think there's something going wrong. Is it possible to get the information about the GFT garbage?

Many thanks in advance!

Kind regards,
Lars

**Comment by pippyn** [comment]
What does the option [printwastetypes: 1](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions) show you?

**Comment by pippyn** [comment]
So you'll need `bio-afval` as a resource, not `gft`

**Comment by larsvdmanden** [comment]
Ah! Sorry I'm quite new in Home Assistant. It's working now, thank you!
