### ISSUE TITLE
sensor.meerlanden_garbage_morgen (and sensor.meerlanden_garbage_vandaag) doesn't work

### ISSUE THREAD

**Issue by iamkarlson** [pippyn/Home-Assistant-Sensor-Afvalbeheer#39]
Hi,
Thank you for the plugin! It's really awesome to have garbage calendar in HA rather than open shitty apps from garbage collectors. However, these particular sensors stopped working recently (like a few months ago). Could you please have a look at why it returns unknown every time? All other sensors seem to be working fine.

**Comment by pippyn** [comment]
Sure! Will need some information though.. what is your config like. (Please change your personal information for something else, but make sure the information is a real address)

**Comment by iamkarlson** [comment]
Hi, I've changed my address information but except this everything else remains unchanged:

```- platform: afvalbeheer
  wastecollector: Meerlanden
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 11XXXX
  streetnumber: xx
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  name: "Garbage"
  nameprefix: 1```

Do you need a real house number and postcode?

**Comment by pippyn** [comment]
> Do you need a real house number and postcode?

yes please

**Comment by iamkarlson** [comment]
@pippyn Please check 1161AS and 24. I'll edit this comment and delete it from the history but you must be able to see it from the notification on the email.

**Comment by pippyn** [comment]
I can't for some reason. Please DM me

**Comment by iamkarlson** [comment]
@pippyn dm what? do you realize that there's no way to send you a private message? on github you don't have any contacts, all the commits are covered with github no-reply addresses and there's no built-in chat system in github in general except for issues.

**Comment by pippyn** [comment]
On HA forum i mean ;)

**Comment by iamkarlson** [comment]
Solution:

And the only 4 fractions listed by meerlanden for your address are:

Restafval
GFT
Textiel
Takken
So your config should be (confirmed working):

```
- platform: afvalbeheer
  wastecollector: Meerlanden
  resources:
    - restafval
    - gft
    - takken
    - textiel
  postcode: 1111XX
  streetnumber: 11
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  name: "Garbage"
  nameprefix: 1```
