### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by Kareltje1980** [pippyn/Home-Assistant-Sensor-Afvalbeheer#391]
Ik was nu even aan het zoeken hoe ik nu deze sensor kon toevoegen. Zoeken op afval leverde wel wat op, maar niet wat ik zocht. 
Misschien als tip erbij zetten dat je het beste kan zoeken op papier/gft oid.

**Comment by pippyn** [comment]
Please english only.

Could you please elaborate what you mean? Searching where? In HACS or Google?

**Comment by pippyn** [comment]
Can this issue be closed?
