### ISSUE TITLE
Restafval sensor not working for BAR

### ISSUE THREAD

**Issue by harisosmancevic** [pippyn/Home-Assistant-Sensor-Afvalbeheer#392]
The restafval sensor is not working for BAR, example zip: 2983AZ 1.

**Comment by pippyn** [comment]
I accidentally mapped PMD-Rest to "Kerstbomen" 😅

Fixed in v5.2.2

**Comment by pippyn** [comment]
Can you elaborate? What's not working?

**Comment by harisosmancevic** [comment]
Gft and papier are giving an date, restafval just says unkown..

**Comment by pippyn** [comment]
Did you check the print available fractions option?

**Comment by harisosmancevic** [comment]
Ah, i had to use pmd-restafval, i was using this config for 2 years or something, did not know it was changed, issue is solved!

**Comment by pippyn** [comment]
Yes BAR changed their API. So all the fractions changed. I'm glad it's working now!

**Comment by pippyn** [comment]
Can we close this issue?

**Comment by harisosmancevic** [comment]
Yes! Still some small things, for gft is show for example woensdag, 12-04-2023, and pmd-restafval just 19-04-2023, also no icons, but i am happy that the sensornis working!

**Comment by pippyn** [comment]
The new api they are using doesn't have the icons I'm afraid
