### ISSUE TITLE
Sensors always returning Unknown for afvalstoffendienstkalender

### ISSUE THREAD

**Issue by cstegeman** [pippyn/Home-Assistant-Sensor-Afvalbeheer#393]
Since April 8 the sensors always return "Unknown" for wastecollector "afvalstoffendienstkalender". I am on the latest version of the integration: 5.2.2

I looked in the logs, but couldn't find anything useful. I know this isn't much in giving context, so if you need more info please let me know.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/1582500/230767654-b89c41f5-1440-4c75-a602-6d8da44608a3.png">

**Comment by warptozero** [comment]
api.afvalstoffendienstkalender.nl returns an expired certificate as happened last year around the same time: https://github.com/xirixiz/homeassistant-afvalwijzer/issues/183.

**Comment by cstegeman** [comment]
In the meantime, it's returning correct info, and besides that the issue was not code related, so closing the issue, thanks for taking the time to provide an answer 👍
