### ISSUE TITLE
Ondersteuning mijnafvalzaken

### ISSUE THREAD

**Issue by GraafIvar** [pippyn/Home-Assistant-Sensor-Afvalbeheer#397]
Mijn gemeente heeft een eigen app geïntroduceerd, is het mogelijk dat deze app ook hierop beschikbaar wordt? De lay-out van de app is volgens mij het zelfde als de lay-out van [Cure](https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/master/example.png) , die op de[hoofdpagina ](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer) a is te vinden 
https://mijnafvalzaken.nl/

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by GraafIvar** [comment]
1902 CA 1

Met vriendelijke groet,

Ivar de Graaf

________________________________
Van: Pippyn ***@***.***>
Verzonden: maandag, mei 8, 2023 8:39 AM
Aan: pippyn/Home-Assistant-Sensor-Afvalbeheer ***@***.***>
CC: Ivar de Graaf ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pippyn/Home-Assistant-Sensor-Afvalbeheer] Ondersteuning mijnafvalzaken (Issue #397)


Do you have an address for me to test with?

**Comment by pippyn** [comment]
Added in v5.2.5
