### ISSUE TITLE
Adhere to new HA naming, introduced in version 0.88

### ISSUE THREAD

**Issue by bouwew** [pippyn/Home-Assistant-Sensor-Afvalbeheer#4]
Hi Pippyn,

FYI, the sensors should now be in its own directory, with the name sensor.py

So, in my case:
../custom_components/groningen-afvalbeheer/sensor.py

**Comment by pippyn** [comment]
Changed the docs to include 2 instructions; 
- pre HA 88 
- HA 88 and later
