### ISSUE TITLE
Waarlanden doenst show restafval

### ISSUE THREAD

**Issue by matrover** [pippyn/Home-Assistant-Sensor-Afvalbeheer#402]
![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/18408057/c95ef3a0-7bfe-4a0c-809f-91cdec00d1be)

test address: 
4205GD, 31

Thanks in advance!

**Comment by pippyn** [comment]
There is no restafval for this address..
![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/7591990/b3ff4ab0-ced8-4470-a194-af72f9f75857)

**Comment by matrover** [comment]
that was quick, thats wierd i have a grey bin. 

but yeah if the data shows none, its not gonna show up :) 

How to test this myself?

**Comment by pippyn** [comment]
I just looked at the [Waarlanden website](https://www.waardlanden.nl/particulieren/afval-en-grondstoffen/afvalkalender).
The sensor uses the same API.

I would contact Waarlanden to ask why the grey bin is not included in the calendar.

**Comment by pippyn** [comment]
As this is not an issue with the sensor, but with the waste collector, can we close it?

**Comment by matrover** [comment]
That is correct, closing
