### ISSUE TITLE
Afvalwijzer

### ISSUE THREAD

**Issue by roosdennis** [pippyn/Home-Assistant-Sensor-Afvalbeheer#408]
Good Evening

Are you,, by any chance, able to add the following?

https://www.mijnafvalwijzer.nl/

9207BX (with a random housenumber

Thanks in advance <3

**Comment by pippyn** [comment]
MijnAfvalwijzer is already supported.

But I can't find any housenumber that works with postal code 9207BX on the website of mijnafvalwijzer.nl
Can you give me an example that works?
