### ISSUE TITLE
Mijnafvalwijzer / type papier-pmd

### ISSUE THREAD

**Issue by qwark1** [pippyn/Home-Assistant-Sensor-Afvalbeheer#409]
Hi,

for my city (Goirle) I get the type papier-pmd from Mijnafvalwijzer for our duobak. Is it possible to add this and map it to the PMD icon?

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by qwark1** [comment]
Sure, a random address in my city that works is 5133AD, house number 27 - see August 29th

**Comment by qwark1** [comment]
Thanks. BTW created sensors are currently named sensor.GFT; sensor.restafval and sensor.papier_pmd without the name of the wastecollector - is that intentionally or also caused by this mismatch?

**Comment by pippyn** [comment]
You can set `nameprefix: 1` to have the collectors name included in the ID.

**Comment by pippyn** [comment]
Icon fix released in v5.2.8
