### ISSUE TITLE
Twente Milieu not working?

### ISSUE THREAD

**Issue by Apacalipto** [pippyn/Home-Assistant-Sensor-Afvalbeheer#410]
Hi, Thank you for creating this integration :)!

The only problem is, i can't get it to work.

The entities all have status unkown.

When i check the logs i get:

Logger: homeassistant.helpers.entity
Source: custom_components/afvalbeheer/API.py:158
Integration: Afvalbeheer ([documentation](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer))
First occurred: 10:56:36 PM (378 occurrences)
Last logged: 11:23:06 PM

Update for sensor.twente_milieu_papier fails
Update for sensor.twente_milieu_pmd fails
Update for sensor.twente_milieu_vandaag fails
Update for sensor.twente_milieu_morgen fails
Update for sensor.twente_milieu_eerst_volgende fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 940, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalbeheer/sensor.py", line 128, in update
    collection = self.data.collections.get_first_upcoming_by_type(self.waste_type)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalbeheer/API.py", line 158, in collections
    return self.collector.collections
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'collections'

Hope you can help me trouble shoot:

configuration.yaml

afvalbeheer:
  wastecollector: Twente Milieu
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 7602AJ
  streetnumber: 84
  upcomingsensor: 1                # (optional)
  dateformat: '%d-%m-%Y'           # (optional)
  dateonly: 0                      # (optional)
  nameprefix: 1                    # (optional)
  builtinicons: 1                  # (optional)
  dutch: 1                         # (optional)
  
 * Random address neighbourhood generated.

**Comment by pippyn** [comment]
When I check the website of twente milieu, I get the following message:
![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/7591990/a995c7c5-bcc3-40db-8c50-7bf1c0081c93)

**Comment by Apacalipto** [comment]
Yes, its the local supermarket.

IL just give a house address for reference
7602CE house number: 42 is in my street

This one works on the Twente Milieu website.

**Comment by Thomish** [comment]
It worked with me after changing the name for the waste collector.
afvalbeheer:
  wastecollector: twentemilieu

**Comment by pippyn** [comment]
Ahh I missed that! Yes @Thomish is correct, you should use `twentemilieu` not `Twente Milieu`

**Comment by Apacalipto** [comment]
Yes, this worked for me to! Maybe change the name in the documentation. :). But i also could have thought about it myself.

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/23662152/7f94ea1c-5cfa-4878-8b09-50e8effed394)

Works!
