### ISSUE TITLE
ZRD afvalkalender

### ISSUE THREAD

**Issue by joosttt** [pippyn/Home-Assistant-Sensor-Afvalbeheer#411]
ZRD afvalkalender werkt helaas niet meer.
Zo te zien is de pagina: https://www.zrd.nl/afvalkalender.htm niet meer bereikbaar. 
en verplaatst naar: https://www.zrd.nl/wanneer. 
Bestaat de mogelijkheid om dit weer werkend te krijgen?

**Comment by joosttt** [comment]
in the log i get error: 
Logger: custom_components.afvalbeheer.API
Source: custom_components/afvalbeheer/API.py:143
Integration: Afvalbeheer ([documentation](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer))
First occurred: 10:23:44 (1 occurrences)
Last logged: 10:23:44
Error occurred while fetching data: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

There is nothing change in my config file:
sensor:
  - platform: afvalbeheer
    wastecollector: ZRD
    resources:
    - restafval
    - gft
    - papier
    - pmd
    postcode: 4691DB
    streetnumber: 19
    upcomingsensor: 1
    dutch: 1

**Comment by pippyn** [comment]
Fixed in v5.2.8

**Comment by pippyn** [comment]
@QLVR-IT I also notified the creator of the afvalwijzer integration @xirixiz to the change in the API

**Comment by joosttt** [comment]
It works again! Thanks for your quick solution!

**Comment by pippyn** [comment]
Can we close this issue?
