### ISSUE TITLE
Can you please add intradura 

### ISSUE THREAD

**Issue by noureddin212** [pippyn/Home-Assistant-Sensor-Afvalbeheer#417]
It is a waste collector in vlaams Brabant 
Bedankt

**Comment by pippyn** [comment]
I'll have a look. Do you an address for me to test with?

**Comment by pippyn** [comment]
What I see on their site is that they support RecycleApp, which this sensor already supports. Does that work for you?

**Comment by pippyn** [comment]
Did you got it working?

**Comment by noureddin212** [comment]
yes it works thanks
