### ISSUE TITLE
Status krijgt geen updates

### ISSUE THREAD

**Issue by Oli4Rupke** [pippyn/Home-Assistant-Sensor-Afvalbeheer#420]
LS,

mijn yaml file ziet er zo uit

##### Afvalbeheer ##############################################################    
afvalbeheer:
  wastecollector: Cyclus
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: ******
  streetnumber: *
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 0
  dayofweek: 0
  dateobject: 1
  updateinterval: 1
  name: ""
  nameprefix: 1
  builtinicons: 1
  builtiniconsnew: 1
  dutch: 1

En dan kan ik deze kaart maken:

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/131397525/52a1885e-a923-4a80-907f-547c489aae7b)

Echter zoals je ziet blijft status uit en onbekend. Wat doe ik verkeerd?

Ik heb al handmatig de entiteit van off naar on gezet maar deze gaat vanzelf weer naar off.

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/131397525/0a2c8c4f-9ca6-48ef-8852-b68ed61c9ebd)

Ik weet het nu ff niet meer dus alle hulp wordt op prijs gesteld.

**Comment by pippyn** [comment]
HI @Oli4Rupke,

Do you have an address for me to test with?

**Comment by Oli4Rupke** [comment]
2811HA #8 suffix 1 but #8 will do fine I guess

**Comment by Oli4Rupke** [comment]
And should the date immidiately appear or do I have to wait for the system to update for 12 hours interval? Obviously not because on your side it works fine within a matter of minutes right?

**Comment by pippyn** [comment]
Depending on your system it should be populated within a few minutes after reboot of HA.

**Comment by Oli4Rupke** [comment]
iN MY CALENDAR i CAN NOW SEE THE information.

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/131397525/b272fc54-9c53-4f1b-b096-7fc0934c77e6)

However nog in my Lovelace card...................... yet......

But haven't been this far so far ;-)

**Comment by Oli4Rupke** [comment]
YESSSSSSS!!!! it works, except for the entity 'volgende' (next)

**Comment by pippyn** [comment]
You're welcome! I'm glad you got it working.
Can we close this issue?
