### ISSUE TITLE
Krijg het niet geïnstalleerd in HA?

### ISSUE THREAD

**Issue by Pleeriezer** [pippyn/Home-Assistant-Sensor-Afvalbeheer#422]
Hallo,

Ik heb het via HACS gedownload, ik krijg hem te zien maar kan er verder niets mee?

https://imgur.com/c9JnB1l

https://imgur.com/wIeFeTK

Hij staat ook netjes in de juiste directory : 

https://imgur.com/7vKdjCS

Wat doe ik fout?

**Comment by pippyn** [comment]
Did you add your config and reboot HA?
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#example-configs

**Comment by Pleeriezer** [comment]
Yes I did.

I put in by hand in the config.yaml and I can see them on my dash.

Now I must see how to get a reminder..as an automation..

**Comment by Pleeriezer** [comment]
I have made this for Twente Milieu :  

![Afval4](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/149144892/10ec500c-0514-4c25-8113-2efa0402c14e)

And I am getting this error : 

![Afval5](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/149144892/0dd2ae99-856e-4ebf-88d0-524be4c24a1c)

**Comment by Pleeriezer** [comment]
Hello Pippyn, how can I solve this problem?

Thanks in advance.

**Comment by pippyn** [comment]
remove the space in Twente Milieu, it should be `twentemilieu`

**Comment by Pleeriezer** [comment]
Thnx for the quick reply it is working!
