### ISSUE TITLE
Recycleapp: upcomingsensor not working as from version 5.2.9

### ISSUE THREAD

**Issue by XalaTheShepard** [pippyn/Home-Assistant-Sensor-Afvalbeheer#425]
Dear Pippyn,

Many thanks for your great integration. It is most likely the first HACS integration I have installed when I started with HA some years ago. 

Since the update to version 5.2.9 the sensors for the waste collection today and the waste collection tomorrow are no longer working. 
In the configuration.yaml file, the upcomingsensor has the value 1 instead of the default 0 .

Reverting back to version 5.2.8 solves this issue. 
Possibly the upcomingsensor in the configuration.yaml file is ignored in the latest update, since no errors were returned in the logs. 

Thanks for looking into this issue. 

Kind regards,

**Comment by pippyn** [comment]
What is your config?

**Comment by pippyn** [comment]
This is a bug and is fixed in v5.2.10, now the name is dependent on whether or not you set the setting `dutch`
