### ISSUE TITLE
limburg.NET stopped working since yesterday

### ISSUE THREAD

**Issue by KurtKeunen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#428]
Hi, i just noticed that limburg.net stopped working for afvalbeheer 
![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/4628973/02e98e90-8754-45d8-8d03-cf0070ad6a9e)

the config i use: 

- platform: afvalbeheer
  wastecollector: Limburg.NET
  postcode: 0000 #redacted ;)
  streetnumber: 1 #redacted ;)
  streetname: "straat" #redacted ;)
  cityname: "stad" #redacted ;)
  printwastetypes: 1
  upcomingsensor: 1 # (optional)
  dateformat: "%d-%m-%Y" # (optional)
  dateonly: 0 # (optional)
  name: "Afvalophaling" # (optional)
  nameprefix: 0 # (optional)
  builtinicons: 1
  builtiniconsnew: 1
  disableicons: 0
  dutch: 1 # (optional)
  resources:
    - restafval
    - gft
    - papier
    - pmd

**Comment by pippyn** [comment]
Any errors in your log? Does the calendar on the website of Limburg.net work?

**Comment by KurtKeunen** [comment]
im closing this, their website is down, cyberattack apparently
