### ISSUE TITLE
Limburg.NET. Max retries exceeded 

### ISSUE THREAD

**Issue by kimbo1st** [pippyn/Home-Assistant-Sensor-Afvalbeheer#429]
Since yesterday eveningI have the following error:

`2023-12-13 22:47:33.872 ERROR (MainThread) [custom_components.afvalbeheer.API] Error occurred while fetching data: ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='limburg.net', port=443): Max retries exceeded with url: /api-proxy/public/afval-kalender/gemeenten/search?query=Ham (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a11441050>, 'Connection to limburg.net timed out. (connect timeout=None)'))"))`

**Comment by kimbo1st** [comment]
Seems to be down due to a cyberattack.

**Comment by Pieter-Geerts** [comment]
I'm having the Same error. Thanks for the feedback

**Comment by RoelG** [comment]
Their site is down as well :) So must indeed be some attack. Missed putting the glass outside yesterday due to this haha

**Comment by pippyn** [comment]
This sensor uses the same API as their website. So if the website is down the sensor will not work.
Hopefully they'll fix it soon🤞

**Comment by jayjayseal** [comment]
The website is back online
