### ISSUE TITLE
Maximum request exceeded error for Venray

### ISSUE THREAD

**Issue by galaxxy22** [pippyn/Home-Assistant-Sensor-Afvalbeheer#43]
Is it possible to add a interval option? I get the following error (example zipcode + housenumber: 5803BD-1):

Logger: custom_components.afvalbeheer.sensor
First occured: 10:30:24 AM (1 occurences)
Last logged: 10:30:24 AM

Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='afvalkalender.venray.nl', port=443): Max retries exceeded with url: /rest/adressen/5803BD-1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xabe21db0>: Failed to establish a new connection: [Errno 111] Connection refused'))"))

**Comment by pippyn** [comment]
This error only happens (as far as I know) when the the site of the waste collector is down.
