### ISSUE TITLE
Limburg.net onbekend

### ISSUE THREAD

**Issue by stevebaele** [pippyn/Home-Assistant-Sensor-Afvalbeheer#430]
Sinds laatste update krijg ik onbekend als statussen voor de afvalbeheer.  Iemand met een oplossing ?

**Comment by cyrilknops** [comment]
https://www.tvl.be/nieuws/limburg.net-is-tijdelijk-onbereikbaar-door-cyberaanval
Website is nog steeds niet beschikbaar daarom werkt de integratie niet

**Comment by jayjayseal** [comment]
De diensten worden langzaam hersteld
https://www.vrt.be/vrtnws/nl/2023/12/18/limburg-net-kan-geleidelijk-weer-opstarten/

**Comment by jayjayseal** [comment]
The servers are back online and the integration is working again :)
