### ISSUE TITLE
RecycleApp not working + Fix?

### ISSUE THREAD

**Issue by martijndhondt** [pippyn/Home-Assistant-Sensor-Afvalbeheer#432]
Hi

As i saw today my sensors had the state unknown, I noticed in the logs the API was unreachable, as i further investigated the api url in the current API.py there was the `https://api.recycleapp.be/api/app/v1/` and i could not get a correct response from this.

I then checked the developer options on [https://www.recycleapp.be/dashboard](https://www.recycleapp.be/dashboard) after I had entered my address i noticed it was pointing now to  `https://api.fostplus.be/recyclecms/app/v1/`

I changed this manually in API.py on my installation and the sensors are now working again.

I'm a system engineer and not a programmer so I'm not entirely sure this is the correct fix, but it was working for me.

**Comment by jayjayseal** [comment]
The servers seem to be back online now.  I'm seeing the dates again.

**Comment by martijndhondt** [comment]
Yes it is, thank you for the feedback.
