### ISSUE TITLE
Use capitalization in calendar names (Camel case)

### ISSUE THREAD

**Issue by Broekman** [pippyn/Home-Assistant-Sensor-Afvalbeheer#443]
Thanks for the integration, has worked perfectly for years!

Just a little nitpick that drew my attention is that everything in my calendar is Camel case, except for Afvalwijzer which is fully lower case (it hurts my OCD a bit 😅). Possibly also just in general for the names in all parts of the integration, instead of only the calendar.

For example:
gft --> GFT
papier --> Papier
pmd --> PMD
Etc....

Would this be a possibility or is this a design choice?

Thanks!

**Comment by pippyn** [comment]
I'll look into this. I'm not sure what consequences this change will have.

**Comment by pippyn** [comment]
Could you try version v5.3.1?

**Comment by Broekman** [comment]
Hi @pippyn, I will be back from holiday next weekend, I will review it right away then. Thanks!

**Comment by Broekman** [comment]
Looks good on my end, thanks!
