### ISSUE TITLE
Please add Arnhem / Suez

### ISSUE THREAD

**Issue by hansmets** [pippyn/Home-Assistant-Sensor-Afvalbeheer#45]
Hi,

Could you add Arnhem to the code, I did test with this URL that is provided by Suez at https://inzamelwijzer.suez.nl/adres/ .

On one of the sites of gemeente Arnhem this one was provided as alternative to the standard afvalwijzer. The syntax is identical to "Alphen aan de Rijn" so I used that as a template. 

Hans

**Comment by pippyn** [comment]
I will have a look. Do you have an address for me to test with?

**Comment by hansmets** [comment]
Hi,

 

I picked a few random addresses in my neighborhood that do work:

 

Eldense Blauwe 1, 6846HS Arnhem

Meikers 44, 6846HR Arnhem

Fruithoeve 22, 6846JH Arnhem

 

Hans

 

 

 

 

Van: pippyn <notifications@github.com> 
Verzonden: woensdag 11 maart 2020 22:08
Aan: pippyn/Home-Assistant-Sensor-Afvalbeheer <Home-Assistant-Sensor-Afvalbeheer@noreply.github.com>
CC: hansmets <hans.metselaar@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [pippyn/Home-Assistant-Sensor-Afvalbeheer] Please add Arnhem / Suez (#45)

 

I will have a look. Do you have an address for me to test with?

**Comment by pippyn** [comment]
Added in version 2.5.13
