### ISSUE TITLE
Date unknown

### ISSUE THREAD

**Issue by Hoftie** [pippyn/Home-Assistant-Sensor-Afvalbeheer#452]
The collection date is no longer displayed for GFT and PMD. The rest are going well. What could this be?
I am using version v5.2.17
It was still working fine a few days ago. I have not changed anything in the configuration. It is as described.
Please can you fix it.

wastecollector: Waardlanden

![wrong date](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/125030130/0a8afc1c-ec15-4035-84d5-f38ed78f0a51)

**Comment by Hoftie** [comment]
wastecollector: Waardlanden

**Comment by pippyn** [comment]
What is your config?
Do you have an address for me to test with?

**Comment by Hoftie** [comment]
![config](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/125030130/7136607f-fc89-4067-b511-45c239140220)

**Comment by pippyn** [comment]
This address has no collection dates for PMD or GFT..
Look at Waardlanden website: https://www.waardlanden.nl/en/particulieren/afval-en-grondstoffen/afvalkalender

**Comment by Hoftie** [comment]
I see. Thank you! Then I will report it there.
