### ISSUE TITLE
Support for Venlo (venlo.nl)

### ISSUE THREAD

**Issue by jasperdemmers** [pippyn/Home-Assistant-Sensor-Afvalbeheer#457]
Venlo uses the following afval calander: [www.venlo.nl/mijn-afvalkalender](https://www.venlo.nl/mijn-afvalkalender).
An example Postal code is: 5912BZ number 76.
It seems they have [open data](https://gemeenteraad.venlo.nl/api/v2/).
Could this be implemented?

**Comment by pippyn** [comment]
Hi @jasperdemmers,

Their website doesn't have an API exposed. And the open data API doesn't support Waste Collections.
Please request this to be added with your municipality.

You could use a scape integration if you like. Have a look at issue #142
