### ISSUE TITLE
Icons do not display using dark-theme

### ISSUE THREAD

**Issue by Sweepr** [pippyn/Home-Assistant-Sensor-Afvalbeheer#458]
Is it possible to add custom icons, where are the files located?

Using light:

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/2857865/765438d4-e803-4a30-9e46-b648010724e7)

Using dark: 

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/2857865/acc2db3e-cfb0-4af4-b2ef-e1f22817969f)

**Comment by pippyn** [comment]
Sure, in HA you can give any entity a [custom icon](https://www.home-assistant.io/docs/configuration/customizing-devices/#entity_picture). There is no file location for the icons used by this integration. They are stored as a base64 string in the code.

**Comment by Sweepr** [comment]
> Sure, in HA you can give any entity a [custom icon](https://www.home-assistant.io/docs/configuration/customizing-devices/#entity_picture). There is no file location for the icons used by this integration. They are stored as a base64 string in the code.

Thank you, i will have a look at that.
