### ISSUE TITLE
States get unknown

### ISSUE THREAD

**Issue by Gavergracht** [pippyn/Home-Assistant-Sensor-Afvalbeheer#459]
all my states get "unknown"

This error originated from a custom integration.

Logger: custom_components.afvalbeheer.API
Source: custom_components/afvalbeheer/API.py:1045
Integration: Afvalbeheer (documentation)
First occurred: 14:40:16 (1 occurrences)
Last logged: 14:40:16

Invalid response from server for accessToken

**Comment by pippyn** [comment]
What is your config? And please add an address in your neighborhood or me to test with?

**Comment by Gavergracht** [comment]
I redownloaded it like it was told on the home assistant forum. It is ok now. it can be closed
