### ISSUE TITLE
Paper and PMD changed for PreZero

### ISSUE THREAD

**Issue by biocoder-frodo** [pippyn/Home-Assistant-Sensor-Afvalbeheer#460]
Since I am a user of https://github.com/xirixiz/homeassistant-afvalwijzer, I noticed i stopped getting updates for the waste collection dates for PMD and paper. I filed a PR [there](https://github.com/xirixiz/homeassistant-afvalwijzer/pull/272) to fix the issue for me.

**Comment by pippyn** [comment]
Thank you, but that is not needed for this sensor. All fractions are supported by default.
