### ISSUE TITLE
Adding option "dutch:1" kills "upcoming" sensors

### ISSUE THREAD

**Issue by jjvandenberg** [pippyn/Home-Assistant-Sensor-Afvalbeheer#461]
Hi,

when adding the option for dutch-names-for-weekdays , the upcoming sensors are killed. See screen shots below: 

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/66120846/a3526bad-0421-4293-852e-29a7f421dec7)
![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/66120846/5db76442-03fc-475e-855c-453c99b42947)

With "dutch:1" enabled:

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/66120846/f5fe9648-e2b1-4d6c-a4b9-1c64bcd61f92)
![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/66120846/941b5518-4d9a-4d09-9e96-ce91d5d22639)

**Comment by jjvandenberg** [comment]
Found it: the "Dutch" option not only translates the names of weekdays, but also the names of the sensors !
That's not expected nor documented ;-)

**Comment by pippyn** [comment]
You are correct. I'll update the docs accordingly
