### ISSUE TITLE
Data afval ophalingen naar Onbekend/None

### ISSUE THREAD

**Issue by wannetk** [pippyn/Home-Assistant-Sensor-Afvalbeheer#462]
Sinds enkele dagen zijn de data niet meer ingevuld voor de afval ophalingen.
Behalve enkele updates en een restart heb ik geen wijzigingen gedaan, werkt al lange tijd prima

Enig idee hoe dit kan opgelost worden?

![Screenshot_20240211_215209_Home Assistant](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/159779920/0f6ffb3c-9277-4f65-9df9-39e847adaba5)
![Screenshot_20240212_124801_Home Assistant](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/159779920/205fd498-b3ff-4974-870b-d6ac223c9a45)

**Comment by jjvandenberg** [comment]
kloppen de namen van je entiteiten nog wel ?
te checken via developer tools / states.

**Comment by wannetk** [comment]
Solved after updates and restarts
