### ISSUE TITLE
Disable Afvalbeheer notification as administrator

### ISSUE THREAD

**Issue by Pammetje** [pippyn/Home-Assistant-Sensor-Afvalbeheer#465]
Every time I restart HA I get a notification from Afvalbeheer (as administrator using de website) I there a way to disable that, it's very annoying

**Comment by pippyn** [comment]
What notification?
What is your config?

**Comment by Pammetje** [comment]
I think I have a default /standard config

afvalbeheer:
  wastecollector: XXX
  resources:
    - gft
  postcode: xxxxXX
  streetnumber: xx
  upcomingsensor: 3
  printwastetypes: 1
  dateonly: 1
  dateformat: '%d-%m-%Y'

![2](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/16224006/dc540acd-24e3-4374-9065-e621043bf73c)
![1](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/16224006/d91b4b22-c85e-4e8b-92e8-8e40b4be7a27)

**Comment by pippyn** [comment]
Remove `printwastetypes: 1` from your config
