### ISSUE TITLE
New entities after upgrade

### ISSUE THREAD

**Issue by Friedrieck** [pippyn/Home-Assistant-Sensor-Afvalbeheer#467]
FYI, not sure why, but after upgrading to today's version (v5.3.1), the integration created new entities with "_2" at the end of the entities ids. The former entities are now unavailable because not being provided by the integration anymore.

**Comment by msc1978** [comment]
I have exactly the same after the exact upgrade..

**Comment by raymajor** [comment]
Here same issue, the integration created new entities with "sensor.gad_gft_2"

**Comment by GertVanderstukken** [comment]
and there is a different capitalization in the Name.
I assume this is the reason that a new entity is created...

Before: Recycleapp afvalophaling gft
After: Recycleapp Afvalophaling gft

**Comment by pippyn** [comment]
I'll look into this. Sorry for the inconvenience

**Comment by pippyn** [comment]
This is strange because the unique ID should have stayed the same.
What waste collector are you using?

**Comment by pippyn** [comment]
I'm sorry to say that the only solution I've found to this problem is to delete the unavailable sensors (without _2). And then remove the _2 from the new sensors.
