### ISSUE TITLE
Limburg.net Afvalbeheer

### ISSUE THREAD

**Issue by 2Crazy187** [pippyn/Home-Assistant-Sensor-Afvalbeheer#468]
Hi All,

I'm trying to add my afvalbeheer but it seems not to work. I get the error Config invalid! Streenname is required for limburg.net.
But this is my code that i've pasted in configuration.yaml:

afvalbeheer:
  wastecollector: Limburg.NET
  resources:
    - restafval
    - gft
    - papier
    - pmd
  cityname: xxx
  Streetname: xxx
  streetnumber: xx
  postcode: xxxx
  upcomingsensor: 0 
  dateformat: "%d-%m-%Y"
  dateonly: 0 
  dateobject: 0 
  dayofweek: 1 
  name: "" 
  nameprefix: 1 
  builtinicons: 0
  dutch: 1

If I swap cityname & streetname from place then Cityname is the issue. 
Somebody has a solution?

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by jayjayseal** [comment]
Hi,

For some reason it does not work anymore for Limburg.NET. it worked flawlessly for months (apart from the time they were hacked)... but since a week or so it stopped working. I had caps in the streetname and i have changed them following this post. but still no result.

**Comment by 2Crazy187** [comment]
@pippyn, it works for me now :) was indeed lower case. 
Thanks in advance!
