### ISSUE TITLE
PMD bij GAD komt niet binnen

### ISSUE THREAD

**Issue by basnagel** [pippyn/Home-Assistant-Sensor-Afvalbeheer#47]
De scrape voor PMD komt niet door bij het GAD.
De sensor geeft Unkown
GFT ,Rest en Papier doen het wel
Morgen en vandaag zijn ook Unknown

Config 

sensor:
  - platform: afvalbeheer
    wastecollector: GAD           
    resources:                     
        - restafval
        - gft
        - papier
        - pmd
    postcode: XXXXXX                
    streetnumber: XX
    builtinicons: 1
    nameprefix: 1
    upcomingsensor: 1                 
    dutch: 0
    dateformat: '%d-%m'

**Comment by pippyn** [comment]
GAD uses PBD, not PMD.
