### ISSUE TITLE
Can you add city of Goes?

### ISSUE THREAD

**Issue by marcelmah** [pippyn/Home-Assistant-Sensor-Afvalbeheer#475]
Hi,

I live in Goes and would like to add our waste, paper and 'gft' to Home Assistant.
They provide a easy website to find the days for your house via: https://afvalkalender.goes.nl/

You can test with postal code: 4463KK 2 (random via postcode.nl)

**Comment by pippyn** [comment]
Hi @marcelmah,

They don't seem to have an API for me to use.
Do you know if they have an app for the collection days?

**Comment by marcelmah** [comment]
Hi,

Not that I know of.... the city of Middelburg and Vlissingen are very close by (the only other 2 city's on this 'island'.)
I notice they are supported, chances are they use the same system, is this something you could check? Should I contact the city of Goes, if so, what questions would you need answered?

**Comment by pippyn** [comment]
Hi,

No they use a different system. I would need to have an exposed API to retrieve the data. And the website https://afvalkalender.goes.nl/ doesn't expose an API as far as I can see.

**Comment by marcelmah** [comment]
Hi,

I've sent them an e-mail, not expecting much, but you never know!

**Comment by marcelmah** [comment]
Hi,

They replyed that they use Sitebox CMS from Care, no API.
Will start looking for another city to live ;-)
