### ISSUE TITLE
No new trigger of the waste collector Schouwen-Duiveland

### ISSUE THREAD

**Issue by Mipilo** [pippyn/Home-Assistant-Sensor-Afvalbeheer#476]
I get my last waste trigger of Schouwen-Duiveland on 19-02-24.
I don't see any errors in de the logging.

**Comment by pippyn** [comment]
What is your config?
Do you have an address for me to test with?

**Comment by Mipilo** [comment]
Hi Pippyn,
I close this issue. The problem was a blocked connection.
It works now.
