### ISSUE TITLE
No data from mijnafvalwijzer

### ISSUE THREAD

**Issue by dacowiec** [pippyn/Home-Assistant-Sensor-Afvalbeheer#478]
Hello,

Somehow I am not getting any data from my mijnafvalwijzer.
I can see the data at my address via another waste plugin.
Am I doing something wrong?
I can see the data on the mijnafvalwijzer.nl site.

HA version: 2024.4.4

**Comment by pippyn** [comment]
What is your config? (with an address to test with)
Any errors in your logs?

**Comment by dacowiec** [comment]
this is my config:
afvalbeheer:
  wastecollector: mijnafvalwijzer
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 9693CR
  streetnumber: 2
  suffix: a                        # (optional)
  upcomingsensor: 1                # (optional)
  dateformat: '%d-%m-%Y'           # (optional)
  dateonly: 0                      # (optional)
  name: ""                         # (optional)
  nameprefix: 1                    # (optional)
  builtinicons: 1                  # (optional)
  builtiniconsnew: 1               # (optional)
  dutch: 1                         # (optional)

see the log error:
Logger: custom_components.afvalbeheer.API
Bron: custom_components/afvalbeheer/API.py:304
integratie: Afvalbeheer ([documentatie](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer))
Eerst voorgekomen: 25 april 2024 om 13:02:41 (9 gebeurtenissen)
Laatst gelogd: 13:02:43

No Waste data found!

**Comment by pippyn** [comment]
9693CR 2a doesn't exist..
Please remove the line `suffix: a                        # (optional)` and restart HA

**Comment by dacowiec** [comment]
How bad of me, how could I overlook it :P
