### ISSUE TITLE
Deprecated warning hass.helpers.discovery

### ISSUE THREAD

**Issue by goegol** [pippyn/Home-Assistant-Sensor-Afvalbeheer#480]
Hi, with homeassistant 2024.5.0 i got the following warning:

WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'afvalbeheer' accesses hass.helpers.discovery. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from discovery directly at custom_components/afvalbeheer/__init__.py, line 82: await hass.helpers.discovery.async_load_platform(, please report it to the author of the 'afvalbeheer' custom integration

**Comment by pippyn** [comment]
Thank you for reporting. I'm aware of this issue and will release an update soon.

**Comment by pippyn** [comment]
This warning is fixed in V5.3.3
