### ISSUE TITLE
Afvalbeheer stopped working for Avri

### ISSUE THREAD

**Issue by dsonnema88** [pippyn/Home-Assistant-Sensor-Afvalbeheer#483]
Hi, 

For a while now, Afvalbeheer shows everything "Unknown". Avri is our wastecollector. 

afvalbeheer:
  wastecollector: Avri
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 4214DC
  streetnumber: 51
  upcomingsensor: 0 # (optional)
  dateformat: "%d-%m-%Y" # (optional)
  dateonly: 0 # (optional)
  name: "" # (optional)
  nameprefix: 1 # (optional)
  builtinicons: 0 # (optional)
  dutch: 0 # (optional)

This is my config. 

Hope you can figure out what is wrong here

Regards

**Comment by pippyn** [comment]
Their API seems down. The website also doesn't work for me:
https://www.avri.nl/inwoners/afval/afvalkalender/

**Comment by dsonnema88** [comment]
Ah I see. The Avri app seemed to work, but was down as well yesterday. 
Now it seems to work again on their website. I will try later today if it works again!

**Comment by dsonnema88** [comment]
Everything works again, thanks!
