### ISSUE TITLE
RWM Collector not working anymore

### ISSUE THREAD

**Issue by HArpid** [pippyn/Home-Assistant-Sensor-Afvalbeheer#484]
The integration for the RWMCollector does not work anymore, the api is offline and is now a part of the OpzetCollector.

Please remove the lines for this collector from API.py (lines 135-136 & 1015-1093)

And add below line to const.py (insert after line 93)
`	'rwm':             	        'https://rwm.nl',`

**Comment by pippyn** [comment]
Added in v5.3.5
