### ISSUE TITLE
Meerlanden not working anymore

### ISSUE THREAD

**Issue by timkoers** [pippyn/Home-Assistant-Sensor-Afvalbeheer#49]
Meerlanden disabled their app.

https://afvalkalender.meerlanden.nl/rest/

**Comment by pippyn** [comment]
It looks like they just changed to address for the API.
Could you test if it works if you change line 155 in /custom_components/afvalbeheer/sensor.py from:
`'meerlanden': 'https://afvalkalender.meerlanden.nl',`
to:
`'meerlanden': 'https://inzamelkalender.meerlanden.nl',`
Does that work?

**Comment by timkoers** [comment]
> 
> 
> Yeah, I have the same problem. The new app seems to have a different kind of API, not sure if it is usable though.
> 
> ```shell
> curl 'https://wasteprod2api.ximmio.com/api/GetCalendar' -H 'content-type: application/json;charset=UTF-8' --data-binary '{"companyCode":"800bf8d7-6dd1-4490-ba9d-b419d6dc8a45","startDate":"2019-12-21","endDate":"2023-01-09","community":"Haarlemmermeer","uniqueAddressID":"1000042431"}'
> ```
> 
> ```json
> {"userMessage":{"type":null,"messageCode":0,"description":null},"ExtraOption":{"$type":"System.Dynamic.ExpandoObject, System.Core"},"dataList":[{"pickupDates":["2020-01-02T00:00:00","2020-01-16T00:00:00","2020-01-30T00:00:00","2020-02-13T00:00:00","2020-02-27T00:00:00","2020-03-12T00:00:00","2020-03-26T00:00:00","2020-04-02T00:00:00","2020-04-09T00:00:00","2020-04-16T00:00:00","2020-04-23T00:00:00","2020-04-30T00:00:00","2020-05-07T00:00:00","2020-05-14T00:00:00","2020-05-25T00:00:00","2020-05-28T00:00:00","2020-06-04T00:00:00","2020-06-11T00:00:00","2020-06-18T00:00:00","2020-06-25T00:00:00","2020-07-02T00:00:00","2020-07-09T00:00:00","2020-07-16T00:00:00","2020-07-23T00:00:00","2020-07-30T00:00:00","2020-08-06T00:00:00","2020-08-13T00:00:00","2020-08-20T00:00:00","2020-08-27T00:00:00","2020-09-03T00:00:00","2020-09-10T00:00:00","2020-09-17T00:00:00","2020-09-24T00:00:00","2020-10-01T00:00:00","2020-10-08T00:00:00","2020-10-15T00:00:00","2020-10-22T00:00:00","2020-10-29T00:00:00","2020-11-05T00:00:00","2020-11-19T00:00:00","2020-12-03T00:00:00","2020-12-17T00:00:00","2020-12-31T00:00:00"],"pickupType":1,"_pickupType":1,"_pickupTypeText":"GREEN","description":"HA Gft 02 Toolenburg West"},{"pickupDates":["2020-01-09T00:00:00"],"pickupType":6,"_pickupType":6,"_pickupTypeText":"TREE","description":"HA Kerstbomen 02 Toolenburg West"},{"pickupDates":["2019-12-24T00:00:00","2020-01-07T00:00:00","2020-01-21T00:00:00","2020-02-04T00:00:00","2020-02-18T00:00:00","2020-03-03T00:00:00","2020-03-17T00:00:00","2020-03-31T00:00:00","2020-04-14T00:00:00","2020-04-28T00:00:00","2020-05-12T00:00:00","2020-05-26T00:00:00","2020-06-09T00:00:00","2020-06-23T00:00:00","2020-07-07T00:00:00","2020-07-21T00:00:00","2020-08-04T00:00:00","2020-08-18T00:00:00","2020-09-01T00:00:00","2020-09-15T00:00:00","2020-09-29T00:00:00","2020-10-13T00:00:00","2020-10-27T00:00:00","2020-11-10T00:00:00","2020-11-24T00:00:00","2020-12-08T00:00:00","2020-12-22T00:00:00"],"pickupType":0,"_pickupType":0,"_pickupTypeText":"GREY","description":"HA Rest 02 Toolenburg West"},{"pickupDates":["2020-04-09T00:00:00","2020-11-05T00:00:00"],"pickupType":29,"_pickupType":29,"_pickupTypeText":"BRANCHES","description":"HA Takken 02 Toolenburg West"}],"intDataList":null,"data":null,"status":true,"messageCode":107,"pdfResponse":null,"token":null,"ID":null,"invalidParameters":null,"total":0,"messageToString":null}
> ```

This is what seems to be usable! Maybe if I have some time left today, I'll fix the plugin

**Comment by basschipper** [comment]
Got it working in a local script. But the integration in this plugin is giving a hard time. This hole `COLLECTOR_NEW_API` and `COLLECTOR_WASTE_ID` are so hacky.

**Comment by basschipper** [comment]
Added a PR: #50 

Please test!

**Comment by timkoers** [comment]
:-) 
It's working for me!
Thanks Bas!

**Comment by pippyn** [comment]
fixed in 3.0.4 thanks to Bas

**Comment by nicovankampen** [comment]
Hi, 
Got two sensors working (restafval and GFT). PBD and papier not however. Do they have different names with Ximmio (former Meerlanden) ?
P.S. for other people with the same problem: When using configureUI in Lovelace, load the new Ximmio sensors.

**Comment by pippyn** [comment]
This should be a new issue. Please create one and give me some more info:
- are you using the latest version? 
- what is your config

**Comment by nicovankampen** [comment]
Yes i updated to 3.1.1 3 days ago.
sensor:
  - builtinicons: 0
    dateformat: '%d-%m-%Y'
    dateonly: 0
    dutch: 1
    name: ''
    nameprefix: 0
    platform: afvalbeheer
    postcode: 2182xx
    resources:
      - restafval
      - gft
      - papier
      - pmd
    streetnumber: xx
    upcomingsensor: 1
    wastecollector: ximmio

**Comment by basschipper** [comment]
The place where I live, there is no papier/pmd collection, you have to bring it to a local container/depot. When I first implemented the new Ximmio API I therefore don't think this was implemented...

I'm working on some code refactoring, will try to fix this as well.

**Comment by nicovankampen** [comment]
thanks. eagerly awaiting your fix.  Keep on the good work!
