### ISSUE TITLE
Restafval+PMD combination missing

### ISSUE THREAD

**Issue by RoRoo1977** [pippyn/Home-Assistant-Sensor-Afvalbeheer#492]
Almere has recently removed PMD and merged it with Restafval. 
I cannot see this in the AfvalBeheer sensors. 
all the available related (pmd/restafval) sensors state: Unknown.

**Comment by pippyn** [comment]
What does the option `Print all available waste fractions` give you?

**Comment by RoRoo1977** [comment]
oh nice feature, was looking for it but missed it. 
Result is: 
Available waste types: BULKYRESTWASTE, GFT, Papier

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by RoRoo1977** [comment]
1316LL

**Comment by RoRoo1977** [comment]
I've added BULKYRESTWASTE to my config. And it shows today's date, so that seems to work.

**Comment by pippyn** [comment]
- Update to v5.3.6 of the sensor
- Add `PMD-Restafval` to your resources in your config (remove BULKYRESTWASTE)
- Roboot HA

**Comment by RoRoo1977** [comment]
Done and working! Thank you so much!
