### ISSUE TITLE
Add WasteCollector

### ISSUE THREAD

**Issue by Hoftie** [pippyn/Home-Assistant-Sensor-Afvalbeheer#509]
Goodmorning,

Please can you add Sliedrecht to Waste Collector.
I have called Opzet (https://www.opzet.nl/contact/)  phone number: 0235388200 
They can give you te API

thank you very much!

**Comment by Hoftie** [comment]
Thank you very much for the quick response!

Unfortunately I don't see a date yet

**Comment by pippyn** [comment]
What is your config? Can you give me an address so I can do some tests?

**Comment by Hoftie** [comment]
#afvalbeheer
afvalbeheer:
  wastecollector: Sliedrecht
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 3363XL
  streetnumber: 26 
  upcomingsensor: 0
  dateformat: '%d-%m-%Y'
  dateonly: 0
  name: "MijnAfvalbeheer"
  nameprefix: 1
  builtinicons: 1
  builtiniconsnew: 1
  dutch: 1

**Comment by pippyn** [comment]
Fixed in v5.4.3

**Comment by Hoftie** [comment]
Thank you very much!!! 
Now it works perfectly!!!
