### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by mosjonathan** [pippyn/Home-Assistant-Sensor-Afvalbeheer#51]
yesterday i moved to a recorder setup after that i'm getting the following error

`Error adding event: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'event_data' at row 1") [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s)] [parameters: ('state_changed', '{"entity_id": "sensor.pmd", "old_state": {"entity_id": "sensor.pmd", "state": "22-04-2020", "attributes": {"Official name": "Zwart kratje PMD BEST", ... (73489 characters truncated) ... :00", "last_updated": "2020-04-09T07:56:17.541387+00:00", "context": {"id": "eaf2296cf7d14416b8314960031a1b0a", "parent_id": null, "user_id": null}}}', 'LOCAL', datetime.datetime(2020, 4, 9, 7, 56, 17, 541437, tzinfo=<UTC>), datetime.datetime(2020, 4, 9, 7, 56, 17, 544357), 'eaf2296cf7d14416b8314960031a1b0a', None)] (Background on this error at: http://sqlalche.me/e/9h9h)'

**Comment by pippyn** [comment]
The system throws this error because the field `event_data` in your mysql database is to small. You have 2 options:
1. Make the field larger in the MySQL database
or
2. Exclude the sensors from the recorder ([see docs](https://www.home-assistant.io/integrations/recorder/#exclude))
