### ISSUE TITLE
API recycleapp.be not accessible

### ISSUE THREAD

**Issue by TheSuperBeaver** [pippyn/Home-Assistant-Sensor-Afvalbeheer#514]
The api from recycleapp.be seems to be unavailable.

`2024-10-01 15:22:20.753 ERROR (MainThread) [custom_components.wastemanagement.API] Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8246a2d0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))"))`

When I'm going to https://api.recycleapp.be/api/app/v1/ I receive a 404

I "hope" this is global, and not because they kicked my IP since I'm doing a lot of queries

(Also, note that I've changed the name "afvalbeheer" to "wastemanagement", because I'm in the process of translating the code to french, english and dutch)

I took contact with the owners of the website to check if that's a "they" problem

**Comment by JonasGe** [comment]
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/releases/tag/v5.4.2

Fixed in 5.4.2
