### ISSUE TITLE
Change of Bins in Almere

### ISSUE THREAD

**Issue by erwinvana** [pippyn/Home-Assistant-Sensor-Afvalbeheer#517]
Hello,
In Almere the PDM and Restafval are being combined. 
PDM bin is removed and only the restafval is left.
(Besides the paper and GFT bin)
In my area they swapped already and now both the PDM and and the restafval show as unknown.
(Paper and GFT still show the correct date)
What should i use to get the "new' "PDM+rest" dat shown?

thanks for helping 
KR, Erwin

**Comment by pippyn** [comment]
Did you try the option [Print all available waste fractions](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions)?

**Comment by erwinvana** [comment]
great missed this option....
result:
Afvalwijzer almere
Available waste types: GFT, Papier, PMD-Restafval

**Comment by erwinvana** [comment]
Solved.
