### ISSUE TITLE
Almere: restafval - unknown 

### ISSUE THREAD

**Issue by RoyMeinen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#519]
So almere stopped with pmd containers and combined them with restafval.

Now the pmd is unavailable as expected, but restafval is set to unknown. There might have been changes that broke it?

**Comment by pippyn** [comment]
Did you try the `Print all available waste fractions` option?
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer?tab=readme-ov-file#print-all-available-waste-fractions

**Comment by RoyMeinen** [comment]
oke, that was a simple solution!

its pmd-restafval now..  Thanks!
