### ISSUE TITLE
Sensor morgen heeft geen waarde

### ISSUE THREAD

**Issue by Wezze03** [pippyn/Home-Assistant-Sensor-Afvalbeheer#520]
Bij de sensor morgen wordt niet weergegeven wat er morgen wordt opgehaald. Dit is problematisch want wanneer ik de sensor eerst volgende gebruik en er is op de dag zelf een omhaling krijg ik die van de dag zelf.
Kan dit nagekeken worden aub?
![image](https://github.com/user-attachments/assets/cac30fd5-ff24-4cfc-8bda-b71a0fca4b79)

**Comment by Wezze03** [comment]
![image](https://github.com/user-attachments/assets/dbd5dc80-b0a0-4330-b12e-eecc44c7557e)

**Comment by RWSF74** [comment]
Hier soortgelijk gedrag, sensor.acv_morgen geeft niet de juiste waarde aan. Geschiedenis geeft de juiste waarde aan; 'geen'.
Hidden staat op true:
<img width="614" alt="2024-11-21_Schermafbeelding 2024-11-21 115005" src="https://github.com/user-attachments/assets/0eb2a761-5a1b-4e62-99e4-ec8389a27377">
Alvast bedankt voor je hulp!

**Comment by pippyn** [comment]
What is your config?

**Comment by pippyn** [comment]
Please copy/paste the config. No Screenshots please

**Comment by RWSF74** [comment]
No errors, no notifications of whatsoever. very strange behavior. Refreshing the page sometimes flips the status to the right value, and vice versa.

<img width="713" alt="Schermafbeelding 2024-11-21 145612" src="https://github.com/user-attachments/assets/695f6c25-2abd-4202-9972-47b7f32f4a34">

I'm beginning to suspect a custom:button-card to be kind of buggy. Is it somehow possible that such a card can alter the state of sensor.acv_morgen?

**Comment by pippyn** [comment]
I can't help you with that. I'm not familiar with frontend coding for HA

**Comment by RWSF74** [comment]
OK I'll keep that in mind. Thanks for your help!

**Comment by Wezze03** [comment]
> Please copy/paste the config. No Screenshots please

Hey pippyn,
If you you need something from me let me know...
