### ISSUE TITLE
Almere afvalbeheer

### ISSUE THREAD

**Issue by bosmanav** [pippyn/Home-Assistant-Sensor-Afvalbeheer#521]
PMD en Rest zijn samengevoegd, krijg dus daarom waarschijnlijk onbekend als waarde bij restafval. 
GFT en PAPIER werken wel. 
Misschien tijd voor een aanpassing. 

PaulB.

**Comment by pippyn** [comment]
Yes, then you'll need to change your config.

**Comment by bosmanav** [comment]
I try this, but with no result
afvalbeheer:
  wastecollector: Almere
  resources:
    - rest+pmd
    - gft
    - papier

<img width="379" alt="Schermafbeelding 2024-11-04 om 20 42 57" src="https://github.com/user-attachments/assets/7edd17ec-2142-49f8-bab6-726d026abfaf">
