### ISSUE TITLE
split entity 'eerstvolgende'

### ISSUE THREAD

**Issue by RWSF74** [pippyn/Home-Assistant-Sensor-Afvalbeheer#524]
Hi Pippyn,

I am creating a one-icon custom button card to display upcoming pickups (with different icons and colors, depending on container and pickup date). I can't get the custom button card to pick the right icon for 'eerstvolgende' pick-up, because this entity contains both type and date.

For that I would like extra entities for 'eerstvolgende' with a separation of:
- only type of container 
- pick-up date
for example:
- sensor.acv_eerstvolgende.type --> GFT / PAPIER etc
- sensor.acv_eerstvolgende.date --> date only

I hope this is possible, thanks in advance!

Cheers, Richard.

**Comment by RWSF74** [comment]
Bedankt voor je integratie trouwens, heel leuk om mee te hobby'en!

**Comment by pippyn** [comment]
Hi @RWSF74,

Those are already state properties. Namely `Upcoming day` and `Upcoming waste types`

**Comment by RWSF74** [comment]
Thanks! Found them.
