### ISSUE TITLE
Saver has switched to Afvalbeheer app

### ISSUE THREAD

**Issue by bdoedens** [pippyn/Home-Assistant-Sensor-Afvalbeheer#528]
Can you add Saver as a waste collector?

They have switched over to a new app made by Opzet bv which is the same as Afvalbeheer if I am right?

Saver is not yet recognised by the integration as a collector.

**Comment by bdoedens** [comment]
https://play.google.com/store/apps/developer?id=Opzet+BV

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by bkbartk** [comment]
I just added the comment here
https://github.com/xirixiz/homeassistant-afvalwijzer/issues/326#issuecomment-2519894551
I don't live there bug google helped me with the address

**Comment by pippyn** [comment]
Version v5.5.0 added support for saver.nl

**Comment by bdoedens** [comment]
so fast! will update and test when I'm home! thanks!

**Comment by niekniek89** [comment]
I am also still with "Afvalwijzer", and I see that the app will soon no longer work, and I have to switch to "Saver".
Via the Saver website I can neatly see all the collection dates (for my postcode).
However, when I add this integration, I get the message that my address cannot be found.

**Comment by niekniek89** [comment]
I too am switching from "mijnafvalwijzer" to Saver.
Should I choose mijnafvalwijzer for wastecollector?

**Comment by bdoedens** [comment]
Updated yesterday evening and found it to be working perfectly for Saver, thanks voor de swift update!
