### ISSUE TITLE
Version 5.5.0 - no more tomorrow sensor and 2 today sensors

### ISSUE THREAD

**Issue by Tazmanian79** [pippyn/Home-Assistant-Sensor-Afvalbeheer#530]
Today I have updated to HA 2024.12.0 and after that I upgraded to version 5.5.0

After the restart all entitites were recreated (with _2 at the end of course)
I removed the old entities and restarted again so the entities have their normal ID again and my automations keep working.

But there is no "tomorrow" sensor anymore.  But instead there are now 2 "today" entities.

So the update to version has a bug.  Can you check it?

**Comment by JSpeleers** [comment]
I'm not using the upcoming sensors but had the same issue after upgrade and update with the resource sensors. Removing the original sensors and restarting HA did indeed solve it. Thanks!

**Comment by velddriel** [comment]
Same problem here. All entities are now with _2 at the end. I already changed the necessary things, so that I now use the _2 sensors for my calendar. Unfortunately the sensor "tomorrow" is gone, which I use in an automation in HA to send a message through the house. Hope this could be resolved soon. Tnx.

**Comment by Tazmanian79** [comment]
Yes deleting the original sensors and restart HA does solve one part.
But there are still 2 today sensors and no tomorrow sensor.

**Comment by pippyn** [comment]
Fix tomorrow sensor in V5.5.1

**Comment by velddriel** [comment]
Probably a failure somewhere in the sensor.py. Tnx Pippyn!

**Comment by sammyke007** [comment]
What's the best way to restore the _2 entities to the normal name?
