### ISSUE TITLE
Update 5.5.1 makes duplicate entities

### ISSUE THREAD

**Issue by iAmRenzo** [pippyn/Home-Assistant-Sensor-Afvalbeheer#531]
After the update all my sensors were unavailable, but now I see the update created duplicates with a _2 suffix. How can I fix this? I really do not want to edit all my dashboards and automations.

![image](https://github.com/user-attachments/assets/98444289-7aed-4545-ad38-abd7d8bec5c8)

**Comment by eclaassens** [comment]
Same. Had to remove Afvalbeheer as an integration, remove from config.yml and remove all entities manually and do a clean install from hacs. At least the sensors came back with the normal names. No changes to the dashboards needed

**Comment by pendragon1** [comment]
I removed the original entities from HA, restarted HA and the _2 were ok again (without the _2). All fine now.

**Comment by JRDevo** [comment]
Thats a workaround,  however its still like this on 5.5.2

**Comment by JRDevo** [comment]
Thats a workaround,  however its still like this on 5.5.2

**Comment by pippyn** [comment]
Should be addressed in V5.5.3

**Comment by iAmRenzo** [comment]
Should? Is anyone that can confirm an update from 5.1.1 to 5.5.3 will not create extra entities and break my (fixed) configuration)

**Comment by pendragon1** [comment]
> Should? Is anyone that can confirm an update from 5.1.1 to 5.5.3 will not create extra entities and break my (fixed) configuration)

I installed 553, no issues here, but I already removed the old entities with 551 and had no issues after that.
