### ISSUE TITLE
Stopped working after update to 5.5.1

### ISSUE THREAD

**Issue by menloperk** [pippyn/Home-Assistant-Sensor-Afvalbeheer#532]
All fields show up as Unavailable. Restarting HA doesn't help. Reloading pages doesn't help. Can't find anything in the logs.

**Comment by zmstr** [comment]
Somehow this recent update freezes my Home Assistant completely. It gets unresponsive as soon as I open a dashboard with all the Afvalbeheer sensors. Sensors like tomorrow or upcoming also have the "Invalid timestamp" as a value. So something is really acting up. I need to hard reset my Raspberry to get my Home Assistant reachable again.

**Comment by menloperk** [comment]
Same as #531
