### ISSUE TITLE
Days_until attribute wrong since 5.5.1 update?

### ISSUE THREAD

**Issue by vandenbogerd** [pippyn/Home-Assistant-Sensor-Afvalbeheer#535]
I also got the inactive entities, removed them, reinstalled etc etc

But my automations heavily use the Days_until attributes; and those are stating '0', while the next collection date is 20241219.
When I try to access the attributes from the entity itself, it states that there is no unique ID, so no more details can be shown.

**Comment by pippyn** [comment]
Can you please share your config? Whit an address to test with?

**Comment by vandenbogerd** [comment]
Sure thing!

(Address not mine, but existing and in the same schedule)


`# Afvalbeheer
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - restafval
      - papier
      - pmd
      - textiel
    postcode: 2322
    streetname: 'Lage Weg'
    cityname: 'Minderhout'
    streetnumber: 18
    dateformat: '%d-%m-%Y'
    upcomingsensor: 1
    nameprefix: 0
    dutch: 1
    dayofweek: 0 #voor de Blueprint garbage collection
    dateonly: 1 #voor de Blueprint garbage collection`

**Comment by martinfrunt** [comment]
You'll have to delete the original entities and restart HA. It'll fix the issue.

![image](https://github.com/user-attachments/assets/c39ab91e-8baf-45ef-9d98-902c76782445)

**Comment by pippyn** [comment]
@martinfrunt Negative, this is a different issue and is fixed in version v5.5.2

**Comment by harmpert** [comment]
@pippyn I just reinstalled afvalbeheer (after removing it through HACS) but the entities still have no unique ID...

**Comment by harmpert** [comment]
Version 5.5.2...

**Comment by vandenbogerd** [comment]
> @martinfrunt Negative, this is a different issue and is fixed in version v5.5.2

"The version v5.5.2 for this integration can not be used with HACS."

**Comment by vandenbogerd** [comment]
> @martinfrunt Negative, this is a different issue and is fixed in version v5.5.2

I hereby confirm that Days_until is working as expected again!

(I manually updated the necessary files, and restarted HA again)

Only the UniqueID's still need to be addressed, right?

**Comment by pippyn** [comment]
Should be addressed in V5.5.3

**Comment by harmpert** [comment]
@pippyn The unique ID's is indeed solved in 5.5.3!
Thanks!

**Comment by niekniek89** [comment]
> You'll have to delete the original entities and restart HA. It'll fix the issue.
> 
> ![image](https://private-user-images.githubusercontent.com/181835009/393209305-c39ab91e-8baf-45ef-9d98-902c76782445.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NzMzNTAsIm5iZiI6MTczMzU3MzA1MCwicGF0aCI6Ii8xODE4MzUwMDkvMzkzMjA5MzA1LWMzOWFiOTFlLThiYWYtNDVlZi05ZDk4LTkwMmM3Njc4MjQ0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QxMjA0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjJkZmYyNDNlNWI3ZGU2ODdmNjY4MjZmYjgzY2QyNWZmMWY0NzRiOGEyMTRjMmYwMzM1OTk3ZjY2OTg5ZDU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jEaVKr41um-Ktuy2KO9n-b09509Eo5Ez1eAUQJqqH2A)

Can you share this config for Days until?
