### ISSUE TITLE
Support for Saver (question, no issue!)

### ISSUE THREAD

**Issue by niekniek89** [pippyn/Home-Assistant-Sensor-Afvalbeheer#538]
Hello,

I am new to this integration, because "mijnafvalwijzer" is going to stop.
I don't see "Saver" anywhere with waste collectors.
Did I create it just now?

**afvalbeheer:
  wastecollector: Saver
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: my postcode
  streetnumber: 4**

**Comment by pippyn** [comment]
Saver should work

**Comment by niekniek89** [comment]
Thanks, it works!

**Comment by niekniek89** [comment]
@pippyn 

Thanks for your answer.
I also see all the dates for the whole of 2025 on the Saver site (with my zip code).
Am I doing something wrong with my config?
