### ISSUE TITLE
Entities show up as "onbekend"

### ISSUE THREAD

**Issue by mountainbikert** [pippyn/Home-Assistant-Sensor-Afvalbeheer#539]
Hi,

Can you check if zipcode 5251JA number 5 is working for afvalstoffendienstkalender?
Can't get any info.

Thanks

**Comment by jboonstra90** [comment]
Have a similar issue. For Omrin the 'papier' sensor keeps showing "onbekend" for a few days now (ever since the last collection)

**Comment by mountainbikert** [comment]
I haven't seen one date yet.

**Comment by pippyn** [comment]
- remove all sensors created by this integration.
- update the sensor to v5.5.4
- restart HA

**Comment by mountainbikert** [comment]
How do i remove all sensors? Just upgraded to 5.5.4 and still seeing "onbekend"

**Comment by pippyn** [comment]
You can remove them here:

<a href="https://my.home-assistant.io/redirect/entities/" target="_blank" rel="noreferrer noopener"><img src="https://my.home-assistant.io/badges/entities.svg" alt="Open your Home Assistant instance and show your entities." /></a>

**Comment by pippyn** [comment]
> I've deleted everything, still the paper collection from omrin shows "Onbekend"
> 
> Can it be that this isn't in their API yet since the next collection is in 2025?

Yes indeed, many waste collectors do not update the API until januari.

**Comment by pippyn** [comment]
@jboonstra90 try the following:
- remove the sensor config from your yaml file
- delete the integration
- restart HA
- remove all sensors created by this integration (important!)
- install v5.5.4 of the sensor
- restart HA
- add your config again
- restart HA

**Comment by pippyn** [comment]
It does not differ per waste collector. It works for all collectors

**Comment by pippyn** [comment]
I tested your address, but 5251JA 5A doens't exist...
5251JA 5 does exist, so remove the suffix line from your config.

**Comment by mountainbikert** [comment]
> I tested your address, but 5251JA 5A doens't exist... 5251JA 5 does exist, so remove the suffix line from your config.

Can't believe I missed that :-) It's working now.

**Comment by JohanKrab** [comment]
Since last update status for 'Waardlanden' is 'onbekend'.

**Comment by coldburn89** [comment]
Same issue for "de afvalapp" on address 5706XN 5

**Comment by pippyn** [comment]
@coldburn89 please create a new issue, with your config and an address for me to test with. Also share any errors in your log.

**Comment by pippyn** [comment]
@coldburn89 please create a new issue, with your config and an address for me to test with. Also share any errors in your log.
