### ISSUE TITLE
Add support for Saver (Afvalkalender) - active in West-Noord-Brabant, Netherlands

### ISSUE THREAD

**Issue by gerbenp** [pippyn/Home-Assistant-Sensor-Afvalbeheer#540]
Hi, is it possible to add support for this?

https://saver.nl/afvalkalender

I have contacted Saver already if they can make the api data available. Don't know if it is possible to get this without the support from Saver if they were not allowed to cooperate.

I will keep you informed if I know more.

**Comment by gerbenp** [comment]
I discovered these REST API endpoints by examining the network requests in Chrome DevTools. I'm not entirely sure if this list is exhaustive, but here are the unique URLs I've found so far:

https://saver.nl/rest/app/settings
https://saver.nl/zcalendar/pages/page
https://saver.nl/rest/postcode/4715RW
https://saver.nl/adressen/4715RW:1
https://saver.nl/rest/feestdagen/2023-12-26/2025-01-06
https://saver.nl/rest/adressen/0840200000293003/afvalstromen
https://saver.nl/rest/adressen/0840200000293003/kalender/2024

**Comment by pippyn** [comment]
Saver is already supported...
