### ISSUE TITLE
Empty value Sensors

### ISSUE THREAD

**Issue by Remcovf** [pippyn/Home-Assistant-Sensor-Afvalbeheer#543]
Hi @Jordi1990 

i added the info in configuration.yaml.

<img width="422" alt="Schermafbeelding 2024-12-21 om 20 11 57" src="https://github.com/user-attachments/assets/81261246-fd67-4645-87a8-ddab18fd221f" />

but al my sensors give a empty value.

<img width="371" alt="Schermafbeelding 2024-12-21 om 20 08 49" src="https://github.com/user-attachments/assets/947a5755-71f6-4bec-9134-2c76701c717e" />

<img width="1859" alt="Schermafbeelding 2024-12-21 om 20 09 04" src="https://github.com/user-attachments/assets/848872eb-f32e-4e9c-ac60-b21faafa4083" />

<img width="632" alt="Schermafbeelding 2024-12-21 om 20 09 12" src="https://github.com/user-attachments/assets/abd8b853-51fe-4a8c-a1dc-e58d8276fef8" />

Is there anything missing? Do I overlook something?

**Comment by pippyn** [comment]
Does your address have a suffix? If not, remove that line

**Comment by Remcovf** [comment]
> Does your address have a suffix? If not, remove that line

Many thanks. That was the trick!
