### ISSUE TITLE
To frequent updates

### ISSUE THREAD

**Issue by coolriku** [pippyn/Home-Assistant-Sensor-Afvalbeheer#57]
I saw in the logging that this Custom Component refreshes to frequent.
I looked at the code and the throttle row is commented out

https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/cefa904e97c90e0dba59beac4c087ba89b9be460/custom_components/afvalbeheer/sensor.py#L315

Is there a reason for? I don't know if some API's are rate limited, otherwise you'l get banned

**Comment by pippyn** [comment]
will be readded in the next version.
