### ISSUE TITLE
[FR] Please make the polling rate less or variable.

### ISSUE THREAD

**Issue by Luukxt8** [pippyn/Home-Assistant-Sensor-Afvalbeheer#59]
I think we need to change the polling rate of the Afvalbeheer API's. See screenshot below. This is the amount it's getting requested within 24 hours. 

![image](https://user-images.githubusercontent.com/50046608/79682548-85e40180-8223-11ea-9d68-30aee24a27b1.png)

`2020-04-19 09:49:22 ERROR (SyncWorker_5) [custom_components.afvalbeheer.sensor] Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='inzamelkalender.hvcgroep.nl', port=443): Max retries exceeded with url: /rest/adressen/***********/afvalstromen (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fefb632b390>: Failed to establish a new connection: [Errno -3] Try again'))"))
`

**Comment by pippyn** [comment]
Yes I know. Will be fixed in the next release. For now you can uncomment line 315, this line 
`# @Throttle(MIN_TIME_BETWEEN_UPDATES)`

**Comment by Luukxt8** [comment]
Hi, 
Thank you for your reply 👍 Take you time! 

Thank you for your work, I'm very happy with the integration!

**Comment by pippyn** [comment]
No problem :)
Fixed in version 4.0.0
