### ISSUE TITLE
Sensor pmd circulus-berkel

### ISSUE THREAD

**Issue by mosjonathan** [pippyn/Home-Assistant-Sensor-Afvalbeheer#62]
This sensor does not work after the latest update.

I have also put pbd but that one does also not work.

**Comment by pippyn** [comment]
Rest API for circulaire berkel is down at the moment. Hopefully they fix it soon

**Comment by mosjonathan** [comment]
The funny thing is that the papier sensor works.

**Comment by pippyn** [comment]
circulus-berkel should be working now. Can you share your config? (you can dm me on the [HA community](https://community.home-assistant.io/u/pippyn/)) 
Is the sensor on version 4.1.0?

**Comment by mosjonathan** [comment]
sure i can share my config.

i cannot dm you but i will share here:

`  
- platform: afvalbeheer
    wastecollector: Circulus-Berkel
    resources:
      - papier
      - pmd
      - gtf
    postcode: 7204PK
    streetnumber: 55
    upcomingsensor: 1
    dateformat: '%d-%m-%Y'
    dateonly: 0
    name: ""
    nameprefix: 0
    builtinicons: 1
    dutch: 1 
`

this is my config that used to work.

sensos papier and gft are working only pmd is not.
i know that the collection date for pmb should be tomorrow (22-04-2020)

the senson is on 4.1.0 with ha on 108.6

**Comment by pippyn** [comment]
Found the issue, will release a fix now

**Comment by pippyn** [comment]
Can you try version 4.1.1 please?

**Comment by mosjonathan** [comment]
One moment i’ll download it

**Comment by mosjonathan** [comment]
It is working now thanks for the quick fix

**Comment by pippyn** [comment]
no problem! Glad I could help
