### ISSUE TITLE
name / nameprefix doesnt seem to work

### ISSUE THREAD

**Issue by yvesfouquet4** [pippyn/Home-Assistant-Sensor-Afvalbeheer#63]
i cant seem to successfully add name: and/or nameprefix: 0 to the configuration.yaml without error:
sensor:
  - platform: afvalbeheer
    wastecollector: ophaalkalender
    resources:
      - restafval
      - pmd
      - papier
    postcode: postalcode
    streetname: streename
    streetnumber: streetnumber
    dateformat: '%d-%m-%Y'
    builtinicons: 1
    name: 'pmd'
    nameprefix: 0
![afbeelding](https://user-images.githubusercontent.com/8839059/79928069-19931900-8442-11ea-85fa-37765cbc76ea.png)

without any name setting it works perfectly 👍 : 
  - platform: afvalbeheer
    wastecollector: ophaalkalender
    resources:
      - restafval
      - pmd
      - papier
    postcode: postalcode
    streetname: streename
    streetnumber: streetnumber
    dateformat: '%d-%m-%Y'
    builtinicons: 1
    #name: 'pmd'
    #nameprefix: 0

![afbeelding](https://user-images.githubusercontent.com/8839059/79928305-dd13ed00-8442-11ea-8c2f-cb0fd10bbe46.png)

Thanks in advance for the feedback

**Comment by pippyn** [comment]
The screenshots are in Lovelace, yes? Did you change the sensors in the your Glances(I think) Card? If you change the names, you have to change the names there also.

**Comment by yvesfouquet4** [comment]
Yes this was in Lovelace UI. Also your solution worked, i forgot to change the entity in the card which i did as below:
![afbeelding](https://user-images.githubusercontent.com/8839059/79966288-84b60d00-848d-11ea-95b9-3e5010091743.png)

Thank you for your fast response, great sensor
