### ISSUE TITLE
Color icons

### ISSUE THREAD

**Issue by yvesfouquet4** [pippyn/Home-Assistant-Sensor-Afvalbeheer#65]
Is it possible to change the color from the icons because it only looks good on a white background. 
If you change to another theme you can barely see the images of the different waste kinds

Thank you
![afbeelding](https://user-images.githubusercontent.com/8839059/79967310-f2af0400-848e-11ea-8b1f-3e2585bf4a62.png)

**Comment by pippyn** [comment]
The included icons are only available in black. But you can add your own icons if you want, [just like every other entity in Home Assistant](https://www.home-assistant.io/docs/configuration/customizing-devices/)
You probably should set `disableicons: 1` in your [config for the sensor](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#disable-the-use-of-entity_picture)
