### ISSUE TITLE
HVC PBD doen't work (anymore)

### ISSUE THREAD

**Issue by Nenodema** [pippyn/Home-Assistant-Sensor-Afvalbeheer#66]
Goodmorning,

Since a couple of days the HVC PBD config doesn't work anymore. Any idea what it might be?

Thanks!

Interface:

![image](https://user-images.githubusercontent.com/33698556/80471057-28e2fc80-8943-11ea-8b37-c9aa03177098.png)

Config:

![image](https://user-images.githubusercontent.com/33698556/80471151-4adc7f00-8943-11ea-8af8-17e238f44047.png)

**Comment by pippyn** [comment]
Strange. What happens when you change pbd to pmd?

**Comment by earlhickey** [comment]
I have the same issue using wastecollector GAD. I looked in the code and in the api response. 

GAD api returns these titles:
`"title": "Plastic, blik en drinkpakken",`
`"page_title": "Plastic, blik en drinkpakken",` 

In previous version 2.5.12 that i was using before the title of the response had a RENAME_TITLES array where plastic is mapped to pmd. The latest version doesn't have this anymore. 

Thanks for this package @pippyn If you need help for a fix please let me know.

**Comment by pippyn** [comment]
And does pmd work for you @earlhickey ?

**Comment by earlhickey** [comment]
No that does not work

**Comment by pippyn** [comment]
Can you [DM me](https://community.home-assistant.io/u/pippyn/summary) a postcode and street number for me to test with?

**Comment by earlhickey** [comment]
> Can you [DM me](https://community.home-assistant.io/u/pippyn/summary) a postcode and street number for me to test with?

I do not see any DM possibility but 1398XW 99 will do. 

https://inzamelkalender.gad.nl/rest/adressen/1398XW-99
https://inzamelkalender.gad.nl/rest/adressen/0424200000017957/afvalstromen

**Comment by tyfoon** [comment]
I'm definitely with GAD and have the same issue. Is seems that they have changed PBD to PMD. About a year ago it was the other way around.. So just change PBD to PMD and your fine.

**Comment by earlhickey** [comment]
> First off all; that is GAD and not HVC
> 
> Second; This config is working just fine for me:
> 
> ```
>   - platform: afvalbeheer
>     wastecollector: gad
>     resources:
>       - pmd
>     postcode: 1398XW
>     streetnumber: 99
> ```

What finally did fix it was update hacs to latest, update this repo to v4.1.5 and restarted. 
Used resources restafval, papier, pmd.
![Screenshot 2020-04-28 at 21 50 24](https://user-images.githubusercontent.com/1826864/80531090-560ec980-899a-11ea-8b92-14083a766f36.jpg)

Thanks for your time!

**Comment by Nenodema** [comment]
I have also installed the latest updates but no unfortiantly still "Unknow".

Without publishing someones address: You can test with a street in the place called "Kraggenburg". I was not able to find the DM function in Github ;-)

**Comment by pippyn** [comment]
@Nenodema 
This works fine for me:
```
  - platform: afvalbeheer
    wastecollector: HVC
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 8317**
    streetnumber: 1
    upcomingsensor: 0
    dateformat: '%d-%m-%Y'
    nameprefix: 1
    builtinicons: 0
    name: ""
    dutch: 1
```
Note: the PMD under resources, not PBD

**Comment by Nenodema** [comment]
@pippyn 

That was the trick, thanks! So HVC changed PBD to PMD?

**Comment by pippyn** [comment]
No, version 4 of this component is a total rewrite of the code. The old code had become a mess and it was impossible to add features and keep a overview. The code is now way more clean and reliable. But as an unforeseen consequence the PBD and PMD recourses merged into PBD. Sorry for the inconvenience!

**Comment by Nenodema** [comment]
Check, thanks for the explanation. And off course; no problem at all. Thanks for sharing your work and time!

**Comment by yvesfouquet4** [comment]
> 
> 
> Check, thanks for the explanation. And off course; no problem at all. Thanks for sharing your work and time!

How did you change those Icons into those coloured ones?
