### ISSUE TITLE
 Can you add Gemeente Westland (https://www.gemeentewestland.nl/afval/huisvuil.html)

### ISSUE THREAD

**Issue by Carlozzz92** [pippyn/Home-Assistant-Sensor-Afvalbeheer#68]
I live in Gemeente Westland, and i can check my garbage collection at https://www.gemeentewestland.nl/afval/huisvuil.html. is it possible to add this to the waste collectors? an postcode to test with is 2671LZ.

**Comment by pippyn** [comment]
I will look into this

**Comment by Carlozzz92** [comment]
Thanks! if i can be any help, please let me know

**Comment by pippyn** [comment]
I've got some bad news. Their API is bad, really bad. You would be better of with a scraping sensor. I'm sorry

**Comment by Carlozzz92** [comment]
No problem, thank you for you're time
