### ISSUE TITLE
0.109 I/O alert

### ISSUE THREAD

**Issue by mosjonathan** [pippyn/Home-Assistant-Sensor-Afvalbeheer#69]
As written in the release note for 0.109 i report the error log here 
`
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for afvalbeheer doing I/O at custom_components/afvalbeheer/sensor.py, line 496: "{}/rest/adressen/{}-{}".format(self.main_url, self.postcode, self.street_number)).json() `

And

`Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for afvalbeheer doing I/O at custom_components/afvalbeheer/sensor.py, line 512: self.bag_id)).json() `

**Comment by SquareBeard** [comment]
This one too:
`
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for afvalbeheer doing I/O at custom_components/afvalbeheer/sensor.py, line 445: self.main_url, self.address_id, self.street_number, self.postcode)).json()
`

I guess it is the same for each collector

**Comment by ericvb** [comment]
Two other ones for the waste collector : Ophaalkalender 

```
    Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for afvalbeheer doing I/O at custom_components/afvalbeheer/sensor.py, line 430: self.main_url, self.street_name, self.postcode)).json()
    Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for afvalbeheer doing I/O at custom_components/afvalbeheer/sensor.py, line 445: self.main_url, self.address_id, self.street_number, self.postcode)).json()
```

**Comment by pippyn** [comment]
thank you for reporting this issue. I will write a fix asap

**Comment by sanderlv** [comment]
here too:
![image](https://user-images.githubusercontent.com/16528916/80634694-2378d580-8a5b-11ea-913f-bcf91cab3c49.png)

**Comment by pippyn** [comment]
It's a warning that the code can be made more efficient. To be clear: not an error. 
I'll adjust my code to make it comply with the new rules so the warning will go away and HA be more stable.

ps Thanks @sanderlv :)

**Comment by elRadix** [comment]
Using ophaalkalender as waste provider:

`[homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for afvalbeheer doing I/O at custom_components/afvalbeheer/sensor.py, line 445: self.main_url, self.address_id, self.street_number, self.postcode)).json()`

**Comment by phdelodder** [comment]
Found another one:
2020-04-30 10:32:41 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for afvalbeheer doing I/O at custom_components/afvalbeheer/sensor.py, line 430: self.main_url, self.street_name, self.postcode)).json()

**Comment by pippyn** [comment]
Thank you, but you can stop reporting the warnings. It's all the same warning

**Comment by pippyn** [comment]
Should all be fixed in v4.1.6

**Comment by lolfonfire** [comment]
Hi Pippyn,

Confirmed!
Installed v4.1.6 + reboot Home Assistant!

Thanks again!
keep up the good work

**Comment by mosjonathan** [comment]
Hi pippyn,

I can also confirm that it is solved.

Thanks for the quick fix and thanks for the good work on this component.

**Comment by prsantos** [comment]
With HA Core 0.109.3, installed v4.16 + reboot HA and same error.
-------
Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 6:47:56 PM (252 occurrences)
Last logged: 7:22:03 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for samsungtv_tizen doing I/O at custom_components/samsungtv_tizen/upnp.py, line 28: response = requests.post("http://{host}:9197/upnp/control/{protocole}1".format(host=self.host, protocole=protocole), data=body, headers=headers, timeout=0.1)

**Comment by pippyn** [comment]
That is not an error from this sensor. But from a component named `samsungtv_tizen `.

**Comment by prsantos** [comment]
sorry, wrong place :)

Regards
