### ISSUE TITLE
PMD give no date by HVC

### ISSUE THREAD

**Issue by jvanderkroon** [pippyn/Home-Assistant-Sensor-Afvalbeheer#7]
The sensor gives no dates for PMD. I think the json has changed.

In the json response i found 2 times a plastic "menu_title"
the first is "menu_title":"Plastic, blik & drinkpakken", and this one have the correct date
the seccond one is "page_title":"plastic gemeente Dordrecht", and have no date

this is the json https://inzamelkalender.hvcgroep.nl/rest/adressen/0505200000065378/afvalstromen

**Comment by pippyn** [comment]
Then the list item for resources should be PBD, not PMD

**Comment by jvanderkroon** [comment]
thnx after changing PMD to PBD the sensor works again.
