### ISSUE TITLE
Sort by Date

### ISSUE THREAD

**Issue by Bergerie** [pippyn/Home-Assistant-Sensor-Afvalbeheer#70]
Is it possible to display collection dates based on chronological calendar dates?

**Comment by pippyn** [comment]
Can please explain a bit more?

**Comment by Bergerie** [comment]
Currently the calendar is displayed according to the fixed entries of the glance or entities card, e.g.
Restafval 14-05-2020
GFT 13-05-2020
Papier 22-05-2020
PMD Today, 30-04-2020
Though I would have loved to see it being displayd as:
PMD Today, 30-04-2020
GFT 13-05-2020
Restafval 14-05-2020
Papier 22-05-2020

I'm currently playing around with the state_attr: Sort-date using the auto-entities HAC plug in which is supposed to automatically populate the entities list of lovelace cards but have not got that far yet. Hence my request.

**Comment by pippyn** [comment]
Ahh i see. There is already a option for that in combination with the [Home Feed Card](https://community.home-assistant.io/t/lovelace-home-feed-card/103719)

You'll need to set the option `dateobject: 1` in the sensor config

Please read [this issue](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/52)

**Comment by pippyn** [comment]
I forgot to say:
You can ofcourse use the attribute `Sort-date `, it's already in every resource sensor.
Look at this issue https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/33

**Comment by Bergerie** [comment]
Thanks a lot, just the right lead!
