### ISSUE TITLE
Helmond afvalapp

### ISSUE THREAD

**Issue by Roger-NL1975** [pippyn/Home-Assistant-Sensor-Afvalbeheer#71]
Hi Pippyn,

could you also check for Helmond? they use http://www.deafvalapp.nl
would like to see it work.

thanks in advance

**Comment by pippyn** [comment]
deafvalapp is already supported.

**Comment by Roger-NL1975** [comment]
need to look at it again then, didn't get it to work???
keep u posted if I fail again
:(

**Comment by pippyn** [comment]
Set the config for the sensor. Reboot your HA. wait a few minutes to see if the sensors work.
If not, post your config here in a code block and I will have a look.

**Comment by Roger-NL1975** [comment]
I got it to work easily this time, 
My last try was e few weeks ago and I failed to check for updates Today...
Nice work, I see the afvalApp is a recently added feature. (20-4-2020)
because it wasn't in my sensor.py file   

thx again keep up the good work
