### ISSUE TITLE
[homeassistant.util.async_] Detected I/O inside the event loop

### ISSUE THREAD

**Issue by lolfonfire** [pippyn/Home-Assistant-Sensor-Afvalbeheer#72]
Hi pippyn,

I've updated Home Assistant to it's latest version: v0.109.1
Since the update I see this error in my "home-assistant.log":

WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for afvalbeheer doing I/O at custom_components/afvalbeheer/sensor.py, line 430: self.main_url, self.street_name, self.postcode)).json()

Your Afvalbeheer integration still works. The only thing I see is this warning in the logfile.
Before the HA update I was running HA v0.108.9. I always keep HACS and your integration up-to-date. So the only thing which changed was Home Assistant update.

After I saw this Warning I also installed latest HACS + Afvalbeheer version.
Warning is still present after HA reboot.

Currently running this setup:
HA: v0.109.1
HACS: 0.24.3
Afvalbeheer v4.1.5

Thanks in advance!

**Comment by pippyn** [comment]
I'm well aware https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/69

**Comment by lolfonfire** [comment]
Ok!
Sorry didn't see open issue "0.109 I/O alert".
My bad!

Really like your work!
