### ISSUE TITLE
residual waste on demand ( Circulus-Berkel )

### ISSUE THREAD

**Issue by jerepeer** [pippyn/Home-Assistant-Sensor-Afvalbeheer#73]
Hi Pippyn,

Since Circulus-Berkel changed the wasteflow to residual waste on demand, it won't show anymore in HA. On their website it's still visible. Do I have to change my "restafval" resource in something different ? Thx !

![afbeelding](https://user-images.githubusercontent.com/56473045/80799964-8a57d500-8ba8-11ea-8e6d-d5fca2b528a1.png)

![afbeelding](https://user-images.githubusercontent.com/56473045/80799980-993e8780-8ba8-11ea-8344-6d63c2e4ff09.png)

**Comment by pippyn** [comment]
Can you give me a postcode and street number to test with?

**Comment by jerepeer** [comment]
7314 LJ 100 ( random neighbor 🤡 )

**Comment by pippyn** [comment]
rename `restafval` to `best` under resources. Does that work?

**Comment by jerepeer** [comment]
It works but i get the date of the BEST bag instead of the 'grey' container.

**Comment by pippyn** [comment]
for the address you gave me, there is no rest:
![image](https://user-images.githubusercontent.com/7591990/80805015-24267e80-8bb7-11ea-997c-9488a7353ff0.png)

**Comment by jerepeer** [comment]
Ahhh i see.. they don't have 'rest', so it won't show up.  Change it to 7314 LL 13

**Comment by pippyn** [comment]
Also no `rest` for that location.😅 
Please check the address first:
https://afvalkalender.circulus-berkel.nl/

**Comment by jerepeer** [comment]
wtf :) See the difference ..weird !

7314 LJ 100
![2020-05-01 14_35_54-Greenshot](https://user-images.githubusercontent.com/56473045/80805792-386b7b00-8bb9-11ea-9dd4-1bb8a397d2bc.png)


7314 LL 13
![2020-05-01 14_32_39-Greenshot](https://user-images.githubusercontent.com/56473045/80805594-c09d5080-8bb8-11ea-81c0-d7a292e71b57.png)

**Comment by pippyn** [comment]
Ahh.. So they are changing to a new API (?)
Just to be sure: they collect `rest` waste were you live?

**Comment by jerepeer** [comment]
Yes at my place They collect waste On demand Just like On number 13 😋 ( het is nu groen, pmd, papier en voor degenen die zich hebben aangemeld dus nog grijs maar daar moet je de container voor aanmelden bij leging. Maar ze rijden dus wel vaste dagen in de maand )

**Comment by pippyn** [comment]
well because it's on demand the API this sensor uses doesn't have a collection date. I'll have a look if I can integrate the new API (if I can figure out how it works ;) )

**Comment by jerepeer** [comment]
The weird thing is the (possible) collectdates  does show up for rest in the agenda if you use a postal code which still has a restcontainer... why doesnt the API work then ... thanx for giving it a shot 🙂

**Comment by pippyn** [comment]
I don't get what you mean? Agenda? In lovelace?

**Comment by jerepeer** [comment]
Sorry, the calendar on their website. The one which shows rest On 7314LL33 and nothing On 7314LJ100

**Comment by pippyn** [comment]
That's because the calendar uses the new API I think.

**Comment by jerepeer** [comment]
Hope you can sort it out 🥳

**Comment by pippyn** [comment]
I did some research:
It should be possible to switch over to the new API, but it a lot more complicated.
I'll do some work on this, but don't expect it to be ready within a week.
I found some working javascript code that i can translate to python I think.
I'll keep you posted

**Comment by pippyn** [comment]
Can you test a beta?
Replace the contents of sensor.py with 
https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/TwenteMilieu/custom_components/afvalbeheer/sensor.py

**Comment by jerepeer** [comment]
Thx, but still no result. Also reinstalled the integration. 

![2020-05-04 14_14_31-Greenshot](https://user-images.githubusercontent.com/56473045/80964830-d22d6500-8e11-11ea-8570-caff5475d841.png)

Other entities work. Ps Address is correct ;)

**Comment by pippyn** [comment]
Are you sure? Did you wait a minute for the sensor to update?
For me this config is working with rest:
```
- platform: afvalbeheer
  wastecollector: circulus-berkel
  resources:
    - restafval
    - gft
    - papier
    - pmd
    - best
  postcode: 7314LL
  streetnumber: 13
```

**Comment by jerepeer** [comment]
Nope.. did a copy/paste ( .py file  &  above settings in sensor.yaml ) just to be sure.. restarted... waited for 5 minutes... others work... crap :/

**Comment by pippyn** [comment]
What about the test address? Does that work?
`  postcode: 7314LL
  streetnumber: 13`

**Comment by jerepeer** [comment]
I tested 7314LL13 indeed just to be sure but nope...

**Comment by pippyn** [comment]
Are you sure you are using the beta code? Because I tested this on multiple systems and I don't see a way why this should be different for you.

**Comment by jerepeer** [comment]
check double check tripple check etc ... 

What's your Tweakers name?  Maybe a PM would be better than 'polluting' the thread ( although it fits the subject haha)

**Comment by pippyn** [comment]
I'm no longer on tweakers. You can DM me on the [community forum](https://community.home-assistant.io/u/pippyn/) if you like

**Comment by jerepeer** [comment]
Hi Pippyn,

The latest update ( 4.2.7 ) did the trick. It’s working ! Waarvoor dank ;)
