### ISSUE TITLE
Possible to add Limburg.NET

### ISSUE THREAD

**Issue by gijbelsy** [pippyn/Home-Assistant-Sensor-Afvalbeheer#77]
Hi

Is it possible to add Limburg.NET to the integration?
I've already have this running with the REST api of HA, but it would be nicer to have it in an integration.
Besides, this one has more features than the one I currently use.

Here's my code, might be something to start with:

`- platform: rest
  resource: https://api.limburg.net/public/volgende-afval-ophaling/71037?straatNummer=XXXXXXX&huisNummer=XXXXXX
  method: GET
  name: afval_ophaling
  scan_interval: 3600
  json_attributes:
    - datum
    - fracties
- platform: template
  sensors:
    afval_ophaling_soort:
      value_template: "{{ states.sensor.afval_ophaling.attributes.fracties[0].name }}"
      friendly_name: Type afval
      entity_picture_template: >
        {% set mapper = {'Grofvuil': '/local/limburgnet/grofvuil.png',
                       'Huisvuil': '/local/limburgnet/restafval.png',
                       'Metalen': '/local/limburgnet/metaal.png',
                       'Papier & karton': '/local/limburgnet/papier.png',
                       'Pmd': '/local/limburgnet/pmd.png',
                       'Groenafval': '/local/limburgnet/tuinafval.png'} %}
        {% set state = states('sensor.afval_ophaling_soort') %}
        {{ mapper[state] if state in mapper else '/local/limburgnet/recycleebaar.png' }}
    afval_ophaling_datum:
      friendly_name: Datum
      icon_template: >
          {%if as_timestamp(states.sensor.afval_ophaling.attributes.datum) | timestamp_custom('%D') != as_timestamp(now()) | timestamp_custom('%D') %}
            mdi:calendar
          {% else %}
            mdi:calendar-alert
          {% endif %}
      value_template: "{{ as_timestamp(states.sensor.afval_ophaling.attributes.datum) | timestamp_custom('%A %d/%m/%Y') }}"`

The straatNummer is a nummeric value, corresponding to an ID of the Limburg.NET database.

This api call only queries the next waste-collection.
There is also one available for long-term waste-collection dates, but I haven't investigated that one.

**Comment by pippyn** [comment]
I'll have a look:)

**Comment by pippyn** [comment]
Do you have a cityname, steetname and streetnumber for me to test with?

**Comment by gijbelsy** [comment]
You might use Hasselt, Grote Markt, 13.

**Comment by pippyn** [comment]
Can you test a Beta?
Replace the contents of sensor.py with:
https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/Limburg.net/custom_components/afvalbeheer/sensor.py

Your config should look something like:
```
- platform: afvalbeheer
  wastecollector: Limburg.net
  resources:
    - restafval
    - gft
    - papier
    - pmd
  cityname: Hasselt
  streetname: Grote Markt
  streetnumber: 13
```

**Comment by pippyn** [comment]
Does it work for you?

**Comment by gijbelsy** [comment]
Hi
Sorry for the late reply, but I was unable to test it sooner.
First testings prove it's working perfectly! 👍 :)

Just a remark:
The resources only handle:
    - restafval
    - gft
    - papier
    - pmd

Is it possible to add:
  - metalen/glas (same pickup round)
  - grofvuil
  - groenafval (differs from gft)

I expect in the near future a new resource: plastic.

**Comment by pippyn** [comment]
Grofvuil is already supported. But the address you gave me just supports:
```
- restafval
- gft
- papier
- pmd
- grofvuil
- textiel
```
Can you give me an address that also supports `metalen/glas` and `groenafval`

**Comment by gijbelsy** [comment]
Try: Beringen, Koersel-Dorp, 81

If you use Genk Maaseikerbaan 1
this address has also the plastics I was talking about.

In the code provided I only saw the options listed below, in the example config.
That's why I assumed that  grofvuil wasn't supported.
    - restafval
    - gft
    - papier
    - pmd

**Comment by pippyn** [comment]
The address you gave me **does not** have the fraction `plastics`. Did you check on [the site](https://limburg.net/afvalkalender)?

That being said: If you know the naming of the fractions you can just add them under resources.
So if i add groenafval it just works for me?
```
- platform: afvalbeheer
  wastecollector: Limburg.net
  resources:
    - restafval
    - gft
    - papier
    - pmd
    - textiel
    - groenafval
  cityname: Beringen
  streetname: Koersel-Dorp
  streetnumber: 81
```

**Comment by gijbelsy** [comment]
Hi pippyn

The plastics is only available for the address in Genk.
Limburg.NET has different services for different cities. Some have plastics, some don't, some have gft, others haven't.

Anyway: I've tested the resources by using the faction namings provided by the api.
I don't see how this can work because the code doesn't have mappings for 'huisvuil' (restafval) & papier-karton (papier).
As a result these sensors remain empty.

**Comment by pippyn** [comment]
The mapping is only used to rename fractions. for example `huisvuil` is renamed to the more common 'restafval' and `papier-karton` to the shorter `papier` to get the same fraction names for all the API's. But it is also used for some addresses to rename `papier opgehaald aan de schoolstraat` to `papier`. So if the fraction is renamed, you'll have to use the renamed option. In your case `papier-karton` is not going to work, but `papier` is.

That being said; a fraction doesn't have to be renamed. In your case: `groenafval` is in the api response and is not renamed, so it just works when you add it under resources.

Can you see what the name is for plastics in the api response? Can you try adding the name as is under resources? Does that work?

The day prefix is only shown when a date is close to today (within a week). That's because when a collection is scheduled 3 months from now for example, it doesn't say much if that's a monday. If you don't like that you can turn it off with `dateonly: 1`

**Comment by gijbelsy** [comment]
Ah, that explains it all a bit.

The plastics resource is named 'plastics'. So that will do the trick.
About the 'groenafval', this works indeed as I add it to the resources section with the exact naming as provided by the API.

As the prefix is concerned: This is indeed a good method to indicate the upcoming date. I didn't notice this, but is clear now.

It seems that the sensor is working properly, I'll test it further but for the moment I don't see any issues.
Thanks a lot for the update.

I have another feature request, shall I open another thread or continue with this one. It's about the upcoming event.

**Comment by pippyn** [comment]
I'm glad it's more clear now. Sorry for the confusion. I'll release an update in a few minutes with the Limburg.net added.

It would be wise to open a new issue for the feature request. I'm closing this one. :)
