### ISSUE TITLE
Add RD4

### ISSUE THREAD

**Issue by 123paultje** [pippyn/Home-Assistant-Sensor-Afvalbeheer#78]
Is it possible for you to add RD4? It was added a few days after you forked the ForumHulp code.
It would be very nice when we can use this addon in limburg also!

https://github.com/ForumHulp/Home-Assistant-Sensor-Afvalbeheer

https://github.com/ForumHulp/rd4

**Comment by pippyn** [comment]
I didn't fork their code, this is an original project. ForumHulp forked my code. 
I'll look into it. I would have to find an API. Because the code from ForumHulp is a scraper.
Will let you know

**Comment by 123paultje** [comment]
tnx for the quick reply. It looked like that in the network view, but now in see your name there!

Should be very nice if you find a solution

**Comment by pippyn** [comment]
Do you have a postcode and streetnumber for me to test with?

**Comment by 123paultje** [comment]
6291cb 7

**Comment by pippyn** [comment]
Can you test a beta? replace the contents of sensor.py with this:
https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/RD4/custom_components/afvalbeheer/sensor.py

**Comment by 123paultje** [comment]
It's working!! thank you very much!!

**Comment by pippyn** [comment]
Nice I'll do some final tests and then release a new version

**Comment by 123paultje** [comment]
tnx for the very quick integration!

**Comment by pippyn** [comment]
Added in v4.2.2
