### ISSUE TITLE
Please support afvalportaal.2go-mobile.com

### ISSUE THREAD

**Issue by Tosko4** [pippyn/Home-Assistant-Sensor-Afvalbeheer#8]
Hi there, 

This is not an issue or bug report, but more a request to help me out implementing this page:

Thttps://afvalportaal.2go-mobile.com/modules/53d8db94-7945-42fd-9742-9bbc71dbe4c1/kalender/

Is there any way this platform could be integrated? Thanks in advance!

**Comment by pippyn** [comment]
Do you have a postcode and street number for me to test with?

**Comment by Tosko4** [comment]
1339NB
20

@pippyn

**Comment by pippyn** [comment]
I'm sorry, but the api is not the same as the one this sensor uses. It differs too much to integrate.

**Comment by Tosko4** [comment]
got it to work, thanks anyway

**Comment by pippyn** [comment]
just out of interest, did you make your own sensor or did you use this sensor with tweaks?

**Comment by Tosko4** [comment]
It is a different sensor which I’ve used. I grabbed someones sensor and tweaked it to work with the area/website I need it to work with. 

https://github.com/yniezink/twentemilieu/blob/master/sensor.py
