### ISSUE TITLE
Not able to uninstall Sensor Ophaalkalender in HACS.

### ISSUE THREAD

**Issue by wimpie007** [pippyn/Home-Assistant-Sensor-Afvalbeheer#80]
![image](https://user-images.githubusercontent.com/33153228/81047669-30fae900-8ebb-11ea-9d4a-d5ec25010b6d.png)

Afvalbeheer is already installed.

**Comment by pippyn** [comment]
just delete the folder `ophaalkalender` in custom_components

**Comment by wimpie007** [comment]
already tried it without luck.
Ended up editing hacs.repositories in .storage. (installed=false, and installed_commit "") 
After reboot it was ok.
Thanks for the nice sensors and the fast reply!

Bedankt! :)

**Comment by pippyn** [comment]
Glad you got it sorted!
