### ISSUE TITLE
sensor pmd circulus berkel not working

### ISSUE THREAD

**Issue by mosjonathan** [pippyn/Home-Assistant-Sensor-Afvalbeheer#81]
Hello Pippyn,

after the latest update the pmd sensor stop working again.

a few day's ago you made a fix for this sensor see issue #62 
is it possible that it got reverted?

sensor papier and gft are working
address to test with:
7204pk 55

**Comment by pippyn** [comment]
I'm so sorry. I changed the api of circulus berkel to the new one and forgot about this issue. It's fixed in version v4.2.1

**Comment by mosjonathan** [comment]
Thanks fox the super quick fix!

and thanks for this nice custom component
