### ISSUE TITLE
No Waste data found!

### ISSUE THREAD

**Issue by frankverheyen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#82]
Hi, great component. I really would like to use it, but I have problems.
After installing and configuring afvalbeheer, I get the following error in my log:
Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:296
Integration: afvalbeheer (documentation)
First occurred: 5:32:27 PM (1 occurrences)
Last logged: 5:32:27 PM
No Waste data found!

My configuration:
 - platform: afvalbeheer
    wastecollector: ophaalkalender
    resources: 
      - restafval
      - papier
      - pmd
    postcode: 2660 
    streetname: steynstraat
    streetnumber: 168
    upcomingsensor: 1
    dateformat: '%d-%m-%Y'
    dateonly: 0                      
    dateobject: 0                    
    name: ''                        
    nameprefix: 1                    
    builtinicons: 0                  
    disableicons: 0                  
    dutch: 1    

Home Assistant 0.109.4, running on rpi4.
Location: Belgium
Not sure if this is a problem with the sensor or with the available data. I already changed the tls configuration as per advice of Paul Vanderperren, but it still doesn't work.
Thanks for your support.

**Comment by pippyn** [comment]
I think its not the sensor. If I go to https://www.ophaalkalender.be/Calendar I can't get any data for your address. (can you?) 

You can maybe contact ophaalkalender.be to to get to know what the issue is.

**Comment by frankverheyen** [comment]
Thx for your feedback. I'm not getting any data back through the online calendar for whatever address I use. When I install the app from the same website, I get all data. I thought it was a problem with my pc.
So when you try other addresses (in Belgium), you are getting information, but not from my address, correct? 
I already tried to contact ophaalkalender.be, but until now I did not get any response from them.

**Comment by pippyn** [comment]
Yes. I did a test to make sure:
![image](https://user-images.githubusercontent.com/7591990/81100042-2583de00-8f0c-11ea-8db8-80eb34082b5e.png)
Hopefully they get back to you soon!

**Comment by frankverheyen** [comment]
Ok, many thanks for your support and your outstanding work!! I hope they will get back to me!
Stay safe!
Kind greetings,Frank

**Comment by pippyn** [comment]
Thanks for the kind words. 
Let me know if do hear back :)
You too!

**Comment by frankverheyen** [comment]
Hi pippyn,
I already received feedback from ophaalkalender.be. Unfortunately it is a bit of bad news (maybe).
Apparantly they are replacing the website piece by piece. This could be the reason that my data is not available anymore. I’m not sure they will support API calls in the future.
![BA92AEFC-D0DE-4547-8E49-60F204515995](https://user-images.githubusercontent.com/62702154/81165771-d7fe8400-8f92-11ea-88da-3d978ec02e0c.png)

Thanks for your support!
