### ISSUE TITLE
Keeps asking to restart Home Assistant

### ISSUE THREAD

**Issue by dewafre** [pippyn/Home-Assistant-Sensor-Afvalbeheer#84]
After installing, configuration and restarting he keeps asking to restart:
_Restart pending
You need to restart Home Assistant_

**Comment by pippyn** [comment]
In HACS you mean? This is not the support for HACS.
But I would delete the folder in custom_components. Restart HA. Reinstall the sensor and restart HA again? If that doesn't work make an issue on the HACS github.
