### ISSUE TITLE
Postcal code is not working

### ISSUE THREAD

**Issue by RualdOrdelman** [pippyn/Home-Assistant-Sensor-Afvalbeheer#85]
Hi there,

Thanks for creating this great integration. I tried to use my personal postal code but that doesn't work. When I tried with the postal code from my parents, that works oke. I live in Apeldoorn and use Circulus-Berkel as wastecollector. 

My current house is build three years ago, but also my previous house that is build 10 years ago isn't recognized. 

Is it possible to integrate that new postal codes or do you integrate with the api of Circulus-Berkel?

Best regards

**Comment by pippyn** [comment]
Would be nice if you shared more info. I need the postcode and street number to do some tests.

Does the website https://mijn.circulus-berkel.nl/afvalkalender/ give you the correct information?

**Comment by RualdOrdelman** [comment]
Sorry, I don't want to share my postal code and house number in public. I will try to send that in a personal message. 

When I look at the Circlus-berkel website it shows the right information with the upcoming events for my postal code/house number.

**Comment by pippyn** [comment]
I understand ofcourse. DM me on the community forum
