### ISSUE TITLE
Home assistant logs give warning

### ISSUE THREAD

**Issue by Tiebe** [pippyn/Home-Assistant-Sensor-Afvalbeheer#87]
`2020-05-08 10:31:21 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for afvalbeheer doing I/O at custom_components/afvalbeheer/sensor.py, line 503: self.bag_id)).json()`

Just going to put this here in case you want to do something with it, but otherwise you can ignore this issue.

**Comment by pippyn** [comment]
You are using an old version. This is fixed in the current version
