### ISSUE TITLE
Feature request: 'Upcoming event'

### ISSUE THREAD

**Issue by gijbelsy** [pippyn/Home-Assistant-Sensor-Afvalbeheer#88]
The component generates 2 extra sensors: '_vandaag' & '_morgen'.
Is it possible to create some sort of '_upcoming' sensor, this provides the date and the resource for the next garbage pickup.
This way I'ts easelly to view which resource will be picked-up next.

This could probably be achieved with a script/automation within HA, but since there is the '_vandaag' & '_morgen' sensor, it might be nice to have this one too.

**Comment by pippyn** [comment]
I'll think about adding a dedicated sensor. But for now you can accomplice the same with lovelace and a few options of this sensor.
look at this issue:
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/70

**Comment by pippyn** [comment]
Can we close this issue?
