### ISSUE TITLE
Feature request: customizable icons

### ISSUE THREAD

**Issue by gijbelsy** [pippyn/Home-Assistant-Sensor-Afvalbeheer#89]
I don't know if this one's possible already: To have a set of custom icons defined by the user, for each resource.
In my HA www folder I have a set of png icons related to the garbage pick up.
Is it possible to use these in stead of the embedded component icons?

Perhaps that the component might have an additional 'icon location' parameter. If filled out it searches for the icons in that particular folder.
Each icon must be named after the resource name provided in the sensor config. (i.e. 'restafval.png, 'pmd.png', ...)

**Comment by pippyn** [comment]
this can be done with default HA options:
https://www.home-assistant.io/docs/configuration/customizing-devices/
or in gui:
hassio.local/config/customize
