### ISSUE TITLE
Add glass to wastecollecter Limburg.net

### ISSUE THREAD

**Issue by KristofVr** [pippyn/Home-Assistant-Sensor-Afvalbeheer#92]
Hello,

Is it possible to add glass to the wastecollecter Limburg.net?

I added the following config to my sensor.yaml file.
  - platform: afvalbeheer
    wastecollector: Limburg.NET
    resources:
        - 'restafval'
        - 'papier'
        - 'pmd'
        - 'glas'
    cityname: Dilsen-Stokkem
    postcode: 3650
    streetname: xxxxxxx
    streetnumber: xxx
    upcomingsensor: 0
    dateformat: '%d/%m/%Y'
    dateonly: 1
    dutch: 1
    builtinicons: 1

All the resources are working fine except glass.
![image](https://user-images.githubusercontent.com/7521092/82048353-d3358080-96b4-11ea-8ce3-38108686e1bf.png)

Checking the Limburg.net calender it should give me a date back.
![image](https://user-images.githubusercontent.com/7521092/82048484-1132a480-96b5-11ea-9295-4f322c897881.png)

**Comment by pippyn** [comment]
Are you able to test a beta?
replace the contents of sensor.py with:
https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/master/custom_components/afvalbeheer/sensor.py
and restart HA.
Does that work?

**Comment by KristofVr** [comment]
Thank you for the quick response. This solved the issue.

**Comment by pippyn** [comment]
added in version 4.2.7
