### ISSUE TITLE
Circulus-Berkel changed Paper value

### ISSUE THREAD

**Issue by volrath911** [pippyn/Home-Assistant-Sensor-Afvalbeheer#93]
Hi, 

just noticed paper didn't show up correctly for my area. 
Looking at the API,  for the town I live in (EPE), DROCODEV was changed to DROCOEPE. 
It looks like Drocodev was used for the town Deventer. 

Is there a way you can change this based on the postalcode? 
I've changed the mapping value 'DROCODEV': WASTE_TYPE_PAPER, to  'DROCOEPE': WASTE_TYPE_PAPER, on row 466 in the sensor.py to make it work for my own environment.

![image](https://user-images.githubusercontent.com/31466949/82248180-fd52a100-9947-11ea-88f0-fea427506946.png)
![image](https://user-images.githubusercontent.com/31466949/82248214-0a6f9000-9948-11ea-949f-2275b2969c21.png)

Thank you for the great plugin!!!
I love it
 
Volrath

**Comment by pippyn** [comment]
Thank you for reporting this issue.
Fixed in v4.2.8
