### ISSUE TITLE
Not working since the last HA update 

### ISSUE THREAD

**Issue by Serban1977** [pippyn/Home-Assistant-Sensor-Afvalbeheer#94]
Hello,

 I updated this morning the OS to Home Assistant 0.110.0 and i noticed that the integration was not working anymore.

 i updated Afvalbeheer with HACS to v4.2.8 but i get the same status to the sensor.avalex -> unknown

here is my code from config that was working fine till this morning:

sensor:
  - platform: afvalbeheer
    wastecollector: Avalex
    resources:
      - gft
      - restafval
      - papier
    postcode: 2241JT
    streetnumber: 14
    upcomingsensor: 1                
    builtinicons: 1       
    dateformat: '%d-%b'           

Appreciate some feedback on what can i try next... 

Best,

S.

**Comment by pippyn** [comment]
It is not the upgrading of your system or the HACS update that is causing this issue.
I looked at the [API response](https://www.avalex.nl/rest/adressen/0629200000010441/afvalstromen) of Avalex for your address and it has no collection dates in it.
Maybe Avalex switched API's (as a lot of waste collectors seem to do). I'll look into it!

**Comment by pippyn** [comment]
I notice now that https://www.avalex.nl/kalender has an empty calendar for your address... 
Did they change something in your area? or maybe the Avalex service is down for the moment? Maybe you can you give them a call?

**Comment by Serban1977** [comment]
Ups... I should have checked first...  Its easy to jump to wrong conclusions :-( . 

They seem to have wider problem as i checked other post codes as well and looks broken. 

Will verify in the next days and update the thread here 

Best,

Serban

**Comment by Serban1977** [comment]
Avalex fix their issues and the HA integration works as usual. 

Thanks a lot - love the integration
