### ISSUE TITLE
Waste Collector Area Reiniging not found

### ISSUE THREAD

**Issue by JanLankhorst** [pippyn/Home-Assistant-Sensor-Afvalbeheer#97]
For some reason Area Reininging is not working. Could you have a look if the ' waste collector list' 
 is complete?
I used the HACS installation procedure.
greeting,
jan

Part of Log:
Logger: homeassistant.helpers.entity
Source: custom_components/afvalbeheer/sensor.py:324
First occurred: 7:48:38 AM (156 occurrences)
Last logged: 8:01:33 AM

* Update for sensor.area_reiniging_gft fails
* Update for sensor.area_reiniging_papier fails
* Update for sensor.area_reiniging_pmd fails
* Update for sensor.area_reiniging_vandaag fails
* Update for sensor.area_reiniging_morgen fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 1124, in update
    collection = self.data.collections.get_first_upcoming_by_type(self.waste_type)
  File "/config/custom_components/afvalbeheer/sensor.py", line 324, in collections
    return self.collector.collections
AttributeError: 'NoneType' object has no attribute ‘collections'

Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:215
Integration: afvalbeheer (documentation)
First occurred: 7:48:07 AM (1 occurrences)
Last logged: 7:48:07 AM

Waste collector "area reiniging" not found!

**Comment by pippyn** [comment]
The waste collector should be `area`, not `area reiniging`.
I'll write a fix so both will work.

**Comment by pippyn** [comment]
Starting from v4.2.10 you should use `AreaReiniging`. (pre v4.2.10 it was `Area`)

**Comment by JanLankhorst** [comment]
Ah oke, docs are not in sync then. No problem. Thank for the good work

**Comment by pippyn** [comment]
Docs are fixed now

**Comment by pippyn** [comment]
Can we close this issue?

**Comment by JanLankhorst** [comment]
yes; thanks

**Comment by JanLankhorst** [comment]
.
