### ISSUE TITLE
Feature request: 'name of day' at 'restafval' sensor 

### ISSUE THREAD

**Issue by wilfredsmit** [pippyn/Home-Assistant-Sensor-Afvalbeheer#99]
Hi,

Is it possible to add the name of day at all sensors. I'm missing the name of day at the 'restafval' sensor. That way it's more consistently.

Greets,

/Wilfred

**Comment by pippyn** [comment]
install v4.2.12. Restart HA

add the option `alwaysshowday: 1` to your config and restart HA again

**Comment by wilfredsmit** [comment]
After an update to version 0.110.3 it is functioning! Thanks!
